/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */
 
#ifndef KOTLIN_NATIVE_TEST_H
#define KOTLIN_NATIVE_TEST_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// ╔════════════════╗
// ║     stdlib     ║
// ╚════════════════╝

typedef int32_t  KInt;
typedef int64_t  KLong;
typedef float    KFloat;
typedef double   KDouble;
typedef int8_t   KByte;
typedef int16_t  KShort;
typedef bool     KBoolean;
typedef uint16_t KChar;

typedef struct KString {
    const char* data;
    KInt length;
} KString;

inline KString makeKString(const char* data, const KInt length) {
    return (KString) { data, length };
}

#define KArrayDef(Name, Type)	                                \
typedef struct Name {			                                \
    const Type elements;				                        \
    KInt size;				                                    \
} Name;                                                         \
                                                                \
inline Name make##Name(const Type elements, const KInt size) {  \
    return (Name){ elements, size };                            \
}
KArrayDef(KCharArray,	 KChar*)
KArrayDef(KBooleanArray, KBoolean*)
KArrayDef(KByteArray,	 KByte*)
KArrayDef(KShortArray,	 KShort*)
KArrayDef(KIntArray,	 KInt*)
KArrayDef(KLongArray,	 KLong*)
KArrayDef(KFloatArray,	 KFloat*)
KArrayDef(KDoubleArray,  KDouble*)
KArrayDef(KArray,        void*)
#undef KArrayDef

#define KCallbackDef(Name, Type, ...)		\
struct Name {								\
    void *m;								\
    Type (*invoke)(Name* _, ##__VA_ARGS__);	\
    void (*free)(Name* _);					\
};

// ╔═══════════════════╗
// ║     Type defs     ║
// ╚═══════════════════╝

typedef struct ParentStruct ParentStruct;
typedef struct MyStruct MyStruct;
typedef struct ChildStruct ChildStruct;
typedef struct VoidCallback VoidCallback;
typedef struct CallbackPassChar CallbackPassChar;
typedef struct CallbackPassBoolean CallbackPassBoolean;
typedef struct CallbackPassByte CallbackPassByte;
typedef struct CallbackPassShort CallbackPassShort;
typedef struct CallbackPassInt CallbackPassInt;
typedef struct CallbackPassLong CallbackPassLong;
typedef struct CallbackPassFloat CallbackPassFloat;
typedef struct CallbackPassDouble CallbackPassDouble;
typedef struct CallbackPassString CallbackPassString;
typedef struct CallbackPassCallback CallbackPassCallback;
typedef struct CallbackPassEnum CallbackPassEnum;
typedef struct CallbackPassStruct CallbackPassStruct;
typedef struct CallbackReturnChar CallbackReturnChar;
typedef struct CallbackReturnBoolean CallbackReturnBoolean;
typedef struct CallbackReturnByte CallbackReturnByte;
typedef struct CallbackReturnShort CallbackReturnShort;
typedef struct CallbackReturnInt CallbackReturnInt;
typedef struct CallbackReturnLong CallbackReturnLong;
typedef struct CallbackReturnFloat CallbackReturnFloat;
typedef struct CallbackReturnDouble CallbackReturnDouble;
typedef struct CallbackReturnString CallbackReturnString;
typedef struct CallbackReturnCallback CallbackReturnCallback;
typedef struct CallbackReturnEnum CallbackReturnEnum;
typedef struct CallbackReturnStruct CallbackReturnStruct;
typedef struct CallbackPassCharArray CallbackPassCharArray;
typedef struct CallbackPassBooleanArray CallbackPassBooleanArray;
typedef struct CallbackPassByteArray CallbackPassByteArray;
typedef struct CallbackPassShortArray CallbackPassShortArray;
typedef struct CallbackPassIntArray CallbackPassIntArray;
typedef struct CallbackPassLongArray CallbackPassLongArray;
typedef struct CallbackPassFloatArray CallbackPassFloatArray;
typedef struct CallbackPassDoubleArray CallbackPassDoubleArray;
typedef struct CallbackPassEnumArray CallbackPassEnumArray;
typedef struct CallbackPassStructArray CallbackPassStructArray;
typedef struct CallbackReturnCharArray CallbackReturnCharArray;
typedef struct CallbackReturnBooleanArray CallbackReturnBooleanArray;
typedef struct CallbackReturnByteArray CallbackReturnByteArray;
typedef struct CallbackReturnShortArray CallbackReturnShortArray;
typedef struct CallbackReturnIntArray CallbackReturnIntArray;
typedef struct CallbackReturnLongArray CallbackReturnLongArray;
typedef struct CallbackReturnFloatArray CallbackReturnFloatArray;
typedef struct CallbackReturnDoubleArray CallbackReturnDoubleArray;
typedef struct CallbackReturnEnumArray CallbackReturnEnumArray;
typedef struct CallbackReturnStructArray CallbackReturnStructArray;


// ╔═══════════════╗
// ║     Enums     ║
// ╚═══════════════╝

typedef enum {
	MyEnum_CASE1,
	MyEnum_CASE2
} MyEnum;


// ╔═════════════════╗
// ║     Structs     ║
// ╚═════════════════╝

struct ParentStruct {
	KInt a;
	KInt b;
};

struct MyStruct { // : ParentStruct
	KInt a;
	KInt b;
	KInt c;
	KInt d;
};

struct ChildStruct { // : MyStruct
	KInt a;
	KInt b;
	KInt c;
	KInt d;
	KInt e;
	KInt f;
};

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

KBoolean passVoid();
KBoolean passChar(KChar arg);
KBoolean passBoolean(KBoolean arg);
KBoolean passByte(KByte arg);
KBoolean passShort(KShort arg);
KBoolean passInt(KInt arg);
KBoolean passLong(KLong arg);
KBoolean passFloat(KFloat arg);
KBoolean passDouble(KDouble arg);
KBoolean passString(KString arg);
KBoolean passEnum(MyEnum arg);
KBoolean passStruct(MyStruct arg);
void returnVoid();
KChar returnChar();
KBoolean returnBoolean();
KByte returnByte();
KShort returnShort();
KInt returnInt();
KLong returnLong();
KFloat returnFloat();
KDouble returnDouble();
KString returnStringLiteral();
KString returnString();
MyEnum returnEnum();
MyStruct returnStruct();
KChar pingChar(KChar arg);
KBoolean pingBoolean(KBoolean arg);
KByte pingByte(KByte arg);
KShort pingShort(KShort arg);
KInt pingInt(KInt arg);
KLong pingLong(KLong arg);
KFloat pingFloat(KFloat arg);
KDouble pingDouble(KDouble arg);
KString pingString(KString arg);
MyEnum pingEnum(MyEnum arg);
MyStruct pingStruct(MyStruct arg);
void callbackVoid(VoidCallback* arg);
KBoolean callbackArgChar(CallbackPassChar* arg);
KBoolean callbackArgBoolean(CallbackPassBoolean* arg);
KBoolean callbackArgByte(CallbackPassByte* arg);
KBoolean callbackArgShort(CallbackPassShort* arg);
KBoolean callbackArgInt(CallbackPassInt* arg);
KBoolean callbackArgLong(CallbackPassLong* arg);
KBoolean callbackArgFloat(CallbackPassFloat* arg);
KBoolean callbackArgDouble(CallbackPassDouble* arg);
KBoolean callbackArgString(CallbackPassString* arg);
KBoolean callbackArgCallback(VoidCallback* pass, CallbackPassCallback* arg);
KBoolean callbackArgEnum(CallbackPassEnum* arg);
KBoolean callbackArgStruct(CallbackPassStruct* arg);
KBoolean callbackReturnChar(CallbackReturnChar* arg);
KBoolean callbackReturnBoolean(CallbackReturnBoolean* arg);
KBoolean callbackReturnByte(CallbackReturnByte* arg);
KBoolean callbackReturnShort(CallbackReturnShort* arg);
KBoolean callbackReturnInt(CallbackReturnInt* arg);
KBoolean callbackReturnLong(CallbackReturnLong* arg);
KBoolean callbackReturnFloat(CallbackReturnFloat* arg);
KBoolean callbackReturnDouble(CallbackReturnDouble* arg);
KBoolean callbackReturnString(CallbackReturnString* arg);
VoidCallback* callbackReturnCallback(CallbackReturnCallback* arg);
KBoolean callbackReturnEnum(CallbackReturnEnum* arg);
KBoolean callbackReturnStruct(CallbackReturnStruct* arg);
KBoolean passCharArray(KCharArray arg);
KBoolean passBooleanArray(KBooleanArray arg);
KBoolean passByteArray(KByteArray arg);
KBoolean passShortArray(KShortArray arg);
KBoolean passIntArray(KIntArray arg);
KBoolean passLongArray(KLongArray arg);
KBoolean passFloatArray(KFloatArray arg);
KBoolean passDoubleArray(KDoubleArray arg);
KBoolean passEnumArray(KArray arg);
KBoolean passStructArray(KArray arg);
KCharArray returnCharArray();
KBooleanArray returnBooleanArray();
KByteArray returnByteArray();
KShortArray returnShortArray();
KIntArray returnIntArray();
KLongArray returnLongArray();
KFloatArray returnFloatArray();
KDoubleArray returnDoubleArray();
KArray returnEnumArray();
KArray returnStructArray();
KCharArray pingCharArray(KCharArray arg);
KBooleanArray pingBooleanArray(KBooleanArray arg);
KByteArray pingByteArray(KByteArray arg);
KShortArray pingShortArray(KShortArray arg);
KIntArray pingIntArray(KIntArray arg);
KLongArray pingLongArray(KLongArray arg);
KFloatArray pingFloatArray(KFloatArray arg);
KDoubleArray pingDoubleArray(KDoubleArray arg);
KArray pingEnumArray(KArray arg);
KArray pingStructArray(KArray arg);
KBoolean callbackArgCharArray(CallbackPassCharArray* arg);
KBoolean callbackArgBooleanArray(CallbackPassBooleanArray* arg);
KBoolean callbackArgByteArray(CallbackPassByteArray* arg);
KBoolean callbackArgShortArray(CallbackPassShortArray* arg);
KBoolean callbackArgIntArray(CallbackPassIntArray* arg);
KBoolean callbackArgLongArray(CallbackPassLongArray* arg);
KBoolean callbackArgFloatArray(CallbackPassFloatArray* arg);
KBoolean callbackArgDoubleArray(CallbackPassDoubleArray* arg);
KBoolean callbackArgEnumArray(CallbackPassEnumArray* arg);
KBoolean callbackArgStructArray(CallbackPassStructArray* arg);
KBoolean callbackReturnCharArray(CallbackReturnCharArray* arg);
KBoolean callbackReturnBooleanArray(CallbackReturnBooleanArray* arg);
KBoolean callbackReturnByteArray(CallbackReturnByteArray* arg);
KBoolean callbackReturnShortArray(CallbackReturnShortArray* arg);
KBoolean callbackReturnIntArray(CallbackReturnIntArray* arg);
KBoolean callbackReturnLongArray(CallbackReturnLongArray* arg);
KBoolean callbackReturnFloatArray(CallbackReturnFloatArray* arg);
KBoolean callbackReturnDoubleArray(CallbackReturnDoubleArray* arg);
KBoolean callbackReturnEnumArray(CallbackReturnEnumArray* arg);
KBoolean callbackReturnStructArray(CallbackReturnStructArray* arg);
KBoolean jvmci1();
KBoolean jvmci2(KInt a1);
KBoolean jvmci3(KInt a1, KInt a2);
KBoolean jvmci4(KInt a1, KInt a2, KInt a3, KInt a4, KInt a5, KInt a6, KInt a7, KInt a8, KInt a9);
KBoolean jvmci5(KInt a1, KLong a2, KInt a3, KLong a4, KInt a5, KLong a6, KInt a7, KInt a8, KLong a9);
KBoolean jvmci6(KFloat a1, KFloat a2, KFloat a3, KFloat a4, KFloat a5, KFloat a6, KFloat a7, KFloat a8, KFloat a9, KInt a10, KInt a11, KInt a12, KInt a13);
KBoolean jvmci7(KFloat a1, KDouble a2, KFloat a3, KDouble a4, KFloat a5, KDouble a6, KFloat a7, KFloat a8, KDouble a9);
KBoolean jvmci8(KInt a1, KDouble a2, KFloat a3, KLong a4);
KBoolean jvmci9(KInt a1, KDouble a2, KFloat a3, KLong a4, KLong a5, KDouble a6, KFloat a7, KFloat a8, KInt a9);
KBoolean jvmci10(KString a1, KDouble a2, KFloat a3, KLong a4, KLong a5, KDouble a6, KString a7, KFloat a8, KInt a9);
KBoolean jvmci11(KFloat a1, KInt a2, KFloat a3, KInt a4, KFloat a5, KInt a6, KFloat a7, KInt a8, KFloat a9, KInt a10, KFloat a11, KInt a12, KFloat a13, KInt a14, KFloat a15, KInt a16, KFloat a17);
KInt jvmci12();
KLong jvmci13();
KFloat jvmci14();
KDouble jvmci15();
KBoolean jvmciArray(KIntArray array);
KBoolean jvmciSomeArrays(KIntArray array1, KFloatArray array2, KDoubleArray array3);
KBoolean jvmciEnum(MyEnum enum1, MyEnum enum2, KArray enumArray);

// ╔═══════════════════╗
// ║     Callbacks     ║
// ╚═══════════════════╝
// ┌───────┬───────────────────────────┬─────────────┬──────────────────┐
// │  ...  │ Name                      │ Type        │ Args             │
// └───────┴───────────────────────────┴─────────────┴──────────────────┘
KCallbackDef(VoidCallback,               void                           )
KCallbackDef(CallbackPassChar,           KBoolean,     KChar arg        )
KCallbackDef(CallbackPassBoolean,        KBoolean,     KBoolean arg     )
KCallbackDef(CallbackPassByte,           KBoolean,     KByte arg        )
KCallbackDef(CallbackPassShort,          KBoolean,     KShort arg       )
KCallbackDef(CallbackPassInt,            KBoolean,     KInt arg         )
KCallbackDef(CallbackPassLong,           KBoolean,     KLong arg        )
KCallbackDef(CallbackPassFloat,          KBoolean,     KFloat arg       )
KCallbackDef(CallbackPassDouble,         KBoolean,     KDouble arg      )
KCallbackDef(CallbackPassString,         KBoolean,     KString arg      )
KCallbackDef(CallbackPassCallback,       KBoolean,     VoidCallback* arg)
KCallbackDef(CallbackPassEnum,           KBoolean,     MyEnum arg       )
KCallbackDef(CallbackPassStruct,         KBoolean,     MyStruct arg     )
KCallbackDef(CallbackReturnChar,         KChar                          )
KCallbackDef(CallbackReturnBoolean,      KBoolean                       )
KCallbackDef(CallbackReturnByte,         KByte                          )
KCallbackDef(CallbackReturnShort,        KShort                         )
KCallbackDef(CallbackReturnInt,          KInt                           )
KCallbackDef(CallbackReturnLong,         KLong                          )
KCallbackDef(CallbackReturnFloat,        KFloat                         )
KCallbackDef(CallbackReturnDouble,       KDouble                        )
KCallbackDef(CallbackReturnString,       KString                        )
KCallbackDef(CallbackReturnCallback,     VoidCallback*                  )
KCallbackDef(CallbackReturnEnum,         MyEnum                         )
KCallbackDef(CallbackReturnStruct,       MyStruct                       )
KCallbackDef(CallbackPassCharArray,      KBoolean,     KCharArray arg   )
KCallbackDef(CallbackPassBooleanArray,   KBoolean,     KBooleanArray arg)
KCallbackDef(CallbackPassByteArray,      KBoolean,     KByteArray arg   )
KCallbackDef(CallbackPassShortArray,     KBoolean,     KShortArray arg  )
KCallbackDef(CallbackPassIntArray,       KBoolean,     KIntArray arg    )
KCallbackDef(CallbackPassLongArray,      KBoolean,     KLongArray arg   )
KCallbackDef(CallbackPassFloatArray,     KBoolean,     KFloatArray arg  )
KCallbackDef(CallbackPassDoubleArray,    KBoolean,     KDoubleArray arg )
KCallbackDef(CallbackPassEnumArray,      KBoolean,     KArray arg       )
KCallbackDef(CallbackPassStructArray,    KBoolean,     KArray arg       )
KCallbackDef(CallbackReturnCharArray,    KCharArray                     )
KCallbackDef(CallbackReturnBooleanArray, KBooleanArray                  )
KCallbackDef(CallbackReturnByteArray,    KByteArray                     )
KCallbackDef(CallbackReturnShortArray,   KShortArray                    )
KCallbackDef(CallbackReturnIntArray,     KIntArray                      )
KCallbackDef(CallbackReturnLongArray,    KLongArray                     )
KCallbackDef(CallbackReturnFloatArray,   KFloatArray                    )
KCallbackDef(CallbackReturnDoubleArray,  KDoubleArray                   )
KCallbackDef(CallbackReturnEnumArray,    KArray                         )
KCallbackDef(CallbackReturnStructArray,  KArray                         )
#undef KCallbackDef


#ifdef __cplusplus
}
#endif

#endif // KOTLIN_NATIVE_TEST_H