/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */
 
#ifndef KOTLIN_NATIVE_TEST_H
#define KOTLIN_NATIVE_TEST_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef INVOKE
#define INVOKE(callback, ...) callback->invoke(callback, ##__VA_ARGS__)
#endif // INVOKE

#ifndef FREE_CALLBACK
#define FREE_CALLBACK(callback) callback->free(callback)
#endif // FREE_CALLBACK

typedef struct SimpleCallback SimpleCallback;
typedef struct StringCallback StringCallback;
typedef struct StringPingCallback StringPingCallback;
typedef struct CallbackPingCallback CallbackPingCallback;

/* =================== *\
        Callbacks
\* =================== */

struct SimpleCallback {
	void *m;
	void (*invoke)(SimpleCallback* _, int32_t status);
	void (*free)(SimpleCallback* _);
};

struct StringCallback {
	void *m;
	const char* (*invoke)(StringCallback* _);
	void (*free)(StringCallback* _);
};

struct StringPingCallback {
	void *m;
	const char* (*invoke)(StringPingCallback* _, const char* text);
	void (*free)(StringPingCallback* _);
};

struct CallbackPingCallback {
	void *m;
	SimpleCallback* (*invoke)(CallbackPingCallback* _, SimpleCallback* callback);
	void (*free)(CallbackPingCallback* _);
};

/* =================== *\
        Functions
\* =================== */

bool consume();
bool consumeInt(int32_t arg);
bool consumeLong(int64_t arg);
bool consumeFloat(float arg);
bool consumeDouble(double arg);
bool consumeByte(int8_t arg);
bool consumeBoolean(bool arg);
bool consumeChar(uint16_t arg);
bool consumeString(const char* arg);
void get();
int32_t getInt();
int64_t getLong();
float getFloat();
double getDouble();
int8_t getByte();
bool getBoolean();
uint16_t getChar();
const char* getStringLiteral();
const char* getString();
int32_t pingInt(int32_t arg);
int64_t pingLong(int64_t arg);
float pingFloat(float arg);
double pingDouble(double arg);
int8_t pingByte(int8_t arg);
bool pingBoolean(bool arg);
uint16_t pingChar(uint16_t arg);
const char* pingString(const char* arg);
void simpleCallback(SimpleCallback* callback);
SimpleCallback* callbackReturn(SimpleCallback* callback);
bool callbackReturnString(StringCallback* callback);
bool callbackPingString(StringPingCallback* callback);
SimpleCallback* callbackPingCallback(CallbackPingCallback* callback, SimpleCallback* item);
bool jvmci1();
bool jvmci2(int32_t a1);
bool jvmci3(int32_t a1, int32_t a2);
bool jvmci4(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9);
bool jvmci5(int32_t a1, int64_t a2, int32_t a3, int64_t a4, int32_t a5, int64_t a6, int32_t a7, int32_t a8, int64_t a9);
bool jvmci6(float a1, float a2, float a3, float a4, float a5, float a6, float a7, float a8, float a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13);
bool jvmci7(float a1, double a2, float a3, double a4, float a5, double a6, float a7, float a8, double a9);
bool jvmci8(int32_t a1, double a2, float a3, int64_t a4);
bool jvmci9(int32_t a1, double a2, float a3, int64_t a4, int64_t a5, double a6, float a7, float a8, int32_t a9);
bool jvmci10(const char* a1, double a2, float a3, int64_t a4, int64_t a5, double a6, const char* a7, float a8, int32_t a9);
bool jvmci11(float a1, int32_t a2, float a3, int32_t a4, float a5, int32_t a6, float a7, int32_t a8, float a9, int32_t a10, float a11, int32_t a12, float a13, int32_t a14, float a15, int32_t a16, float a17);
int32_t jvmci12();
int64_t jvmci13();
float jvmci14();
double jvmci15();

#ifdef __cplusplus
}
#endif

#endif // KOTLIN_NATIVE_TEST_H