/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */
 
#ifndef KOTLIN_NATIVE_TEST_H
#define KOTLIN_NATIVE_TEST_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// ╔════════════════╗
// ║     stdlib     ║
// ╚════════════════╝

typedef int32_t  KInt;
typedef int64_t  KLong;
typedef float    KFloat;
typedef double   KDouble;
typedef int8_t   KByte;
typedef int16_t  KShort;
typedef bool     KBoolean;
typedef uint16_t KChar;

typedef struct KString {
    const char* data;
    KInt length;
} KString;

inline KString makeKString(const char* data, const KInt length) {
    return (KString) { data, length };
}

#define KArrayDef(Name, Type)	                                \
typedef struct Name {			                                \
    const Type elements;				                        \
    KInt size;				                                    \
} Name;                                                         \
                                                                \
inline Name make##Name(const Type elements, const KInt size) {  \
    return (Name){ elements, size };                            \
}
KArrayDef(KCharArray,	 KChar*)
KArrayDef(KBooleanArray, KBoolean*)
KArrayDef(KByteArray,	 KByte*)
KArrayDef(KShortArray,	 KShort*)
KArrayDef(KIntArray,	 KInt*)
KArrayDef(KLongArray,	 KLong*)
KArrayDef(KFloatArray,	 KFloat*)
KArrayDef(KDoubleArray,  KDouble*)
KArrayDef(KObjectArray,  void*)
#undef KArrayDef

#define KCallbackDef(Name, Type, ...)		\
struct Name {								\
    void *m;								\
    Type (*invoke)(Name* _, ##__VA_ARGS__);	\
    void (*free)(Name* _);					\
};

// ╔═══════════════════╗
// ║     Type defs     ║
// ╚═══════════════════╝

typedef struct SimpleCallback SimpleCallback;
typedef struct StringCallback StringCallback;
typedef struct StringPingCallback StringPingCallback;
typedef struct CallbackPingCallback CallbackPingCallback;

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

KBoolean consume();
KBoolean consumeInt(KInt arg);
KBoolean consumeLong(KLong arg);
KBoolean consumeFloat(KFloat arg);
KBoolean consumeDouble(KDouble arg);
KBoolean consumeByte(KByte arg);
KBoolean consumeBoolean(KBoolean arg);
KBoolean consumeChar(KChar arg);
KBoolean consumeString(KString arg);
void get();
KInt getInt();
KLong getLong();
KFloat getFloat();
KDouble getDouble();
KByte getByte();
KBoolean getBoolean();
KChar getChar();
KString getStringLiteral();
KString getString();
KInt pingInt(KInt arg);
KLong pingLong(KLong arg);
KFloat pingFloat(KFloat arg);
KDouble pingDouble(KDouble arg);
KByte pingByte(KByte arg);
KBoolean pingBoolean(KBoolean arg);
KChar pingChar(KChar arg);
KString pingString(KString arg);
void simpleCallback(SimpleCallback* callback);
SimpleCallback* callbackReturn(SimpleCallback* callback);
KBoolean callbackReturnString(StringCallback* callback);
KBoolean callbackPingString(StringPingCallback* callback);
SimpleCallback* callbackPingCallback(CallbackPingCallback* callback, SimpleCallback* item);
KBoolean passArray(KIntArray arg);
KIntArray returnArray();
KIntArray pingArray(KIntArray arg);
KBoolean jvmci1();
KBoolean jvmci2(KInt a1);
KBoolean jvmci3(KInt a1, KInt a2);
KBoolean jvmci4(KInt a1, KInt a2, KInt a3, KInt a4, KInt a5, KInt a6, KInt a7, KInt a8, KInt a9);
KBoolean jvmci5(KInt a1, KLong a2, KInt a3, KLong a4, KInt a5, KLong a6, KInt a7, KInt a8, KLong a9);
KBoolean jvmci6(KFloat a1, KFloat a2, KFloat a3, KFloat a4, KFloat a5, KFloat a6, KFloat a7, KFloat a8, KFloat a9, KInt a10, KInt a11, KInt a12, KInt a13);
KBoolean jvmci7(KFloat a1, KDouble a2, KFloat a3, KDouble a4, KFloat a5, KDouble a6, KFloat a7, KFloat a8, KDouble a9);
KBoolean jvmci8(KInt a1, KDouble a2, KFloat a3, KLong a4);
KBoolean jvmci9(KInt a1, KDouble a2, KFloat a3, KLong a4, KLong a5, KDouble a6, KFloat a7, KFloat a8, KInt a9);
KBoolean jvmci10(KString a1, KDouble a2, KFloat a3, KLong a4, KLong a5, KDouble a6, KString a7, KFloat a8, KInt a9);
KBoolean jvmci11(KFloat a1, KInt a2, KFloat a3, KInt a4, KFloat a5, KInt a6, KFloat a7, KInt a8, KFloat a9, KInt a10, KFloat a11, KInt a12, KFloat a13, KInt a14, KFloat a15, KInt a16, KFloat a17);
KInt jvmci12();
KLong jvmci13();
KFloat jvmci14();
KDouble jvmci15();
KBoolean jvmciArray(KIntArray array);
KBoolean jvmciSomeArrays(KIntArray array1, KFloatArray array2, KDoubleArray array3);

// ╔═══════════════════╗
// ║     Callbacks     ║
// ╚═══════════════════╝
// ┌───────┬─────────────────────┬────────────────┬─────────────────────────┐
// │  ...  │ Name                │ Type           │ Args                    │
// └───────┴─────────────────────┴────────────────┴─────────────────────────┘
KCallbackDef(SimpleCallback,       void,            KInt status             )
KCallbackDef(StringCallback,       KString                                  )
KCallbackDef(StringPingCallback,   KString,         KString text            )
KCallbackDef(CallbackPingCallback, SimpleCallback*, SimpleCallback* callback)
#undef KCallbackDef


#ifdef __cplusplus
}
#endif

#endif // KOTLIN_NATIVE_TEST_H