/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */
 
#ifndef KOTLIN_NATIVE_JVMONLYTEST_H
#define KOTLIN_NATIVE_JVMONLYTEST_H

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

#define ARG_LENGTH(...) ARG_LENGTH__(__VA_ARGS__)
#define ARG_LENGTH__(...) ARG_LENGTH_(,##__VA_ARGS__,                          \
    63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45,\
    44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,\
    25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6,\
    5, 4, 3, 2, 1, 0)
#define ARG_LENGTH_(_, _63, _62, _61, _60, _59, _58, _57, _56, _55, _54, _53,  \
    _52, _51, _50, _49, _48, _47, _46, _45, _44, _43, _42, _41, _40, _39, _38, \
    _37, _36, _35, _34, _33, _32, _31, _30, _29, _28, _27, _26, _25, _24, _23, \
    _22, _21, _20, _19, _18, _17, _16, _15, _14, _13, _12, _11, _10, _9, _8,   \
    _7, _6, _5, _4, _3, _2, _1, Count, ...) Count

// ╔═══════════════╗
// ║     Types     ║
// ╚═══════════════╝

typedef int32_t  KInt;
typedef uint32_t KUInt;
typedef int64_t  KLong;
typedef uint64_t KULong;
typedef float    KFloat;
typedef double   KDouble;
typedef int8_t   KByte;
typedef uint8_t  KUByte;
typedef int16_t  KShort;
typedef uint16_t KUShort;
typedef bool     KBoolean;
typedef uint16_t KChar;

typedef struct KString {
    const char* _Nonnull data;
    size_t size;
    KInt length;
    char __flags;
} KString;

KString* _Nonnull KString_new(const char* _Nonnull data, KInt length, size_t size, bool is_data_owner);
KString* _Nullable KString_clone(const KString* _Nullable self);
void KString_free(KString* _Nullable self);

typedef struct KCharArray {
    const KChar* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
} KCharArray;

KCharArray* _Nonnull KCharArray_new(const KChar* _Nonnull elements, KInt length, bool is_data_owner);
KCharArray* _Nonnull KCharArray_of_n(int n, ...);
KCharArray* _Nullable KCharArray_clone(const KCharArray* _Nullable self);
void KCharArray_free(KCharArray* _Nullable self);
#define KCharArray_of(...) KCharArray_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)


typedef struct KBooleanArray {
    const KBoolean* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
} KBooleanArray;

KBooleanArray* _Nonnull KBooleanArray_new(const KBoolean* _Nonnull elements, KInt length, bool is_data_owner);
KBooleanArray* _Nonnull KBooleanArray_of_n(int n, ...);
KBooleanArray* _Nullable KBooleanArray_clone(const KBooleanArray* _Nullable self);
void KBooleanArray_free(KBooleanArray* _Nullable self);
#define KBooleanArray_of(...) KBooleanArray_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)


typedef struct KByteArray {
    const KByte* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
} KByteArray;

KByteArray* _Nonnull KByteArray_new(const KByte* _Nonnull elements, KInt length, bool is_data_owner);
KByteArray* _Nonnull KByteArray_of_n(int n, ...);
KByteArray* _Nullable KByteArray_clone(const KByteArray* _Nullable self);
void KByteArray_free(KByteArray* _Nullable self);
#define KByteArray_of(...) KByteArray_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)


typedef struct KUByteArray {
    const KUByte* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
} KUByteArray;

KUByteArray* _Nonnull KUByteArray_new(const KUByte* _Nonnull elements, KInt length, bool is_data_owner);
KUByteArray* _Nonnull KUByteArray_of_n(int n, ...);
KUByteArray* _Nullable KUByteArray_clone(const KUByteArray* _Nullable self);
void KUByteArray_free(KUByteArray* _Nullable self);
#define KUByteArray_of(...) KUByteArray_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)


typedef struct KShortArray {
    const KShort* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
} KShortArray;

KShortArray* _Nonnull KShortArray_new(const KShort* _Nonnull elements, KInt length, bool is_data_owner);
KShortArray* _Nonnull KShortArray_of_n(int n, ...);
KShortArray* _Nullable KShortArray_clone(const KShortArray* _Nullable self);
void KShortArray_free(KShortArray* _Nullable self);
#define KShortArray_of(...) KShortArray_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)


typedef struct KUShortArray {
    const KUShort* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
} KUShortArray;

KUShortArray* _Nonnull KUShortArray_new(const KUShort* _Nonnull elements, KInt length, bool is_data_owner);
KUShortArray* _Nonnull KUShortArray_of_n(int n, ...);
KUShortArray* _Nullable KUShortArray_clone(const KUShortArray* _Nullable self);
void KUShortArray_free(KUShortArray* _Nullable self);
#define KUShortArray_of(...) KUShortArray_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)


typedef struct KIntArray {
    const KInt* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
} KIntArray;

KIntArray* _Nonnull KIntArray_new(const KInt* _Nonnull elements, KInt length, bool is_data_owner);
KIntArray* _Nonnull KIntArray_of_n(int n, ...);
KIntArray* _Nullable KIntArray_clone(const KIntArray* _Nullable self);
void KIntArray_free(KIntArray* _Nullable self);
#define KIntArray_of(...) KIntArray_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)


typedef struct KUIntArray {
    const KUInt* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
} KUIntArray;

KUIntArray* _Nonnull KUIntArray_new(const KUInt* _Nonnull elements, KInt length, bool is_data_owner);
KUIntArray* _Nonnull KUIntArray_of_n(int n, ...);
KUIntArray* _Nullable KUIntArray_clone(const KUIntArray* _Nullable self);
void KUIntArray_free(KUIntArray* _Nullable self);
#define KUIntArray_of(...) KUIntArray_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)


typedef struct KLongArray {
    const KLong* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
} KLongArray;

KLongArray* _Nonnull KLongArray_new(const KLong* _Nonnull elements, KInt length, bool is_data_owner);
KLongArray* _Nonnull KLongArray_of_n(int n, ...);
KLongArray* _Nullable KLongArray_clone(const KLongArray* _Nullable self);
void KLongArray_free(KLongArray* _Nullable self);
#define KLongArray_of(...) KLongArray_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)


typedef struct KULongArray {
    const KULong* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
} KULongArray;

KULongArray* _Nonnull KULongArray_new(const KULong* _Nonnull elements, KInt length, bool is_data_owner);
KULongArray* _Nonnull KULongArray_of_n(int n, ...);
KULongArray* _Nullable KULongArray_clone(const KULongArray* _Nullable self);
void KULongArray_free(KULongArray* _Nullable self);
#define KULongArray_of(...) KULongArray_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)


typedef struct KFloatArray {
    const KFloat* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
} KFloatArray;

KFloatArray* _Nonnull KFloatArray_new(const KFloat* _Nonnull elements, KInt length, bool is_data_owner);
KFloatArray* _Nonnull KFloatArray_of_n(int n, ...);
KFloatArray* _Nullable KFloatArray_clone(const KFloatArray* _Nullable self);
void KFloatArray_free(KFloatArray* _Nullable self);
#define KFloatArray_of(...) KFloatArray_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)


typedef struct KDoubleArray {
    const KDouble* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
} KDoubleArray;

KDoubleArray* _Nonnull KDoubleArray_new(const KDouble* _Nonnull elements, KInt length, bool is_data_owner);
KDoubleArray* _Nonnull KDoubleArray_of_n(int n, ...);
KDoubleArray* _Nullable KDoubleArray_clone(const KDoubleArray* _Nullable self);
void KDoubleArray_free(KDoubleArray* _Nullable self);
#define KDoubleArray_of(...) KDoubleArray_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)


typedef struct KArray {
    const void* _Nullable* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
} KArray;

KArray* _Nonnull KArray_new(const void* _Nullable* _Nonnull elements, KInt length, bool is_data_owner);
KArray* _Nonnull KArray_of_n(int n, ...);
KArray* _Nullable KArray_clone(const KArray* _Nullable self, void* _Nullable (* _Nullable clone_op)(void* _Nullable));
void KArray_free(const KArray* _Nullable self, void (* _Nonnull free_op)(void* _Nonnull));
#define KArray_of(...) KArray_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)


#define KCallbackDef(Name, Type, ...)                                       \
struct Name {                                                               \
    char __flags;                                                           \
    Type (* _Nonnull invoke)(Name* _Nonnull self, ##__VA_ARGS__);           \
    Name* _Nonnull (* _Nonnull clone)(Name* _Nonnull self);                 \
    KBoolean (* _Nonnull equals)(Name* _Nonnull self, Name* _Nullable obj); \
    KInt (* _Nonnull hash_code)(Name* _Nonnull self);                       \
    void (* _Nonnull free)(Name* _Nullable self);                           \
};

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

void hello_world();

#endif // KOTLIN_NATIVE_JVMONLYTEST_H