/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */

#pragma once

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

// ╔══════════════════════════╗
// ║     Type definitions     ║
// ╚══════════════════════════╝

typedef struct MyDictionary MyDictionary;

// ╔═══════════════╗
// ║     Types     ║
// ╚═══════════════╝

typedef struct KString KString;
struct KString {
    KString* _Nullable (* _Nullable clone)(const KString* _Nullable);
    void (* _Nullable free)(KString* _Nullable);
    const char* _Nonnull data;
    int32_t size;
};

typedef struct _KStringNewArgs {
    const int32_t size;
    bool make_copy;
} _KStringNewArgs;

#define kstring_new(data, ...) \
    _kstring_new(data, (_KStringNewArgs){ .size = -1, .make_copy = true, __VA_ARGS__ })

KString* _Nonnull _kstring_new(const char* _Nonnull data, _KStringNewArgs args);
KString* _Nonnull kstring_clone(const KString* _Nonnull self);
int32_t kstring_length(const KString* _Nonnull self);
void kstring_free(KString* _Nonnull self);

// ╔═════════════════╗
// ║     Structs     ║
// ╚═════════════════╝

struct MyDictionary {	
	MyDictionary* _Nullable (* _Nullable clone)(const MyDictionary* _Nullable);
	void (* _Nullable free)(MyDictionary* _Nullable);
	int32_t field;
	KString* _Nonnull a;
};

MyDictionary* _Nonnull MyDictionary_new(int32_t field, KString* _Nonnull a);
MyDictionary* _Nullable MyDictionary_clone(const MyDictionary* _Nullable self);
void MyDictionary_free(MyDictionary* _Nullable self);

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

void hello_world(void);
