/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */

#pragma once

#include <memory>
#include <string>

// ╔═══════════════╗
// ║     Types     ║
// ╚═══════════════╝

template <typename T> class KArray {
    T* _Nonnull elements;
    int32_t length;
    int32_t capacity;
public:
    explicit KArray(int32_t capacity);
    explicit KArray(T* _Nonnull elements, int32_t length, bool copy = true);
    explicit KArray(std::initializer_list<T> elements);
    KArray(const KArray& other);
    KArray(KArray&& other) noexcept;
    KArray& operator=(KArray&& other) noexcept;
    ~KArray();
    explicit operator const T* _Nonnull () const;
    const T& operator[](size_t index) const;
    void push(T&& element);
    T& get(int32_t index);
    const T* _Nonnull get_elements();
    int32_t get_length() const;
};

// ╔═══════════════╗
// ║     Enums     ║
// ╚═══════════════╝

enum MyEnum {
	A
};

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

void stub1(const KArray<int64_t>& e);
void stub2(const KArray<MyEnum>& e);

#include "api.tpp"