/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */
 
#pragma once

// ╔═══════════════╗
// ║     Array     ║
// ╚═══════════════╝

template<typename T> 
KArray<T>* _Nonnull karray_wrap(KArray<T> value) {
    return new KArray<T>(std::move(value));
}

template<typename T>
KArray<T> karray_unwrap(KArray<T>* _Nonnull arg) {
    KArray<T> result = std::move(*arg);
    delete arg;
    return result;
}

template<typename T>
KArray<T>::KArray(const int32_t capacity): elements(nullptr), length(0), capacity(capacity) {
    if (capacity > 0) {
        elements = static_cast<T*>(malloc(sizeof(T) * capacity));
    }
}

template<typename T>
KArray<T>::KArray(T* _Nonnull elements, const int32_t length, const bool copy): length(length), capacity(length) {
    if (copy) {
        this->elements = static_cast<T*>(malloc(sizeof(T) * length));
        if constexpr (std::is_trivially_copyable_v<T>) {
            std::memcpy(this->elements, elements, sizeof(T) * length);
        } else {
            for (int32_t i = 0; i < length; ++i)
                new (&this->elements[i]) T(elements[i]);
        }
    } else this->elements = elements;
}

template<typename T>
KArray<T>::KArray(std::initializer_list<T> elements): length(elements.size()), capacity(elements.size()) {
    this->elements = static_cast<T*>(malloc(sizeof(T) * elements.size()));
    if constexpr (std::is_trivially_copyable_v<T>) {
        std::memcpy(this->elements, elements.begin(), sizeof(T) * elements.size());
    } else {
        int32_t i = 0;
        for (const auto& e : elements)
            new (&this->elements[i++]) T(e);
    }
}

template<typename T>
KArray<T>::KArray(const KArray &other): length(other.length), capacity(other.capacity) {
    elements = static_cast<T*>(malloc(sizeof(T) * capacity));
    if constexpr (std::is_trivially_copyable_v<T>) {
        std::memcpy(elements, other.elements, sizeof(T) * length);
    } else {
        for (int32_t i = 0; i < length; ++i)
            new (&elements[i]) T(other.elements[i]);
    }
}

template<typename T>
KArray<T>::KArray(KArray&& other) noexcept
    : elements(other.elements), length(other.length), capacity(other.capacity) {
    other.elements = nullptr;
    other.length = 0;
    other.capacity = 0;
}

template<typename T>
KArray<T>& KArray<T>::operator=(KArray&& other) noexcept {
    if (this != &other) {
        if constexpr (!std::is_trivially_destructible_v<T>) {
            for (size_t i = 0; i < length; i++)
                elements[i].~T();
        }
        free(elements);
        elements = other.elements;
        length = other.length;
        capacity = other.capacity;
        other.elements = nullptr;
        other.length = 0;
        other.capacity = 0;
    }
    return *this;
}

template<typename T>
KArray<T>::~KArray() {
    if constexpr (!std::is_trivially_destructible_v<T>) {
        for (size_t i = 0; i < length; i++)
            elements[i].~T();
    }
    free(elements);
}

template<typename T>
KArray<T>::operator const T* _Nonnull () const {
    return elements;
}

template<typename T>
const T& KArray<T>::operator[](size_t index) const {
    return elements[index];
}

template<typename T>
void KArray<T>::push(T&& element) {
    if (length >= capacity) {
        capacity = capacity == 0 ? 4 : capacity * 2;
        if constexpr (std::is_trivially_copyable_v<T>) {
            elements = static_cast<T*>(realloc(elements, sizeof(T) * capacity));
        } else {
            T* new_elements = static_cast<T*>(malloc(sizeof(T) * capacity));
            for (int32_t i = 0; i < length; ++i)
                new (&new_elements[i]) T(std::move(elements[i]));
            if constexpr (!std::is_trivially_destructible_v<T>) {
                for (int32_t i = 0; i < length; i++)
                    elements[i].~T();
            }
            free(elements);
            elements = new_elements;
        }
    }
    new (&elements[length]) T(std::move(element));
    length++;
}

template<typename T>
T &KArray<T>::get(int32_t index) {
    return elements[index];
}

template<typename T>
int32_t KArray<T>::get_length() const {
    return length;
}

template<typename T>
const T* _Nonnull KArray<T>::get_elements() {
    return elements;
}
