kotlin.code.style=official

kotlin.mpp.enableCInteropCommonization=true
kotlin.native.enableKlibsCrossCompilation=false
kotlin.native.ignoreDisabledTargets=true
kotlin.js.yarn = false

# gradle
org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true