package com.huskerdev.nativekt.printers

import com.huskerdev.nativekt.utils.globalOperators
import com.huskerdev.nativekt.utils.printLabel
import com.huskerdev.nativekt.utils.toCDefType
import com.huskerdev.webidl.resolver.IdlResolver
import com.huskerdev.webidl.resolver.ResolvedIdlCallbackFunction
import com.huskerdev.webidl.resolver.ResolvedIdlOperation
import java.io.File
import kotlin.math.max

class HeaderPrinter(
    idl: IdlResolver,
    target: File,
    val guardName: String? = null
) {
    private val defName = "KOTLIN_NATIVE_${guardName}_H"

    init {
        target.parentFile.mkdirs()

        val builder = StringBuilder()
        printHeader(builder)

        printLabel(builder, "stdlib")
        printStdLib(builder)

        if(idl.callbacks.isNotEmpty()) {
            printLabel(builder, "Type defs")
            idl.callbacks.values.forEach { printCallbackTypedef(builder, it) }
            builder.append("\n")
        }

        printLabel(builder, "Functions")
        idl.globalOperators().forEach { printFunction(builder, it) }

        if(idl.callbacks.isNotEmpty()) {
            builder.append("\n")
            printLabel(builder, "Callbacks")
            printCallbacks(builder, idl.callbacks.values)
        }

        printFooter(builder)

        target.writeText(builder.toString().replace("\n", System.lineSeparator()))
    }

    private fun printFunction(builder: StringBuilder, function: ResolvedIdlOperation) = builder.apply {
        append("\n")
        append(function.type.toCDefType())
        append(" ")
        append(function.name)
        append("(")

        function.args.joinTo(builder) {
            "${it.type.toCDefType()} ${it.name}"
        }

        append(");")
    }

    private fun printCallbackTypedef(builder: StringBuilder, callback: ResolvedIdlCallbackFunction) = builder.apply {
        append("\ntypedef struct ")
        append(callback.name)
        append(" ")
        append(callback.name)
        append(";")
    }

    private fun printCallbacks(builder: StringBuilder, callbacks: Collection<ResolvedIdlCallbackFunction>) = builder.apply {
        val column1 = "Name"
        val column2 = "Type"
        val column3 = "Args"

        val names = arrayListOf<String>()
        val types = arrayListOf<String>()
        val args = arrayListOf<String>()

        callbacks.forEach { callback ->
            names += callback.name + ","
            types += callback.type.toCDefType() + if(callback.args.isNotEmpty()) "," else ""
            args += callback.args.joinToString { "${it.type.toCDefType()} ${it.name}" }
        }

        val width1 = max(column1.length, names.maxOf { it.length })
        val width2 = max(column2.length, types.maxOf { it.length })
        val width3 = max(column3.length, args.maxOf { it.length })

        // ┌───────┬─────────────────────┬────────────────┬─────────────────────────┐
        // │       │ Name                │ Type           │ Args                    │
        // └───────┴─────────────────────┴────────────────┴─────────────────────────┘
        // table
        append("// ┌───────┬")
        append("─".repeat(width1)).append("┬")
        append("─".repeat(width2)).append("┬")
        append("─".repeat(width3+1)).append("┐\n")
        append("// │  ...  │ ")
        append(column1).append(" ".repeat(width1 - column1.length - 1)).append("│ ")
        append(column2).append(" ".repeat(width2 - column2.length - 1)).append("│ ")
        append(column3).append(" ".repeat(width3 - column3.length)).append("│\n")
        append("// └───────┴")
        append("─".repeat(width1)).append("┴")
        append("─".repeat(width2)).append("┴")
        append("─".repeat(width3+1)).append("┘\n")

        for(i in callbacks.indices) {
            append("KCallbackDef(")

            // name
            append(names[i])
            append(" ".repeat(width1 - names[i].length))

            // type
            append(" ")
            append(types[i])
            append(" ".repeat(width2 - types[i].length ))

            // args
            if(args.isNotEmpty()) {
                append(" ")
                append(args[i])
                append(" ".repeat(width3 - args[i].length))
            }
            append(")\n")
        }
        append("#undef KCallbackDef\n")
    }

    private fun printHeader(builder: StringBuilder){
        builder.append("""
            /*
             * This file was automatically generated by Gradle.
             *
             * DO NOT EDIT THIS FILE MANUALLY.
             * Any changes made to this file will be overwritten the next time
             * the project is built.
             */
             

        """.trimIndent())

        if(guardName != null) {
            builder.append("#ifndef $defName\n")
            builder.append("#define $defName\n")
        }

        builder.append("""
            
            #include <stdint.h>
            #include <stdbool.h>
            
            #ifdef __cplusplus
            extern "C" {
            #endif
            
        """.trimIndent())
    }

    private fun printFooter(builder: StringBuilder){
        builder.append("""
            
            
            #ifdef __cplusplus
            }
            #endif
        """.trimIndent())

        if(guardName != null)
            builder.append("\n\n#endif // $defName")
    }

    private fun printStdLib(builder: StringBuilder){
        builder.append("""

            typedef int32_t  KInt;
            typedef int64_t  KLong;
            typedef float    KFloat;
            typedef double   KDouble;
            typedef int8_t   KByte;
            typedef int16_t  KShort;
            typedef bool     KBoolean;
            typedef uint16_t KChar;

            typedef struct KString {
                const char* data;
                KInt length;
            } KString;
            
            inline KString makeKString(const char* data, const KInt length) {
                return (KString) { data, length };
            }

            #define KArrayDef(Name, Type)	                                \
            typedef struct Name {			                                \
                const Type elements;				                        \
                const KInt size;				                            \
            } Name;                                                         \
                                                                            \
            inline Name make##Name(const Type elements, const KInt size) {  \
                return (Name){ elements, size };                            \
            }
            KArrayDef(KCharArray,	 KChar*)
            KArrayDef(KBooleanArray, KBoolean*)
            KArrayDef(KByteArray,	 KByte*)
            KArrayDef(KShortArray,	 KShort*)
            KArrayDef(KIntArray,	 KInt*)
            KArrayDef(KLongArray,	 KLong*)
            KArrayDef(KFloatArray,	 KFloat*)
            KArrayDef(KDoubleArray,  KDouble*)
            KArrayDef(KObjectArray,  void*)
            #undef KArrayDef

            #define KCallbackDef(Name, Type, ...)		\
            struct Name {								\
                void *m;								\
                Type (*invoke)(Name* _, ##__VA_ARGS__);	\
                void (*free)(Name* _);					\
            };
            
        """.trimIndent())
    }
}