/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */

#pragma once

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

// ╔══════════════════════════╗
// ║     Type definitions     ║
// ╚══════════════════════════╝

#ifndef NATIVEKT_EmptyInterface
#define NATIVEKT_EmptyInterface void
#endif

#ifndef NATIVEKT_MyInterface
#define NATIVEKT_MyInterface void
#endif


// ╔═══════════════╗
// ║     Types     ║
// ╚═══════════════╝

#define RC(Name, Type, Lower)                                    \
typedef struct RC_##Name RC_##Name;                              \
struct RC_##Name {                                               \
    RC_##Name* _Nonnull (* _Nonnull clone)(RC_##Name* _Nonnull); \
    void (* _Nonnull free)(RC_##Name* _Nonnull);                 \
    void (* _Nonnull free_pointed)(Type* _Nonnull);              \
    Type* _Nonnull pointed;                                      \
    int32_t refs;                                                \
};                                                               \
RC_##Name* _Nullable rc_##Lower##_new(Type* _Nullable ptr);

RC(EmptyInterface, NATIVEKT_EmptyInterface, emptyinterface)
RC(MyInterface, NATIVEKT_MyInterface, myinterface)
#undef RC

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

void stub1(RC_EmptyInterface* _Nonnull e);
void stub2(RC_MyInterface* _Nonnull e);
void _interface_emptyinterface_free(void* _Nonnull _self);
void _interface_myinterface_fn_func(void* _Nonnull _self);
void _interface_myinterface_free(void* _Nonnull _self);
