package com.huskerdev.nativekt.printers.c

import com.huskerdev.nativekt.NativeModuleContext
import com.huskerdev.nativekt.plugin.Language
import com.huskerdev.nativekt.utils.*
import com.huskerdev.webidl.resolver.ResolvedIdlType
import java.io.File

class CApiHeaderPrinter(
    val context: NativeModuleContext,
    target: File,
    val language: Language? = context.language,
    val isInternal: Boolean = false
) {
    init {
        target.parentFile.mkdirs()
        target.writeText(buildString {
            printHeader()
            printTypeDefs()
            printStdLib()
            printEnums()
            printDictionaries()
            printCallbacks()
            printFunctions()
        }.replace("\n", System.lineSeparator()))
    }

    private fun StringBuilder.printHeader(){
        appendLine("""
            /*
             * This file was automatically generated by Gradle.
             *
             * DO NOT EDIT THIS FILE MANUALLY.
             * Any changes made to this file will be overwritten the next time
             * the project is built.
             */
            
            #pragma once
            
            #include <stdlib.h>
            #include <stdint.h>
            #include <stdbool.h>
        """.trimIndent())

        if(isInternal) appendLine("""
            #include <string.h>
            #include <stdarg.h>
        """.trimIndent())

        if(language == Language.C && (context.hasObjectArrays || context.hasPrimitiveArray)) {
            appendLine("""
                
                #define ARG_LENGTH(...) ARG_LENGTH__(__VA_ARGS__)
                #define ARG_LENGTH__(...) ARG_LENGTH_(,##__VA_ARGS__,                          \
                    63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45,\
                    44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,\
                    25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6,\
                    5, 4, 3, 2, 1, 0)
                #define ARG_LENGTH_(_, _63, _62, _61, _60, _59, _58, _57, _56, _55, _54, _53,  \
                    _52, _51, _50, _49, _48, _47, _46, _45, _44, _43, _42, _41, _40, _39, _38, \
                    _37, _36, _35, _34, _33, _32, _31, _30, _29, _28, _27, _26, _25, _24, _23, \
                    _22, _21, _20, _19, _18, _17, _16, _15, _14, _13, _12, _11, _10, _9, _8,   \
                    _7, _6, _5, _4, _3, _2, _1, Count, ...) Count
            """.trimIndent())
        }
        if(isInternal) {
            appendLine("""
                
                #ifndef LIB_EXPORT
                    #if defined(_WIN32) || defined(__CYGWIN__)
                        #define LIB_EXPORT __declspec(dllexport)
                    #else
                        #define LIB_EXPORT __attribute__((visibility("default")))
                    #endif
                #endif
                
                LIB_EXPORT void ${context.mangle("init")}(void);
            """.trimIndent())
            if(context.needsAllocFunctions) appendLine("""
                LIB_EXPORT void* _Nullable ${context.mangle("alloc")}(size_t size);
                LIB_EXPORT void ${context.mangle("dealloc")}(void* _Nullable ptr, size_t size);
            """.trimIndent())
        }
    }

    private fun StringBuilder.printTypeDefs() {
        if(language != Language.C || (
            !context.hasCallbacks &&
            !context.hasDictionaries &&
            !context.hasInterfaces
        )) return

        printLabel("Type definitions")

        context.usedInterfaces.forEach {
            append("""
                
                #ifndef NATIVEKT_${it.cname}
                #define NATIVEKT_${it.cname} void
                #endif
                
            """.trimIndent())
        }

        buildList {
            addAll(context.usedDictionaries)
            addAll(context.usedCallbacks)
        }.joinTo(this, separator = "") {
            "\ntypedef struct ${it.cname} ${it.cname};"
        }
        append("\n")
    }

    private fun StringBuilder.printStdLib() {
        if(!context.hasCallbacks &&
            !context.hasInterfaces &&
            !context.hasString &&
            !context.hasPrimitiveArray &&
            !context.hasObjectArrays
        ) return

        printLabel("Types")

        if(language == Language.C && (context.hasCallbacks || context.hasInterfaces)) {
            append("""
                
                #define RC(Name, Type, Lower)                                    \
                typedef struct RC_##Name RC_##Name;                              \
                struct RC_##Name {                                               \
                    RC_##Name* _Nonnull (* _Nonnull clone)(RC_##Name* _Nonnull); \
                    void (* _Nonnull free)(RC_##Name* _Nonnull);                 \
                    void (* _Nonnull free_pointed)(Type* _Nonnull);              \
                    Type* _Nonnull pointed;                                      \
                    int32_t refs;                                                \
                };                                                               \
                RC_##Name* _Nullable rc_##Lower##_new(Type* _Nullable ptr);
                
                
            """.trimIndent())

            buildList {
                context.usedCallbacks.mapTo(this) { Triple(it.cname, it.cname, it.name.lowercase()) }
                context.usedInterfaces.mapTo(this) { Triple(it.cname, "NATIVEKT_${it.cname}", it.name.lowercase()) }
            }.forEach {
                append("RC(${it.first}, ${it.second}, ${it.third})\n")
            }
            append("#undef RC\n")
        }

        // String
        if(context.hasString) {
            if (language == Language.C) {
                append("""
                    
                    typedef struct KString KString;
                    struct KString {
                        KString* _Nullable (* _Nullable clone)(const KString* _Nullable);
                        void (* _Nullable free)(KString* _Nullable);
                        const char* _Nonnull data;
                        int32_t length;
                        int32_t size;
                    };
                    
                    typedef struct _KStringNewArgs {
                        const int32_t length;
                        const int32_t size;
                        bool make_copy;
                    } _KStringNewArgs;
                    
                    #define kstring_new(data, ...) \
                        _kstring_new(data, (_KStringNewArgs){ .length = -1, .size = -1, .make_copy = true, __VA_ARGS__ })
                    
                    KString* _Nonnull _kstring_new(const char* _Nonnull data, _KStringNewArgs args);
                    KString* _Nonnull kstring_clone(const KString* _Nonnull self);
                    void kstring_free(KString* _Nonnull self);
                    
                """.trimIndent())
            }
            if (isInternal) {
                val typeName = if (language == Language.C) "KString" else "void"
                if (context.hasStringToNativeCast) append("""
                    
                    LIB_EXPORT $typeName* _Nonnull ${context.mangle("string_new")}(const char* _Nonnull data, int32_t length, int32_t size, bool make_copy);
                """.trimIndent())
                if (context.hasStringToKotlinCast) append("""
                    
                    LIB_EXPORT const char* _Nonnull ${context.mangle("string_data")}(const $typeName* _Nonnull self);
                    LIB_EXPORT size_t ${context.mangle("string_size")}(const $typeName* _Nonnull self);
                    LIB_EXPORT int32_t ${context.mangle("string_length")}(const $typeName* _Nonnull self);
                    LIB_EXPORT void ${context.mangle("string_free")}($typeName* _Nonnull self);
                """.trimIndent())
                append("\n")
            }
        }

        // Primitive arrays
        if(context.hasPrimitiveArray) {
            if (language == Language.C) {
                listOf(
                    Triple("Char" to "uint16_t", context.hasCharArrayToNativeCast, context.hasCharArrayToKotlinCast),
                    Triple("Boolean" to "bool", context.hasBooleanArrayToNativeCast, context.hasBooleanArrayToKotlinCast),
                    Triple("Byte" to "int8_t",
                        context.hasByteArrayToNativeCast || (isInternal && context.hasUByteArrayToNativeCast),
                        context.hasByteArrayToKotlinCast || (isInternal && context.hasUByteArrayToKotlinCast)),
                    Triple("UByte" to "uint8_t",
                        context.hasUByteArrayToNativeCast,
                        context.hasUByteArrayToKotlinCast),
                    Triple("Short" to "int16_t",
                        context.hasShortArrayToNativeCast || (isInternal && context.hasUShortArrayToNativeCast),
                        context.hasShortArrayToKotlinCast || (isInternal && context.hasUShortArrayToKotlinCast)),
                    Triple("UShort" to "uint16_t",
                        context.hasUShortArrayToNativeCast,
                        context.hasUShortArrayToKotlinCast),
                    Triple("Int" to "int32_t",
                        context.hasIntArrayToNativeCast || context.hasEnumArrayToNativeCast || (isInternal && context.hasUIntArrayToNativeCast),
                        context.hasIntArrayToKotlinCast || context.hasEnumArrayToKotlinCast || (isInternal && context.hasUIntArrayToKotlinCast)
                    ),
                    Triple("UInt" to "uint32_t",
                        context.hasUIntArrayToNativeCast,
                        context.hasUIntArrayToKotlinCast),
                    Triple("Long" to "int64_t",
                        context.hasLongArrayToNativeCast || (isInternal && context.hasULongArrayToNativeCast),
                        context.hasLongArrayToKotlinCast || (isInternal && context.hasULongArrayToKotlinCast)),
                    Triple("ULong" to "uint64_t",
                        context.hasULongArrayToNativeCast,
                        context.hasULongArrayToKotlinCast),
                    Triple("Float" to "float", context.hasFloatArrayToNativeCast, context.hasFloatArrayToKotlinCast),
                    Triple("Double" to "double", context.hasDoubleArrayToNativeCast, context.hasDoubleArrayToKotlinCast)
                ).forEach { (names, hasToNativeCast, hasToKotlinCast) ->
                    if (!hasToNativeCast && !hasToKotlinCast)
                        return@forEach

                    val name = "K${names.first}Array"
                    val type = names.second
                    val funcName = name.snakeCase()

                    append("""
                        
                        typedef struct $name $name;
                        struct $name {
                            $name* _Nonnull (* _Nonnull clone)(const $name* _Nonnull);
                            void (* _Nonnull free)($name* _Nonnull);
                            const $type* _Nonnull elements;
                            int32_t length;
                        };
                        
                        $name* _Nonnull ${funcName}_new(const $type* _Nonnull elements, int32_t length, bool make_copy);
                        $name* _Nonnull ${funcName}_of_n(int n, ...);
                        #define ${funcName}_of(...) ${funcName}_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
                        $name* _Nullable ${funcName}_clone(const $name* _Nullable self);
                        void ${funcName}_free($name* _Nullable self);
                        
                    """.trimIndent())
                }
            }
            if(isInternal) {
                listOf(
                    Triple("Char" to "uint16_t", context.hasCharArrayToNativeCast, context.hasCharArrayToKotlinCast),
                    Triple("Boolean" to "bool", context.hasBooleanArrayToNativeCast, context.hasBooleanArrayToKotlinCast),
                    Triple("Byte" to "int8_t",
                        context.hasByteArrayToNativeCast || context.hasUByteArrayToNativeCast,
                        context.hasByteArrayToKotlinCast || context.hasUByteArrayToKotlinCast),
                    Triple("Short" to "int16_t",
                        context.hasShortArrayToNativeCast || context.hasUShortArrayToNativeCast,
                        context.hasShortArrayToKotlinCast || context.hasUShortArrayToKotlinCast),
                    Triple("Int" to "int32_t",
                        context.hasIntArrayToNativeCast || context.hasEnumArrayToNativeCast || context.hasUIntArrayToNativeCast,
                        context.hasIntArrayToKotlinCast || context.hasEnumArrayToKotlinCast || context.hasUIntArrayToKotlinCast
                    ),
                    Triple("Long" to "int64_t",
                        context.hasLongArrayToNativeCast || context.hasULongArrayToNativeCast,
                        context.hasLongArrayToKotlinCast || context.hasULongArrayToKotlinCast),
                    Triple("Float" to "float", context.hasFloatArrayToNativeCast, context.hasFloatArrayToKotlinCast),
                    Triple("Double" to "double", context.hasDoubleArrayToNativeCast, context.hasDoubleArrayToKotlinCast)
                ).forEach { (names, hasToNativeCast, hasToKotlinCast) ->
                    if(!hasToNativeCast && !hasToKotlinCast)
                        return@forEach

                    val name = "K${names.first}Array"
                    val type = names.second
                    val lowerName = name.lowercase().drop(1)
                    val typeName = if (language == Language.C) name else "void"

                    if (hasToNativeCast) append("""
                        
                        LIB_EXPORT $typeName* _Nonnull ${context.mangle("${lowerName}_new")}(const $type* _Nonnull elements, int32_t length, bool make_copy);
                    """.trimIndent())
                    if (hasToKotlinCast) append("""
                        
                        LIB_EXPORT const $type* _Nonnull ${context.mangle("${lowerName}_elements")}(const $typeName* _Nonnull self);
                        LIB_EXPORT int32_t ${context.mangle("${lowerName}_length")}(const $typeName* _Nonnull self);
                    """.trimIndent())
                    appendLine("""
                        
                        LIB_EXPORT void ${context.mangle("${lowerName}_free")}($typeName* _Nonnull self);
                        
                    """.trimIndent())
                }
            }
        }

        // Object array
        if(context.hasObjectArrays) {
            if (language == Language.C) {
                append("""
                    
                    typedef struct KArray KArray;
                    struct KArray {
                        KArray* _Nonnull (* _Nonnull clone)(const KArray* _Nonnull);
                        void (* _Nonnull free)(KArray* _Nonnull);
                        const void *_Nullable *_Nonnull elements;
                        int32_t length;
                        int32_t capacity;
                    };
                    
                    KArray* _Nonnull karray_with_capacity(int32_t capacity);
                    KArray* _Nonnull karray_new(const void* _Nullable * _Nonnull elements, int32_t length);
                    KArray* _Nonnull karray_of_n(int n, ...);
                    #define karray_of(...) karray_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
                    void karray_push(KArray* _Nullable self, const void* _Nullable element);
                    KArray* _Nullable karray_clone(const KArray* _Nullable self);
                    void karray_free(KArray* _Nullable self);
                    
                """.trimIndent())
            }
            if (isInternal) {
                val arrayType = if (language == Language.C) "KArray*" else "void*"
                buildList {
                    context.usedDictionaries.mapTo(this) {
                        Triple(it.cname to it.cname.lowercase(),
                            it in context.usedObjectArrayToNativeCast,
                            it in context.usedObjectArrayToKotlinCast)
                    }
                    context.usedInterfaces.mapTo(this) {
                        Triple("void" to it.cname.lowercase(),
                            it in context.usedObjectArrayToNativeCast,
                            it in context.usedObjectArrayToKotlinCast)
                    }
                    add(Triple("KString" to "string",
                        context.hasStringArrayToNativeCast,
                        context.hasStringArrayToKotlinCast
                    ))
                }.forEach { (names, hasToNativeCast, hasToKotlinCast) ->
                    val typeName = if (language == Language.C) names.first else "void"
                    val name = names.second

                    if (hasToNativeCast) append("""
                        
                        LIB_EXPORT $arrayType _Nonnull ${context.mangle("array_${name}_new")}(int32_t capacity, bool nullable_elements);
                    """.trimIndent())
                    if (hasToKotlinCast) append("""
                        
                        LIB_EXPORT int32_t ${context.mangle("array_${name}_length")}($arrayType _Nonnull self, bool nullable_elements);
                        LIB_EXPORT void ${context.mangle("array_${name}_push")}($arrayType _Nonnull self, void* _Nullable element, bool nullable_elements);
                        LIB_EXPORT $typeName* _Nullable ${context.mangle("array_${name}_get")}($arrayType _Nonnull self, int32_t index, bool nullable_elements);
                        LIB_EXPORT void ${context.mangle("array_${name}_free")}($arrayType _Nonnull self, bool nullable_elements);
                    """.trimIndent())
                    append("\n")
                }
            }
        }
    }

    private fun StringBuilder.printEnums() {
        if(!context.hasEnums || language != Language.C)
            return
        printLabel("Enums")

        context.usedEnums.forEach { enum ->
            append("\ntypedef enum {")
            enum.elements.joinTo(this, separator = ",") {
                "\n\t${enum.cname}_${it}"
            }
            append("\n} ${enum.cname};\n")
        }
    }

    private fun StringBuilder.printDictionaries() {
        if(!context.hasDictionaries)
            return
        printLabel("Structs")

        context.usedDictionaries.forEach { dictionary ->
            val name = dictionary.cname
            val fields = context.allFields[dictionary]!!
            val args = fields.map { field ->
                "${field.type.toLangType()} ${field.cname}"
            }

            if(language == Language.C) {
                append("\nstruct $name {")
                if (dictionary.implements != null)
                    append(" // : ").append(dictionary.implements!!.cname)
                append("""
                    
                    $name* _Nullable (* _Nullable clone)(const $name* _Nullable);
                    void (* _Nullable free)($name* _Nullable);
                """.replaceIndent("\t"))
                args.joinTo(this, separator = "") { "\n\t$it;" }
                append("\n};\n")

                // Methods
                append("""
                    
                    $name* _Nonnull ${name}_new(${args.joinToString()});
                    $name* _Nullable ${name}_clone(const $name* _Nullable self);
                    void ${name}_free($name* _Nullable self);
                    
                """.trimIndent())
            }
            if (isInternal) {
                val structTypeName = if(language == Language.C) name else "void"
                val args = fields.map { field ->
                    "${field.type.toLangType()} ${field.cname}"
                }
                if(dictionary in context.toNativeDeclarations) append("""
                    
                    LIB_EXPORT $structTypeName* _Nonnull ${dictionary.subCFunc(context, "new")}(${args.joinToString()});
                """.trimIndent())

                if(dictionary in context.toKotlinDeclarations) {
                    append("""
                        
                        LIB_EXPORT void ${dictionary.subCFunc(context, "free")}($structTypeName* _Nonnull self);
                    """.trimIndent())
                    fields.joinTo(this, separator = "") { field ->
                        val func = dictionary.subFieldCFunc(context, field)
                        val type = field.type.toLangType()
                        "\nLIB_EXPORT $type $func(const $structTypeName* _Nonnull self);"
                    }
                }
                append("\n")
            }
        }
    }

    private fun StringBuilder.printCallbacks(){
        if(!context.hasCallbacks)
            return
        printLabel("Callbacks")

        if(language == Language.C) {
            if(isInternal) appendLine("""
                
                #define KCallbackDef(Name, Lower, FUNC_NEW, FUNC_ID, FUNC_FREE, Type, ...)  \
                struct Name {                                                               \
                    size_t id;                                                              \
                    int32_t hash_code;                                                      \
                    Type (* _Nonnull invoke)(size_t id, ##__VA_ARGS__);                     \
                    bool (* _Nonnull equals)(size_t id, size_t other);                      \
                    void (* _Nonnull _free)(size_t id);                                     \
                };                                                                          \
                Type Lower##_invoke(RC_##Name* _Nonnull, ##__VA_ARGS__);                    \
                static void Lower##_free(Name* _Nonnull self) {                             \
                    self->_free(self->id);                                                  \
                    free((void*) self);                                                     \
                }                                                                           \
                LIB_EXPORT RC_##Name* _Nonnull FUNC_NEW(                                    \
                    size_t id,                                                              \
                    int32_t hash_code,                                                      \
                    void* _Nonnull invoke,                                                  \
                    void* _Nonnull equals,                                                  \
                    void* _Nonnull free);                                                   \
                LIB_EXPORT size_t FUNC_ID(RC_##Name* _Nonnull _self);                       \
                LIB_EXPORT void FUNC_FREE(RC_##Name* _Nonnull _self);
            """.trimIndent()) else appendLine("""
            
                #define KCallbackDef(Name, Lower, Type, ...)                                \
                struct Name {                                                               \
                    size_t id;                                                              \
                    int32_t hash_code;                                                      \
                    Type (* _Nonnull invoke)(size_t id, ##__VA_ARGS__);                     \
                    bool (* _Nonnull equals)(size_t id, size_t other);                      \
                    void (* _Nonnull _free)(size_t id);                                     \
                };                                                                          \
                Type Lower##_invoke(RC_##Name* _Nonnull, ##__VA_ARGS__);
            """.trimIndent())

            context.usedCallbacks.forEach { callback ->
                val args = buildList {
                    val lower = callback.name.camelCase().lowercase()
                    add(callback.cname)
                    add(lower)
                    if(isInternal) {
                        add(context.mangle("${lower}_new"))
                        add(context.mangle("${lower}_id"))
                        add(context.mangle("${lower}_free"))
                    }
                    add(callback.type.toLangType())
                    callback.args.mapTo(this) {
                        "${it.type.toLangType()} ${it.cname}"
                    }
                }.joinToString()
                append("\nKCallbackDef($args)")
            }
            append("\n#undef KCallbackDef\n")
        } else {
            append("""
                #define KCallbackFunc(FUNC_NEW, FUNC_ID, FUNC_FREE) \
                LIB_EXPORT void* _Nonnull FUNC_NEW(size_t id, int32_t hash_code, void* _Nonnull invoke, void* _Nonnull equals, void* _Nonnull free); \
                LIB_EXPORT size_t FUNC_ID(void* _Nonnull _self); \
                LIB_EXPORT void FUNC_FREE(void* _Nonnull _self);
                
                
            """.trimIndent())
            context.usedCallbacks.forEach { callback ->
                val lower = callback.name.camelCase().lowercase()
                append("KCallbackFunc(${context.mangle("${lower}_new")}, ${context.mangle("${lower}_id")}, ${context.mangle("${lower}_free")})\n")
            }
            append("\n#undef KCallbackFunc\n")
        }
    }

    private fun StringBuilder.printFunctions() {
        if (context.allOperations.isEmpty())
            return

        printLabel("Functions")

        context.allOperations.forEach { function ->
            val critical = function.isCritical()
            val name = function.cname
            val mangledName = function.cnameMangled(context)

            // C-API
            if (language == Language.C && (!function.isInterfaceOperationAddress() && !function.isInterfaceOperationClone())) {
                val type = function.type.toLangType(rcAsVoid = true)
                val args = function.args.joinToString {
                    "${it.type.toLangType(rcAsVoid = true)} ${it.cname}"
                }.ifEmpty { "void" }

                append("\n$type $name(${args});")
            }

            // Mangled API
            if (isInternal) {
                val type = function.type.toLangType()
                val args = function.args.flatMap {
                    val name = it.cname
                    when {
                        critical && it.type.isString() -> listOf(
                            "const char* _Nullable $name",
                            "int32_t _${name}_length",
                            "int32_t _${name}_size"
                        )
                        critical && it.type.isArray() -> listOf(
                            "const ${it.type.arrayTypeOrNull()!!.toLangType()}* _Nullable $name",
                            "int32_t _${name}_length"
                        )
                        else -> listOf("${it.type.toLangType()} $name")
                    }
                }.joinToString().ifEmpty { "void" }
                append("\nLIB_EXPORT $type $mangledName($args);")
            }
        }
        append("\n")
    }

    private fun ResolvedIdlType.toLangType(
        enumAsInt: Boolean = false,
        rcAsVoid: Boolean = false
    ): String = when (language) {
        Language.C -> toCType(printNullable = true, enumAsInt = enumAsInt, rcAsVoid = rcAsVoid)
        else -> toCommonNativeType(printNullable = true)
    }
}

