/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */

#pragma once

#include <memory>
#include <string>
#include <cstring>

// ╔═══════════════╗
// ║     Enums     ║
// ╚═══════════════╝

enum MyEnum {
	A
};

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

void stub(MyEnum e);

#include "api.tpp"