/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */

#pragma once

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

#define ARG_LENGTH(...) ARG_LENGTH__(__VA_ARGS__)
#define ARG_LENGTH__(...) ARG_LENGTH_(,##__VA_ARGS__,                          \
    63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45,\
    44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,\
    25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6,\
    5, 4, 3, 2, 1, 0)
#define ARG_LENGTH_(_, _63, _62, _61, _60, _59, _58, _57, _56, _55, _54, _53,  \
    _52, _51, _50, _49, _48, _47, _46, _45, _44, _43, _42, _41, _40, _39, _38, \
    _37, _36, _35, _34, _33, _32, _31, _30, _29, _28, _27, _26, _25, _24, _23, \
    _22, _21, _20, _19, _18, _17, _16, _15, _14, _13, _12, _11, _10, _9, _8,   \
    _7, _6, _5, _4, _3, _2, _1, Count, ...) Count

// ╔═══════════════╗
// ║     Types     ║
// ╚═══════════════╝

typedef struct KIntArray KIntArray;
struct KIntArray {
    KIntArray* _Nonnull (* _Nonnull clone)(const KIntArray* _Nonnull);
    void (* _Nonnull free)(KIntArray* _Nonnull);
    const int32_t* _Nonnull elements;
    int32_t length;
};

KIntArray* _Nonnull kint_array_new(const int32_t* _Nonnull elements, int32_t length, bool make_copy);
KIntArray* _Nonnull kint_array_of_n(int n, ...);
#define kint_array_of(...) kint_array_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
KIntArray* _Nullable kint_array_clone(const KIntArray* _Nullable self);
void kint_array_free(KIntArray* _Nullable self);

typedef struct KLongArray KLongArray;
struct KLongArray {
    KLongArray* _Nonnull (* _Nonnull clone)(const KLongArray* _Nonnull);
    void (* _Nonnull free)(KLongArray* _Nonnull);
    const int64_t* _Nonnull elements;
    int32_t length;
};

KLongArray* _Nonnull klong_array_new(const int64_t* _Nonnull elements, int32_t length, bool make_copy);
KLongArray* _Nonnull klong_array_of_n(int n, ...);
#define klong_array_of(...) klong_array_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
KLongArray* _Nullable klong_array_clone(const KLongArray* _Nullable self);
void klong_array_free(KLongArray* _Nullable self);

// ╔═══════════════╗
// ║     Enums     ║
// ╚═══════════════╝

typedef enum {
	MyEnum_A
} MyEnum;

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

void stub1(KLongArray* _Nonnull e);
void stub2(KIntArray* _Nonnull e);
