/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */
 
#ifndef KOTLIN_NATIVE_GLFWBINDINGS_H
#define KOTLIN_NATIVE_GLFWBINDINGS_H

#include <stdlib.h>
#include <stdarg.h>

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

// ╔════════════════╗
// ║     stdlib     ║
// ╚════════════════╝

#define K_FLAG_RELEASABLE 1
#define K_FLAG_ON_STACK 2

#define K_OBJECT_IS_RELEASABLE(flags) ((flags) & K_FLAG_RELEASABLE)
#define K_OBJECT_IS_ON_STACK(flags) ((flags) & K_FLAG_ON_STACK)

typedef int32_t  KInt;
typedef int64_t  KLong;
typedef float    KFloat;
typedef double   KDouble;
typedef int8_t   KByte;
typedef int16_t  KShort;
typedef bool     KBoolean;
typedef uint16_t KChar;

typedef struct KString {
    char __flags;
    const char* data;
    KInt length;
    size_t size;
} KString;

static KString* KString_new(const char* data, const KInt length, const KInt size) {
    KString* result = (KString*) malloc(sizeof(KString));
    *result = (KString) { K_FLAG_RELEASABLE, data, length, size };
    return result;
}

static KString* KString_clone(const KString* of) {
    const KInt size = of->size;
    void* data = malloc(size);
    memcpy(data, of->data, size);
    KString* result = (KString*) malloc(sizeof(KString));
    *result = (KString) { K_FLAG_RELEASABLE, (const char*) data, of->length, size };
    return result;
}

static void KString_free(KString* str) {
    if(!K_OBJECT_IS_RELEASABLE(str->__flags))
        return;
    free((void*) str->data);
    if(!K_OBJECT_IS_ON_STACK(str->__flags))
        free((void*) str);
}

#define ARG_LENGTH(...) ARG_LENGTH__(__VA_ARGS__)
#define ARG_LENGTH__(...) ARG_LENGTH_(,##__VA_ARGS__,                          \
    63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45,\
    44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,\
    25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6,\
    5, 4, 3, 2, 1, 0)
#define ARG_LENGTH_(_, _63, _62, _61, _60, _59, _58, _57, _56, _55, _54, _53,  \
    _52, _51, _50, _49, _48, _47, _46, _45, _44, _43, _42, _41, _40, _39, _38, \
    _37, _36, _35, _34, _33, _32, _31, _30, _29, _28, _27, _26, _25, _24, _23, \
    _22, _21, _20, _19, _18, _17, _16, _15, _14, _13, _12, _11, _10, _9, _8,   \
    _7, _6, _5, _4, _3, _2, _1, Count, ...) Count

#define KArrayDef(Name, Type, VarargType)                          \
typedef struct Name {                                              \
    char __flags;                                                  \
    const Type* elements;                                          \
    KInt length;				                                   \
    size_t size;				                                   \
} Name;                                                            \
                                                                   \
static Name* Name##_new(const Type* elements, const KInt length) { \
    Name* result = (Name*) malloc(sizeof(Name));                   \
    *result = (Name){                                              \
        K_FLAG_RELEASABLE,                                         \
        elements,                                                  \
        length,                                                    \
        length * sizeof(Name)                                      \
    };                                                             \
    return result;                                                 \
}                                                                  \
                                                                   \
static Name* _##Name##_of(const int n, ...) {                      \
    va_list args;                                                  \
    va_start(args, n);                                             \
    Type* elements = (Type*)malloc(n * sizeof(Type));              \
    for (int i = 0; i < n; i++)                                    \
        elements[i] = (Type)va_arg(args, VarargType);              \
    va_end(args);                                                  \
    Name* result = (Name*) malloc(sizeof(Name));                   \
    *result = (Name){                                              \
        K_FLAG_RELEASABLE,                                         \
        (const Type*) elements,                                    \
        n,                                                         \
        n * sizeof(Name)                                           \
    };                                                             \
    return result;                                                 \
}

#define KArrayCloneDef(Name, Type)                                     \
static Name* Name##_clone(const Name* of) {                            \
    const KInt size = of->size;                                        \
    void** elements = malloc(size);                                    \
    memcpy(elements, (void*) of->elements, size);                      \
    Name* result = (Name*) malloc(sizeof(Name));                       \
    *result = (Name) {                                                 \
        K_FLAG_RELEASABLE,                                             \
        (Type*) elements,                                              \
        of->length,                                                    \
        of->size                                                       \
    };                                                                 \
    return result;                                                     \
}                                                                      \
                                                                       \
static void Name##_free(Name* arr) {                                   \
    if(!K_OBJECT_IS_RELEASABLE(arr->__flags))                          \
        return;                                                        \
    free((void*) arr->elements);                                       \
    if(!K_OBJECT_IS_ON_STACK(arr->__flags))                            \
        free((void*) arr);                                             \
}

KArrayDef(KCharArray,	 KChar,    int32_t)
KArrayDef(KBooleanArray, KBoolean, int32_t)
KArrayDef(KByteArray,	 KByte,    int32_t)
KArrayDef(KShortArray,	 KShort,   int32_t)
KArrayDef(KIntArray,	 KInt,     int32_t)
KArrayDef(KLongArray,	 KLong,    int64_t)
KArrayDef(KFloatArray,	 KFloat,   double)
KArrayDef(KDoubleArray,  KDouble,  double)
KArrayDef(KArray,        void*,    void*)
#undef KArrayDef

#define KCharArray_of(...)    _KCharArray_of(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
#define KBooleanArray_of(...) _KBooleanArray_of(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
#define KByteArray_of(...)    _KByteArray_of(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
#define KShortArray_of(...)   _KShortArray_of(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
#define KIntArray_of(...)     _KIntArray_of(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
#define KFloatArray_of(...)   _KFloatArray_of(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
#define KDoubleArray_of(...)  _KDoubleArray_of(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
#define KArray_of(...)        _KArray_of(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)

KArrayCloneDef(KCharArray,    KChar)
KArrayCloneDef(KBooleanArray, KBoolean)
KArrayCloneDef(KByteArray,    KByte)
KArrayCloneDef(KShortArray,   KShort)
KArrayCloneDef(KIntArray,     KInt)
KArrayCloneDef(KLongArray,    KLong)
KArrayCloneDef(KFloatArray,   KFloat)
KArrayCloneDef(KDoubleArray,  KDouble)

static KArray* KArray_clone(const KArray* of, void* (*cloneOp)(void*)) {
	const KInt size = of->size;
	void** elements = malloc(size);
	for (int i = 0; i < of->length; i++)
		elements[i] = cloneOp((void*)of->elements[i]);
	KArray* result = (KArray*) malloc(sizeof(KArray));
	*result = (KArray) { 
        K_FLAG_RELEASABLE, 
        (const void**) elements, 
        of->length, 
        of->size
    }; 
	return result;
}

static void KArray_free(const KArray* arr, void* (*freeOp)(void*)) {
    if(!K_OBJECT_IS_RELEASABLE(arr->__flags))
        return;
    const void** elements = arr->elements;
    for (int i = 0; i < arr->length; i++)
        freeOp((void*) elements[i]);
    free((void*) elements);
    if(!K_OBJECT_IS_ON_STACK(arr->__flags))
        free((void*) arr);
}

#define KCallbackDef(Name, Type, ...)       \
struct Name {                               \
    char __flags;                           \
    Type (*invoke)(Name* _, ##__VA_ARGS__); \
    Name* (*clone)(Name* _);                \
    KBoolean (*equals)(Name* _, Name* obj); \
    KInt (*hashCode)(Name* _);              \
    void (*free)(Name* _);                  \
};

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

void run();
void glfwInit();

#ifdef __cplusplus
}
#endif

#endif // KOTLIN_NATIVE_GLFWBINDINGS_H