/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */

#pragma once

#include <memory>
#include <string>

// ╔══════════════════════════╗
// ║     Type definitions     ║
// ╚══════════════════════════╝

struct IEmptyInterface;
struct IMyInterface;

// ╔════════════════════╗
// ║     Interfaces     ║
// ╚════════════════════╝

struct IEmptyInterface {
	virtual ~IEmptyInterface() = default;
};

struct IMyInterface {
	virtual void func() = 0;
	virtual ~IMyInterface() = default;
};

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

void stub1(const std::shared_ptr<IEmptyInterface>& e);
void stub2(const std::shared_ptr<IMyInterface>& e);

#include "api.tpp"