/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */

#pragma once

#include <memory>
#include <string>

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

void hello_world();

#include "api.tpp"