package com.huskerdev.nativekt.printers.cpp

import com.huskerdev.nativekt.*
import com.huskerdev.nativekt.utils.*
import io.github.vinceglb.filekit.*
import kotlinx.io.SystemLineSeparator

class CppApiHeaderPrinter(
    val context: NativeModuleContext,
    target: PlatformFile,
    tppTarget: PlatformFile
) {
    init {
        target.parent()!!.createDirectories()
        target.writeSync(buildString {
            printHeader()
            printStdLib()
            printTypeDefs()
            printEnums()
            printInterfaces()
            printCallbacks()
            printStructs()
            printFunctions()
            append("\n#include \"api.tpp\"")
        }.replace("\n", SystemLineSeparator))

        tppTarget.parent()!!.createDirectories()
        tppTarget.writeSync(buildString {
            printTtp()
        }.replace("\n", SystemLineSeparator))
    }

    private fun StringBuilder.printHeader(){
        append("""
            /*
             * This file was automatically generated by Gradle.
             *
             * DO NOT EDIT THIS FILE MANUALLY.
             * Any changes made to this file will be overwritten the next time
             * the project is built.
             */
            
            #pragma once
            
            #include <memory>
            #include <string>
            #include <cstring>
            
        """.trimIndent())
    }

    private fun StringBuilder.printStdLib() {
        if(!context.hasNullableCast &&
            !context.hasStringCast &&
            !context.hasObjectArraysCast &&
            !context.hasPrimitiveArrayCast
        ) return

        printLabel("Types")

        if(context.hasNullableCast) append("""
            
            template <typename T> class KOptional {
                bool is_empty;
                alignas(T) unsigned char storage[sizeof(T)];
            public:
                KOptional();
                explicit KOptional(const T& value);
                explicit KOptional(T&& value);
                ~KOptional();
                KOptional(const KOptional&);
                KOptional& operator=(const KOptional&);
                KOptional(KOptional&&) noexcept;
                KOptional& operator=(KOptional&&) noexcept;
                T& operator*() &;
                T&& operator*() &&;
                bool is_none() const;
                T* _Nullable get_ptr();
                const T* _Nullable get_ptr() const;
            };
        """.trimIndent())
        if(context.hasStringCast) append("""
            
            class KString {
                char* _Nonnull data;
                int32_t length;
                size_t size;
            public:
                explicit KString(const char* _Nonnull data, int32_t length, size_t size, bool copy = true);
                explicit KString(const char* _Nonnull data, bool copy = true);
                KString(const KString& other);
                KString(KString&& other) noexcept;
                KString& operator=(KString&& other) noexcept;
                ~KString();
                std::string* _Nonnull to_string() const;
                const char* _Nonnull get_data() const;
                int32_t get_length() const;
                size_t get_size() const;
                explicit operator const char* _Nonnull() const;
            };
        """.trimIndent())
        if(context.hasObjectArraysCast || context.hasPrimitiveArrayCast) append("""
            
            template <typename T> class KArray {
                T* _Nonnull elements;
                int32_t length;
                int32_t capacity;
            public:
                explicit KArray(int32_t capacity);
                explicit KArray(T* _Nonnull elements, int32_t length, bool copy = true);
                explicit KArray(std::initializer_list<T> elements);
                KArray(const KArray& other);
                KArray(KArray&& other) noexcept;
                KArray& operator=(KArray&& other) noexcept;
                ~KArray();
                explicit operator const T* _Nonnull () const;
                const T& operator[](size_t index) const;
                void push(T&& element);
                T& get(int32_t index);
                const T* _Nonnull get_elements();
                int32_t get_length() const;
            };
        """.trimIndent())
        append("\n")
    }

    private fun StringBuilder.printTypeDefs() {
        if(context.callbacks.isEmpty() &&
            context.dictionaries.isEmpty() &&
            context.interfaces.isEmpty()
        ) return

        printLabel("Type definitions")

        buildList {
            addAll(context.dictionaries)
            addAll(context.callbacks)
            addAll(context.interfaces)
        }.map { it.cppName }.joinTo(this, separator = "") {
            "\nstruct $it;"
        }
        append("\n")
    }

    private fun StringBuilder.printEnums() {
        if(context.enums.isEmpty())
            return
        printLabel("Enums")

        context.enums.forEach { enum ->
            append("\nenum ${enum.cppName} {")
            enum.elements.joinTo(this) { "\n\t$it" }
            append("\n};\n")
        }
    }

    private fun StringBuilder.printInterfaces() {
        if(context.interfaces.isEmpty())
            return
        printLabel("Interfaces")

        context.interfaces.forEach { inter ->
            val interName = inter.cppName

            append("\nstruct $interName {")
            context.interfaceOperations[inter]!!.forEach { operation ->
                val funcName = operation.cppName
                val args = operation.args.map {
                    "${it.type.toCppType()} ${it.cppName}"
                }
                val type = operation.type.toCppType()

                when {
                    operation.isInterfaceOperationConstructor() ->
                        append("\n\tstatic $interName* _Nonnull $funcName(${args.joinToString()});")
                    operation.isInterfaceOperationFn() -> {
                        val args = args.drop(1).joinToString()
                        append("\n\tvirtual $type $funcName($args) = 0;")
                    }
                    operation.isInterfaceOperationFree() ->
                        append("\n\tvirtual ~$interName() = default;")
                    else -> return@forEach
                }
            }
            append("\n};\n")
        }
    }

    private fun StringBuilder.printCallbacks() {
        if (context.callbacks.isEmpty())
            return
        printLabel("Callbacks")

        append("""
            
            #define KCallbackDef(Name, Type, ...)             \
            class Name {                                      \
                void* _Nonnull _invoke;                       \
                bool (* _Nonnull _equals)(size_t, size_t);    \
                void (* _Nonnull _free)(size_t);              \
            public:                                           \
                size_t id;                                    \
            	int32_t hash_code;                               \
            	~Name();                                      \
                Name(                                         \
                    size_t id,                                \
                    int32_t hash_code,                           \
                    void* _Nonnull invoke,                    \
                    bool (* _Nonnull equals)(size_t, size_t), \
                    void (* _Nonnull free)(size_t)            \
                );                                            \
                Name(const Name&) = delete;                   \
                Name& operator=(const Name&) = delete;        \
                Name(Name&&) noexcept = delete;               \
                Name& operator=(Name&&) noexcept = delete;    \
                                                              \
                bool operator==(const Name& other) const;     \
                Type invoke(__VA_ARGS__) const;               \
            };
            
        """.trimIndent())

        context.callbacks.forEach { callback ->
            val params = buildList {
                add(callback.cppName)
                add(callback.type.toCppType())
                callback.args.mapTo(this) {
                    "${it.type.toCppType()} ${it.cppName}"
                }
            }.joinToString()
            append("\nKCallbackDef($params)")
        }
        append("\n")
    }

    private fun StringBuilder.printStructs() {
        if(context.dictionaries.isEmpty())
            return
        printLabel("Structs")

        context.dictionaries.sortedWith { d1, d2 ->
            when {
                d1 == d2.implements -> -1
                d1.implements == d2 -> 1
                else -> d1.name.compareTo(d2.name)
            }
        }.forEach { dictionary ->
            val name = dictionary.cppName
            val parent = if(dictionary.implements != null)
                " : ${dictionary.implements?.cppName}" else ""

            val allFields = context.allFields[dictionary]!!
            val allArgs = allFields.map { field ->
                "${field.type.toCppType()} ${field.cppName}"
            }

            val localFields = dictionary.fields
            val localArgs = localFields.map { field ->
                "${field.type.toCppType()} ${field.cppName}"
            }

            append("\nstruct $name$parent {")
            localArgs.joinTo(this, separator = "") { "\n\t$it;" }
            append("""
                    
                    $name(${allArgs.joinToString()});
                    $name(const $name& other);
                };
                
            """.trimIndent())
        }
    }

    private fun StringBuilder.printFunctions() {
        if(context.allOperations.isEmpty())
            return
        printLabel("Functions")

        context.allOperations.forEach { function ->
            val name = function.cppName
            val type = function.type.toCppType()
            val args = function.args.joinToString {
                val type = if(it.type.isReleasable())
                    "const ${it.type.toCppType()}&"
                else it.type.toCppType()
                "$type ${it.cppName}"
            }

            if (!function.isInterfaceOperation())
                append("\n$type $name($args);")
        }
        append("\n")
    }

    private fun StringBuilder.printTtp() {
        append("""
            /*
             * This file was automatically generated by Gradle.
             *
             * DO NOT EDIT THIS FILE MANUALLY.
             * Any changes made to this file will be overwritten the next time
             * the project is built.
             */
             
            #pragma once
            
        """.trimIndent())

        if(context.hasNullableCast) {
            printLabel("Tools")
            if(context.hasNullableCastToKotlin) appendLine("""
                
                template<typename T>
                T* _Nullable obj_opt(KOptional<T> opt, T* _Nonnull (* _Nonnull wrap)(T)) {
                    if (opt.is_none()) return nullptr;
                    return wrap(std::move(*opt.get_ptr()));
                }
            """.trimIndent())
            if(context.hasNullableCastToNative) appendLine("""
                
                template<typename T>
                KOptional<T> ptr_opt(T* _Nullable arg, T (* _Nonnull unwrap)(T* _Nonnull)) {
                    if (arg == nullptr) return KOptional<T>();
                    return KOptional<T>(unwrap(arg));
                }
            """.trimIndent())

            printLabel("Optional")
            appendLine("""
                
                // ReSharper disable once CppPossiblyUninitializedMember
                template<typename T>
                KOptional<T>::KOptional(): is_empty(true) {}
    
                template<typename T>
                KOptional<T>::KOptional(const T& value) : is_empty(false) {
                    ::new (static_cast<void*>(storage)) T(value);
                }
    
                template<typename T>
                KOptional<T>::KOptional(T &&value) : is_empty(false) {
                    ::new (static_cast<void*>(storage)) T(std::move(value));
                }
    
                template<typename T>
                KOptional<T>::~KOptional() {
                    if (!is_empty) {
                        if constexpr (!std::is_trivially_destructible_v<T>)
                            get_ptr()->~T();
                        is_empty = true;
                    }
                }
    
                template<typename T>
                KOptional<T>::KOptional(const KOptional& other) : is_empty(other.is_empty) {
                    if (!is_empty) {
                        if constexpr (std::is_trivially_copyable_v<T>)
                            std::memcpy(storage, other.storage, sizeof(T));
                        else
                            ::new (static_cast<void*>(storage)) T(*other.get_ptr());
                    }
                }
    
                template<typename T>
                KOptional<T>::KOptional(KOptional&& other) noexcept : is_empty(other.is_empty) {
                    if (!is_empty) {
                        if constexpr (std::is_trivially_copyable_v<T>) {
                            std::memcpy(storage, other.storage, sizeof(T));
                        } else {
                            ::new (static_cast<void*>(storage)) T(std::move(*other.get_ptr()));
                            if constexpr (!std::is_trivially_destructible_v<T>)
                                other.get_ptr()->~T();
                        }
                        other.is_empty = true;
                    }
                }
    
                template<typename T>
                KOptional<T> &KOptional<T>::operator=(const KOptional &other) {
                    if (this != &other) {
                        if (!other.is_empty) {
                            if (!is_empty)
                                *get_ptr() = *other.get_ptr();
                            else {
                                ::new (static_cast<void*>(storage)) T(*other.get_ptr());
                                is_empty = false;
                            }
                        } else if (!is_empty) {
                            if constexpr (!std::is_trivially_destructible_v<T>)
                                get_ptr()->~T();
                            is_empty = true;
                        }
                    }
                    return *this;
                }
    
                template<typename T>
                KOptional<T> &KOptional<T>::operator=(KOptional&& other) noexcept {
                    if (this != &other) {
                        if (!other.is_empty) {
                            if (!is_empty)
                                *get_ptr() = std::move(*other.get_ptr());
                            else {
                                ::new (static_cast<void*>(storage)) T(std::move(*other.get_ptr()));
                                is_empty = false;
                            }
                            if constexpr (!std::is_trivially_destructible_v<T>)
                                other.get_ptr()->~T();
                            other.is_empty = true;
                        } else if (!is_empty) {
                            if constexpr (!std::is_trivially_destructible_v<T>)
                                get_ptr()->~T();
                            is_empty = true;
                        }
                    }
                    return *this;
                }
    
                template<typename T>
                T& KOptional<T>::operator*() & {
                    return *get_ptr();
                }
    
                template<typename T>
                T &&KOptional<T>::operator*() && {
                    return std::move(*get_ptr());
                }
    
                template<typename T>
                T* _Nullable KOptional<T>::get_ptr() {
                    if (is_empty) return nullptr;
                    return reinterpret_cast<T*>(storage);
                }
    
                template<typename T>
                const T* _Nullable KOptional<T>::get_ptr() const {
                    if (is_empty) return nullptr;
                    return reinterpret_cast<const T*>(storage);
                }
    
                template<typename T>
                bool KOptional<T>::is_none() const {
                    return is_empty;
                }
            """.trimIndent())
        }

        if(context.hasPrimitiveArrayCast || context.hasObjectArraysCast) {
            printLabel("Array")
            append("""
                
                template<typename T> 
                KArray<T>* _Nonnull karray_wrap(KArray<T> value) {
                    return new KArray<T>(std::move(value));
                }
    
                template<typename T>
                KArray<T> karray_unwrap(KArray<T>* _Nonnull arg) {
                    KArray<T> result = std::move(*arg);
                    delete arg;
                    return result;
                }
    
                template<typename T>
                KArray<T>::KArray(const int32_t capacity): elements(nullptr), length(0), capacity(capacity) {
                    if (capacity > 0) {
                        elements = static_cast<T*>(malloc(sizeof(T) * capacity));
                    }
                }
    
                template<typename T>
                KArray<T>::KArray(T* _Nonnull elements, const int32_t length, const bool copy): length(length), capacity(length) {
                    if (copy) {
                        this->elements = static_cast<T*>(malloc(sizeof(T) * length));
                        if constexpr (std::is_trivially_copyable_v<T>) {
                            std::memcpy(this->elements, elements, sizeof(T) * length);
                        } else {
                            for (int32_t i = 0; i < length; ++i)
                                new (&this->elements[i]) T(elements[i]);
                        }
                    } else this->elements = elements;
                }
    
                template<typename T>
                KArray<T>::KArray(std::initializer_list<T> elements): length(elements.size()), capacity(elements.size()) {
                    this->elements = static_cast<T*>(malloc(sizeof(T) * elements.size()));
                    if constexpr (std::is_trivially_copyable_v<T>) {
                        std::memcpy(this->elements, elements.begin(), sizeof(T) * elements.size());
                    } else {
                        int32_t i = 0;
                        for (const auto& e : elements)
                            new (&this->elements[i++]) T(e);
                    }
                }
    
                template<typename T>
                KArray<T>::KArray(const KArray &other): length(other.length), capacity(other.capacity) {
                    elements = static_cast<T*>(malloc(sizeof(T) * capacity));
                    if constexpr (std::is_trivially_copyable_v<T>) {
                        std::memcpy(elements, other.elements, sizeof(T) * length);
                    } else {
                        for (int32_t i = 0; i < length; ++i)
                            new (&elements[i]) T(other.elements[i]);
                    }
                }
    
                template<typename T>
                KArray<T>::KArray(KArray&& other) noexcept
                    : elements(other.elements), length(other.length), capacity(other.capacity) {
                    other.elements = nullptr;
                    other.length = 0;
                    other.capacity = 0;
                }
    
                template<typename T>
                KArray<T>& KArray<T>::operator=(KArray&& other) noexcept {
                    if (this != &other) {
                        if constexpr (!std::is_trivially_destructible_v<T>) {
                            for (size_t i = 0; i < length; i++)
                                elements[i].~T();
                        }
                        free(elements);
                        elements = other.elements;
                        length = other.length;
                        capacity = other.capacity;
                        other.elements = nullptr;
                        other.length = 0;
                        other.capacity = 0;
                    }
                    return *this;
                }
    
                template<typename T>
                KArray<T>::~KArray() {
                    if constexpr (!std::is_trivially_destructible_v<T>) {
                        for (size_t i = 0; i < length; i++)
                            elements[i].~T();
                    }
                    free(elements);
                }
    
                template<typename T>
                KArray<T>::operator const T* _Nonnull () const {
                    return elements;
                }
    
                template<typename T>
                const T& KArray<T>::operator[](size_t index) const {
                    return elements[index];
                }
    
                template<typename T>
                void KArray<T>::push(T&& element) {
                    if (length >= capacity) {
                        capacity = capacity == 0 ? 4 : capacity * 2;
                        if constexpr (std::is_trivially_copyable_v<T>) {
                            elements = static_cast<T*>(realloc(elements, sizeof(T) * capacity));
                        } else {
                            T* new_elements = static_cast<T*>(malloc(sizeof(T) * capacity));
                            for (int32_t i = 0; i < length; ++i)
                                new (&new_elements[i]) T(std::move(elements[i]));
                            if constexpr (!std::is_trivially_destructible_v<T>) {
                                for (int32_t i = 0; i < length; i++)
                                    elements[i].~T();
                            }
                            free(elements);
                            elements = new_elements;
                        }
                    }
                    new (&elements[length]) T(std::move(element));
                    length++;
                }
    
                template<typename T>
                T &KArray<T>::get(int32_t index) {
                    return elements[index];
                }
    
                template<typename T>
                int32_t KArray<T>::get_length() const {
                    return length;
                }
    
                template<typename T>
                const T* _Nonnull KArray<T>::get_elements() {
                    return elements;
                }
                
            """.trimIndent())
        }
    }
}