package com.huskerdev.nativekt.printers

import com.huskerdev.nativekt.utils.globalOperators
import com.huskerdev.nativekt.utils.toCType
import com.huskerdev.webidl.resolver.IdlResolver
import com.huskerdev.webidl.resolver.ResolvedIdlOperation
import java.io.File

class HeaderPrinter(
    idl: IdlResolver,
    target: File,
    guardName: String? = null
) {
    private val defName = "KOTLIN_NATIVE_${guardName}_H"

    init {
        target.parentFile.mkdirs()

        val builder = StringBuilder()
        builder.append("""
            /*
             * This file was automatically generated by Gradle.
             *
             * DO NOT EDIT THIS FILE MANUALLY.
             * Any changes made to this file will be overwritten the next time
             * the project is built.
             */
             

        """.trimIndent())

        if(guardName != null) {
            builder.append("#ifndef $defName\n")
            builder.append("#define $defName\n")
        }

        builder.append("""
            
            #include <stddef.h>
            #include <stdint.h>
            #include <stdbool.h>
            
            #ifdef __cplusplus
            extern "C" {
            #endif
            
        """.trimIndent())

        idl.globalOperators().forEach { printFunction(builder, it) }

        builder.append("""
            
            
            #ifdef __cplusplus
            }
            #endif
        """.trimIndent())

        if(guardName != null)
            builder.append("\n\n#endif // $defName")

        target.writeText(builder.toString().replace("\n", System.lineSeparator()))
    }

    private fun printFunction(builder: StringBuilder, function: ResolvedIdlOperation) = builder.apply {
        append("\n")
        append(function.type.toCType())
        append(" ")
        append(function.name)
        append("(")

        function.args.joinTo(builder) {
            "${it.type.toCType()} ${it.name}"
        }

        append(");")
    }
}