/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */
 
#pragma once

// ╔═══════════════╗
// ║     Tools     ║
// ╚═══════════════╝

template<typename T>
T* _Nullable obj_opt(KOptional<T> opt, T* _Nonnull (* _Nonnull wrap)(T)) {
    if (opt.is_none()) return nullptr;
    return wrap(std::move(*opt.get_ptr()));
}

template<typename T>
KOptional<T> ptr_opt(T* _Nullable arg, T (* _Nonnull unwrap)(T* _Nonnull)) {
    if (arg == nullptr) return KOptional<T>();
    return KOptional<T>(unwrap(arg));
}

// ╔══════════════════╗
// ║     Optional     ║
// ╚══════════════════╝

// ReSharper disable once CppPossiblyUninitializedMember
template<typename T>
KOptional<T>::KOptional(): is_empty(true) {}

template<typename T>
KOptional<T>::KOptional(const T& value) : is_empty(false) {
    ::new (static_cast<void*>(storage)) T(value);
}

template<typename T>
KOptional<T>::KOptional(T &&value) : is_empty(false) {
    ::new (static_cast<void*>(storage)) T(std::move(value));
}

template<typename T>
KOptional<T>::~KOptional() {
    if (!is_empty) {
        if constexpr (!std::is_trivially_destructible_v<T>)
            get_ptr()->~T();
        is_empty = true;
    }
}

template<typename T>
KOptional<T>::KOptional(const KOptional& other) : is_empty(other.is_empty) {
    if (!is_empty) {
        if constexpr (std::is_trivially_copyable_v<T>)
            std::memcpy(storage, other.storage, sizeof(T));
        else
            ::new (static_cast<void*>(storage)) T(*other.get_ptr());
    }
}

template<typename T>
KOptional<T>::KOptional(KOptional&& other) noexcept : is_empty(other.is_empty) {
    if (!is_empty) {
        if constexpr (std::is_trivially_copyable_v<T>) {
            std::memcpy(storage, other.storage, sizeof(T));
        } else {
            ::new (static_cast<void*>(storage)) T(std::move(*other.get_ptr()));
            if constexpr (!std::is_trivially_destructible_v<T>)
                other.get_ptr()->~T();
        }
        other.is_empty = true;
    }
}

template<typename T>
KOptional<T> &KOptional<T>::operator=(const KOptional &other) {
    if (this != &other) {
        if (!other.is_empty) {
            if (!is_empty)
                *get_ptr() = *other.get_ptr();
            else {
                ::new (static_cast<void*>(storage)) T(*other.get_ptr());
                is_empty = false;
            }
        } else if (!is_empty) {
            if constexpr (!std::is_trivially_destructible_v<T>)
                get_ptr()->~T();
            is_empty = true;
        }
    }
    return *this;
}

template<typename T>
KOptional<T> &KOptional<T>::operator=(KOptional&& other) noexcept {
    if (this != &other) {
        if (!other.is_empty) {
            if (!is_empty)
                *get_ptr() = std::move(*other.get_ptr());
            else {
                ::new (static_cast<void*>(storage)) T(std::move(*other.get_ptr()));
                is_empty = false;
            }
            if constexpr (!std::is_trivially_destructible_v<T>)
                other.get_ptr()->~T();
            other.is_empty = true;
        } else if (!is_empty) {
            if constexpr (!std::is_trivially_destructible_v<T>)
                get_ptr()->~T();
            is_empty = true;
        }
    }
    return *this;
}

template<typename T>
T& KOptional<T>::operator*() & {
    return *get_ptr();
}

template<typename T>
T &&KOptional<T>::operator*() && {
    return std::move(*get_ptr());
}

template<typename T>
T* _Nonnull KOptional<T>::get_ptr() {
    return reinterpret_cast<T*>(storage);
}

template<typename T>
const T* _Nonnull KOptional<T>::get_ptr() const {
    return reinterpret_cast<const T*>(storage);
}

template<typename T>
bool KOptional<T>::is_none() const {
    return is_empty;
}

// ╔═══════════════╗
// ║     Array     ║
// ╚═══════════════╝

template<typename T> 
KArray<T>* _Nonnull karray_wrap(KArray<T> value) {
    return new KArray<T>(std::move(value));
}

template<typename T>
KArray<T> karray_unwrap(KArray<T>* _Nonnull arg) {
    KArray<T> result = std::move(*arg);
    delete arg;
    return result;
}

template<typename T>
KArray<T>::KArray(const int32_t capacity): elements(nullptr), length(0), capacity(capacity) {
    if (capacity > 0) {
        elements = static_cast<T*>(malloc(sizeof(T) * capacity));
    }
}

template<typename T>
KArray<T>::KArray(T* _Nonnull elements, const int32_t length, const bool copy): length(length), capacity(length) {
    if (copy) {
        this->elements = static_cast<T*>(malloc(sizeof(T) * length));
        if constexpr (std::is_trivially_copyable_v<T>) {
            std::memcpy(this->elements, elements, sizeof(T) * length);
        } else {
            for (int32_t i = 0; i < length; ++i)
                new (&this->elements[i]) T(elements[i]);
        }
    } else this->elements = elements;
}

template<typename T>
KArray<T>::KArray(std::initializer_list<T> elements): length(elements.size()), capacity(elements.size()) {
    this->elements = static_cast<T*>(malloc(sizeof(T) * elements.size()));
    if constexpr (std::is_trivially_copyable_v<T>) {
        std::memcpy(this->elements, elements.begin(), sizeof(T) * elements.size());
    } else {
        int32_t i = 0;
        for (const auto& e : elements)
            new (&this->elements[i++]) T(e);
    }
}

template<typename T>
KArray<T>::KArray(const KArray &other): length(other.length), capacity(other.capacity) {
    elements = static_cast<T*>(malloc(sizeof(T) * capacity));
    if constexpr (std::is_trivially_copyable_v<T>) {
        std::memcpy(elements, other.elements, sizeof(T) * length);
    } else {
        for (int32_t i = 0; i < length; ++i)
            new (&elements[i]) T(other.elements[i]);
    }
}

template<typename T>
KArray<T>::KArray(KArray&& other) noexcept
    : elements(other.elements), length(other.length), capacity(other.capacity) {
    other.elements = nullptr;
    other.length = 0;
    other.capacity = 0;
}

template<typename T>
KArray<T>& KArray<T>::operator=(KArray&& other) noexcept {
    if (this != &other) {
        if constexpr (!std::is_trivially_destructible_v<T>) {
            for (size_t i = 0; i < length; i++)
                elements[i].~T();
        }
        free(elements);
        elements = other.elements;
        length = other.length;
        capacity = other.capacity;
        other.elements = nullptr;
        other.length = 0;
        other.capacity = 0;
    }
    return *this;
}

template<typename T>
KArray<T>::~KArray() {
    if constexpr (!std::is_trivially_destructible_v<T>) {
        for (size_t i = 0; i < length; i++)
            elements[i].~T();
    }
    free(elements);
}

template<typename T>
KArray<T>::operator const T* _Nonnull () const {
    return elements;
}

template<typename T>
const T& KArray<T>::operator[](size_t index) const {
    return elements[index];
}

template<typename T>
void KArray<T>::push(T&& element) {
    if (length >= capacity) {
        capacity = capacity == 0 ? 4 : capacity * 2;
        if constexpr (std::is_trivially_copyable_v<T>) {
            elements = static_cast<T*>(realloc(elements, sizeof(T) * capacity));
        } else {
            T* new_elements = static_cast<T*>(malloc(sizeof(T) * capacity));
            for (int32_t i = 0; i < length; ++i)
                new (&new_elements[i]) T(std::move(elements[i]));
            if constexpr (!std::is_trivially_destructible_v<T>) {
                for (int32_t i = 0; i < length; i++)
                    elements[i].~T();
            }
            free(elements);
            elements = new_elements;
        }
    }
    new (&elements[length]) T(std::move(element));
    length++;
}

template<typename T>
T &KArray<T>::get(int32_t index) {
    return elements[index];
}

template<typename T>
int32_t KArray<T>::get_length() const {
    return length;
}

template<typename T>
const T* _Nonnull KArray<T>::get_elements() {
    return elements;
}
