/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */

#pragma once

#include <initializer_list>
#include <cstdint>
#include <memory>


// ╔═══════════════╗
// ║     Types     ║
// ╚═══════════════╝

typedef int32_t  KInt;
typedef uint32_t KUInt;
typedef int64_t  KLong;
typedef uint64_t KULong;
typedef float    KFloat;
typedef double   KDouble;
typedef int8_t   KByte;
typedef uint8_t  KUByte;
typedef int16_t  KShort;
typedef uint16_t KUShort;
typedef bool     KBoolean;
typedef uint16_t KChar;

struct KString {
    const char* _Nonnull data;
    size_t size;
    KInt length;
    char __flags;
    
    KString(const char* _Nonnull data, KInt length, size_t size, bool is_data_owner);
	KString* _Nonnull clone() const;
	void destroy();
};

struct KCharArray {
    const KChar* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
    
    KCharArray(const KChar* _Nonnull elements, KInt length, bool is_data_owner);
    static KCharArray* _Nonnull of(std::initializer_list<KChar> elements);
    KCharArray* _Nonnull clone() const;
    void destroy();
};

struct KBooleanArray {
    const KBoolean* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
    
    KBooleanArray(const KBoolean* _Nonnull elements, KInt length, bool is_data_owner);
    static KBooleanArray* _Nonnull of(std::initializer_list<KBoolean> elements);
    KBooleanArray* _Nonnull clone() const;
    void destroy();
};

struct KByteArray {
    const KByte* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
    
    KByteArray(const KByte* _Nonnull elements, KInt length, bool is_data_owner);
    static KByteArray* _Nonnull of(std::initializer_list<KByte> elements);
    KByteArray* _Nonnull clone() const;
    void destroy();
};

struct KUByteArray {
    const KUByte* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
    
    KUByteArray(const KUByte* _Nonnull elements, KInt length, bool is_data_owner);
    static KUByteArray* _Nonnull of(std::initializer_list<KUByte> elements);
    KUByteArray* _Nonnull clone() const;
    void destroy();
};

struct KShortArray {
    const KShort* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
    
    KShortArray(const KShort* _Nonnull elements, KInt length, bool is_data_owner);
    static KShortArray* _Nonnull of(std::initializer_list<KShort> elements);
    KShortArray* _Nonnull clone() const;
    void destroy();
};

struct KUShortArray {
    const KUShort* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
    
    KUShortArray(const KUShort* _Nonnull elements, KInt length, bool is_data_owner);
    static KUShortArray* _Nonnull of(std::initializer_list<KUShort> elements);
    KUShortArray* _Nonnull clone() const;
    void destroy();
};

struct KIntArray {
    const KInt* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
    
    KIntArray(const KInt* _Nonnull elements, KInt length, bool is_data_owner);
    static KIntArray* _Nonnull of(std::initializer_list<KInt> elements);
    KIntArray* _Nonnull clone() const;
    void destroy();
};

struct KUIntArray {
    const KUInt* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
    
    KUIntArray(const KUInt* _Nonnull elements, KInt length, bool is_data_owner);
    static KUIntArray* _Nonnull of(std::initializer_list<KUInt> elements);
    KUIntArray* _Nonnull clone() const;
    void destroy();
};

struct KLongArray {
    const KLong* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
    
    KLongArray(const KLong* _Nonnull elements, KInt length, bool is_data_owner);
    static KLongArray* _Nonnull of(std::initializer_list<KLong> elements);
    KLongArray* _Nonnull clone() const;
    void destroy();
};

struct KULongArray {
    const KULong* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
    
    KULongArray(const KULong* _Nonnull elements, KInt length, bool is_data_owner);
    static KULongArray* _Nonnull of(std::initializer_list<KULong> elements);
    KULongArray* _Nonnull clone() const;
    void destroy();
};

struct KFloatArray {
    const KFloat* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
    
    KFloatArray(const KFloat* _Nonnull elements, KInt length, bool is_data_owner);
    static KFloatArray* _Nonnull of(std::initializer_list<KFloat> elements);
    KFloatArray* _Nonnull clone() const;
    void destroy();
};

struct KDoubleArray {
    const KDouble* _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
    
    KDoubleArray(const KDouble* _Nonnull elements, KInt length, bool is_data_owner);
    static KDoubleArray* _Nonnull of(std::initializer_list<KDouble> elements);
    KDoubleArray* _Nonnull clone() const;
    void destroy();
};

struct KArray {
    const void* _Nullable * _Nonnull elements;
    size_t size;
    KInt length;
    char __flags;
    
    KArray(const void* _Nullable * _Nonnull elements, KInt length, bool is_data_owner);
    static KArray* _Nonnull of(std::initializer_list<void* _Nullable> elements);
    template <typename T> KArray* _Nullable clone() const;
    template <typename T> void destroy();
};

#define KCallbackDef(Name, Type, ...)                                       \
struct Name {                                                               \
    char __flags;                                                           \
    Type (* _Nonnull invoke)(Name* _Nonnull self, ##__VA_ARGS__);           \
    Name* _Nonnull (* _Nonnull clone)(Name* _Nonnull self);                 \
    KBoolean (* _Nonnull equals)(Name* _Nonnull self, Name* _Nullable obj); \
    KInt (* _Nonnull hash_code)(Name* _Nonnull self);                       \
    void (* _Nonnull free)(Name* _Nullable self);                           \
};


// ╔══════════════════════════╗
// ║     Type definitions     ║
// ╚══════════════════════════╝

struct ParentDictionary;
struct MyDictionary;
struct TypeDictionary;
struct VoidCallback;
struct CallbackPassChar;
struct CallbackPassBoolean;
struct CallbackPassByte;
struct CallbackPassUByte;
struct CallbackPassShort;
struct CallbackPassUShort;
struct CallbackPassInt;
struct CallbackPassUInt;
struct CallbackPassLong;
struct CallbackPassULong;
struct CallbackPassFloat;
struct CallbackPassDouble;
struct CallbackPassString;
struct CallbackPassStringN;
struct CallbackPassCallback;
struct CallbackPassCallbackN;
struct CallbackPassEnum;
struct CallbackPassDictionary;
struct CallbackPassDictionaryN;
struct CallbackReturnChar;
struct CallbackReturnBoolean;
struct CallbackReturnByte;
struct CallbackReturnUByte;
struct CallbackReturnShort;
struct CallbackReturnUShort;
struct CallbackReturnInt;
struct CallbackReturnUInt;
struct CallbackReturnLong;
struct CallbackReturnULong;
struct CallbackReturnFloat;
struct CallbackReturnDouble;
struct CallbackReturnString;
struct CallbackReturnStringN;
struct CallbackReturnCallback;
struct CallbackReturnCallbackN;
struct CallbackReturnEnum;
struct CallbackReturnDictionary;
struct CallbackReturnDictionaryN;
struct CallbackPassCharArray;
struct CallbackPassCharArrayN;
struct CallbackPassBooleanArray;
struct CallbackPassByteArray;
struct CallbackPassUByteArray;
struct CallbackPassShortArray;
struct CallbackPassUShortArray;
struct CallbackPassIntArray;
struct CallbackPassUIntArray;
struct CallbackPassLongArray;
struct CallbackPassULongArray;
struct CallbackPassFloatArray;
struct CallbackPassDoubleArray;
struct CallbackPassStringArray;
struct CallbackPassStringArrayN;
struct CallbackPassEnumArray;
struct CallbackPassDictionaryArray;
struct CallbackPassDictionaryArrayN;
struct CallbackReturnCharArray;
struct CallbackReturnCharArrayN;
struct CallbackReturnBooleanArray;
struct CallbackReturnByteArray;
struct CallbackReturnUByteArray;
struct CallbackReturnShortArray;
struct CallbackReturnUShortArray;
struct CallbackReturnIntArray;
struct CallbackReturnUIntArray;
struct CallbackReturnLongArray;
struct CallbackReturnULongArray;
struct CallbackReturnFloatArray;
struct CallbackReturnDoubleArray;
struct CallbackReturnStringArray;
struct CallbackReturnStringArrayN;
struct CallbackReturnEnumArray;
struct CallbackReturnDictionaryArray;
struct CallbackReturnDictionaryArrayN;
struct IB;
struct IA;


// ╔═══════════════╗
// ║     Enums     ║
// ╚═══════════════╝

enum MyEnum {
	CASE1,
	CASE2
};


// ╔════════════════════╗
// ║     Interfaces     ║
// ╚════════════════════╝

struct IB {
	static IB* _Nonnull _create();
	virtual ~IB() = default;
};

struct IA {
	static IA* _Nonnull _create();
	virtual void test(void* _Nonnull arg) = 0;
	virtual ~IA() = default;
};


// ╔═════════════════╗
// ║     Structs     ║
// ╚═════════════════╝

struct ParentDictionary {
	KInt a;
	KInt b;
	char __flags;

    ParentDictionary(KInt a, KInt b);
    ParentDictionary* _Nullable clone() const;
    void destroy();
};

struct MyDictionary { // : ParentDictionary
	KInt a;
	KInt b;
	KInt c;
	KInt d;
	char __flags;

    MyDictionary(KInt a, KInt b, KInt c, KInt d);
    MyDictionary* _Nullable clone() const;
    void destroy();
};

struct TypeDictionary {
	KChar a1;
	KBoolean a2;
	KByte a3;
	KUByte a4;
	KShort a5;
	KUShort a6;
	KInt a7;
	KUInt a8;
	KLong a9;
	KULong a10;
	KFloat a11;
	KDouble a12;
	KString* _Nonnull a13;
	MyEnum a14;
	MyDictionary* _Nonnull a15;
	VoidCallback* _Nonnull a16;
	KCharArray* _Nonnull a17;
	KBooleanArray* _Nonnull a18;
	KByteArray* _Nonnull a19;
	KUByteArray* _Nonnull a20;
	KShortArray* _Nonnull a21;
	KUShortArray* _Nonnull a22;
	KIntArray* _Nonnull a23;
	KUIntArray* _Nonnull a24;
	KLongArray* _Nonnull a25;
	KULongArray* _Nonnull a26;
	KFloatArray* _Nonnull a27;
	KDoubleArray* _Nonnull a28;
	KArray* _Nonnull a29;
	KIntArray* _Nonnull a30;
	KArray* _Nonnull a31;
	char __flags;

    TypeDictionary(KChar a1, KBoolean a2, KByte a3, KUByte a4, KShort a5, KUShort a6, KInt a7, KUInt a8, KLong a9, KULong a10, KFloat a11, KDouble a12, KString* _Nonnull a13, MyEnum a14, MyDictionary* _Nonnull a15, VoidCallback* _Nonnull a16, KCharArray* _Nonnull a17, KBooleanArray* _Nonnull a18, KByteArray* _Nonnull a19, KUByteArray* _Nonnull a20, KShortArray* _Nonnull a21, KUShortArray* _Nonnull a22, KIntArray* _Nonnull a23, KUIntArray* _Nonnull a24, KLongArray* _Nonnull a25, KULongArray* _Nonnull a26, KFloatArray* _Nonnull a27, KDoubleArray* _Nonnull a28, KArray* _Nonnull a29, KIntArray* _Nonnull a30, KArray* _Nonnull a31);
    TypeDictionary* _Nullable clone() const;
    void destroy();
};


// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

KBoolean pass_void();
KBoolean pass_char(KChar arg);
KBoolean pass_boolean(KBoolean arg);
KBoolean pass_byte(KByte arg);
KBoolean pass_ubyte(KUByte arg);
KBoolean pass_short(KShort arg);
KBoolean pass_ushort(KUShort arg);
KBoolean pass_int(KInt arg);
KBoolean pass_uint(KUInt arg);
KBoolean pass_long(KLong arg);
KBoolean pass_ulong(KULong arg);
KBoolean pass_float(KFloat arg);
KBoolean pass_double(KDouble arg);
KBoolean pass_string(KString* _Nonnull arg);
KBoolean pass_string_n(KString* _Nullable arg);
KBoolean pass_enum(MyEnum arg);
KBoolean pass_dictionary(MyDictionary* _Nonnull arg);
KBoolean pass_dictionary_n(MyDictionary* _Nullable arg);
void return_void();
KChar return_char();
KBoolean return_boolean();
KByte return_byte();
KUByte return_ubyte();
KShort return_short();
KUShort return_ushort();
KInt return_int();
KUInt return_uint();
KLong return_long();
KULong return_ulong();
KFloat return_float();
KDouble return_double();
KString* _Nonnull return_string();
KString* _Nullable return_string_n();
MyEnum return_enum();
MyDictionary* _Nonnull return_dictionary();
MyDictionary* _Nullable return_dictionary_n();
KChar ping_char(KChar arg);
KBoolean ping_boolean(KBoolean arg);
KByte ping_byte(KByte arg);
KUByte ping_ubyte(KUByte arg);
KShort ping_short(KShort arg);
KUShort ping_ushort(KUShort arg);
KInt ping_int(KInt arg);
KUInt ping_uint(KUInt arg);
KLong ping_long(KLong arg);
KULong ping_ulong(KULong arg);
KFloat ping_float(KFloat arg);
KDouble ping_double(KDouble arg);
KString* _Nonnull ping_string(KString* _Nonnull arg);
KString* _Nullable ping_string_n(KString* _Nullable arg);
MyEnum ping_enum(MyEnum arg);
MyDictionary* _Nonnull ping_dictionary(MyDictionary* _Nonnull arg);
MyDictionary* _Nullable ping_dictionary_n(MyDictionary* _Nullable arg);
void callback_void(VoidCallback* _Nonnull arg);
KBoolean callback_void_n(VoidCallback* _Nullable arg);
KBoolean callback_arg_char(CallbackPassChar* _Nonnull arg);
KBoolean callback_arg_boolean(CallbackPassBoolean* _Nonnull arg);
KBoolean callback_arg_byte(CallbackPassByte* _Nonnull arg);
KBoolean callback_arg_ubyte(CallbackPassUByte* _Nonnull arg);
KBoolean callback_arg_short(CallbackPassShort* _Nonnull arg);
KBoolean callback_arg_ushort(CallbackPassUShort* _Nonnull arg);
KBoolean callback_arg_int(CallbackPassInt* _Nonnull arg);
KBoolean callback_arg_uint(CallbackPassUInt* _Nonnull arg);
KBoolean callback_arg_long(CallbackPassLong* _Nonnull arg);
KBoolean callback_arg_ulong(CallbackPassULong* _Nonnull arg);
KBoolean callback_arg_float(CallbackPassFloat* _Nonnull arg);
KBoolean callback_arg_double(CallbackPassDouble* _Nonnull arg);
KBoolean callback_arg_string(CallbackPassString* _Nonnull arg);
KBoolean callback_arg_string_n(CallbackPassStringN* _Nonnull arg);
KBoolean callback_arg_callback(VoidCallback* _Nonnull pass, CallbackPassCallback* _Nonnull arg);
KBoolean callback_arg_callback_n(CallbackPassCallbackN* _Nonnull arg);
KBoolean callback_arg_enum(CallbackPassEnum* _Nonnull arg);
KBoolean callback_arg_dictionary(CallbackPassDictionary* _Nonnull arg);
KBoolean callback_arg_dictionary_n(CallbackPassDictionaryN* _Nonnull arg);
KBoolean callback_return_char(CallbackReturnChar* _Nonnull arg);
KBoolean callback_return_boolean(CallbackReturnBoolean* _Nonnull arg);
KBoolean callback_return_byte(CallbackReturnByte* _Nonnull arg);
KBoolean callback_return_ubyte(CallbackReturnUByte* _Nonnull arg);
KBoolean callback_return_short(CallbackReturnShort* _Nonnull arg);
KBoolean callback_return_ushort(CallbackReturnUShort* _Nonnull arg);
KBoolean callback_return_int(CallbackReturnInt* _Nonnull arg);
KBoolean callback_return_uint(CallbackReturnUInt* _Nonnull arg);
KBoolean callback_return_long(CallbackReturnLong* _Nonnull arg);
KBoolean callback_return_ulong(CallbackReturnULong* _Nonnull arg);
KBoolean callback_return_float(CallbackReturnFloat* _Nonnull arg);
KBoolean callback_return_double(CallbackReturnDouble* _Nonnull arg);
KBoolean callback_return_string(CallbackReturnString* _Nonnull arg);
KBoolean callback_return_string_n(CallbackReturnStringN* _Nonnull arg);
VoidCallback* _Nonnull callback_return_callback(CallbackReturnCallback* _Nonnull arg);
KBoolean callback_return_callback_n(CallbackReturnCallbackN* _Nonnull arg);
KBoolean callback_return_enum(CallbackReturnEnum* _Nonnull arg);
KBoolean callback_return_dictionary(CallbackReturnDictionary* _Nonnull arg);
KBoolean callback_return_dictionary_n(CallbackReturnDictionaryN* _Nonnull arg);
KBoolean pass_char_array(KCharArray* _Nonnull arg);
KBoolean pass_char_array_n(KCharArray* _Nullable arg);
KBoolean pass_boolean_array(KBooleanArray* _Nonnull arg);
KBoolean pass_byte_array(KByteArray* _Nonnull arg);
KBoolean pass_ubyte_array(KUByteArray* _Nonnull arg);
KBoolean pass_short_array(KShortArray* _Nonnull arg);
KBoolean pass_ushort_array(KUShortArray* _Nonnull arg);
KBoolean pass_int_array(KIntArray* _Nonnull arg);
KBoolean pass_uint_array(KUIntArray* _Nonnull arg);
KBoolean pass_long_array(KLongArray* _Nonnull arg);
KBoolean pass_ulong_array(KULongArray* _Nonnull arg);
KBoolean pass_float_array(KFloatArray* _Nonnull arg);
KBoolean pass_double_array(KDoubleArray* _Nonnull arg);
KBoolean pass_string_array(KArray* _Nonnull arg);
KBoolean pass_string_array_n(KArray* _Nonnull arg);
KBoolean pass_enum_array(KIntArray* _Nonnull arg);
KBoolean pass_dictionary_array(KArray* _Nonnull arg);
KBoolean pass_dictionary_array_n(KArray* _Nonnull arg);
KCharArray* _Nonnull return_char_array();
KCharArray* _Nullable return_char_array_n();
KBooleanArray* _Nonnull return_boolean_array();
KByteArray* _Nonnull return_byte_array();
KUByteArray* _Nonnull return_ubyte_array();
KShortArray* _Nonnull return_short_array();
KUShortArray* _Nonnull return_ushort_array();
KIntArray* _Nonnull return_int_array();
KUIntArray* _Nonnull return_uint_array();
KLongArray* _Nonnull return_long_array();
KULongArray* _Nonnull return_ulong_array();
KFloatArray* _Nonnull return_float_array();
KDoubleArray* _Nonnull return_double_array();
KArray* _Nonnull return_string_array();
KArray* _Nonnull return_string_array_n();
KIntArray* _Nonnull return_enum_array();
KArray* _Nonnull return_dictionary_array();
KArray* _Nonnull return_dictionary_array_n();
KCharArray* _Nonnull ping_char_array(KCharArray* _Nonnull arg);
KCharArray* _Nullable ping_char_array_n(KCharArray* _Nullable arg);
KBooleanArray* _Nonnull ping_boolean_array(KBooleanArray* _Nonnull arg);
KByteArray* _Nonnull ping_byte_array(KByteArray* _Nonnull arg);
KUByteArray* _Nonnull ping_ubyte_array(KUByteArray* _Nonnull arg);
KShortArray* _Nonnull ping_short_array(KShortArray* _Nonnull arg);
KUShortArray* _Nonnull ping_ushort_array(KUShortArray* _Nonnull arg);
KIntArray* _Nonnull ping_int_array(KIntArray* _Nonnull arg);
KUIntArray* _Nonnull ping_uint_array(KUIntArray* _Nonnull arg);
KLongArray* _Nonnull ping_long_array(KLongArray* _Nonnull arg);
KULongArray* _Nonnull ping_ulong_array(KULongArray* _Nonnull arg);
KFloatArray* _Nonnull ping_float_array(KFloatArray* _Nonnull arg);
KDoubleArray* _Nonnull ping_double_array(KDoubleArray* _Nonnull arg);
KArray* _Nonnull ping_string_array(KArray* _Nonnull arg);
KArray* _Nonnull ping_string_array_n(KArray* _Nonnull arg);
KIntArray* _Nonnull ping_enum_array(KIntArray* _Nonnull arg);
KArray* _Nonnull ping_dictionary_array(KArray* _Nonnull arg);
KArray* _Nonnull ping_dictionary_array_n(KArray* _Nonnull arg);
KBoolean callback_arg_char_array(CallbackPassCharArray* _Nonnull arg);
KBoolean callback_arg_char_array_n(CallbackPassCharArrayN* _Nonnull arg);
KBoolean callback_arg_boolean_array(CallbackPassBooleanArray* _Nonnull arg);
KBoolean callback_arg_byte_array(CallbackPassByteArray* _Nonnull arg);
KBoolean callback_arg_ubyte_array(CallbackPassUByteArray* _Nonnull arg);
KBoolean callback_arg_short_array(CallbackPassShortArray* _Nonnull arg);
KBoolean callback_arg_ushort_array(CallbackPassUShortArray* _Nonnull arg);
KBoolean callback_arg_int_array(CallbackPassIntArray* _Nonnull arg);
KBoolean callback_arg_uint_array(CallbackPassUIntArray* _Nonnull arg);
KBoolean callback_arg_long_array(CallbackPassLongArray* _Nonnull arg);
KBoolean callback_arg_ulong_array(CallbackPassULongArray* _Nonnull arg);
KBoolean callback_arg_float_array(CallbackPassFloatArray* _Nonnull arg);
KBoolean callback_arg_double_array(CallbackPassDoubleArray* _Nonnull arg);
KBoolean callback_arg_string_array(CallbackPassStringArray* _Nonnull arg);
KBoolean callback_arg_string_array_n(CallbackPassStringArrayN* _Nonnull arg);
KBoolean callback_arg_enum_array(CallbackPassEnumArray* _Nonnull arg);
KBoolean callback_arg_dictionary_array(CallbackPassDictionaryArray* _Nonnull arg);
KBoolean callback_arg_dictionary_array_n(CallbackPassDictionaryArrayN* _Nonnull arg);
KBoolean callback_return_char_array(CallbackReturnCharArray* _Nonnull arg);
KBoolean callback_return_char_array_n(CallbackReturnCharArrayN* _Nonnull arg);
KBoolean callback_return_boolean_array(CallbackReturnBooleanArray* _Nonnull arg);
KBoolean callback_return_byte_array(CallbackReturnByteArray* _Nonnull arg);
KBoolean callback_return_ubyte_array(CallbackReturnUByteArray* _Nonnull arg);
KBoolean callback_return_short_array(CallbackReturnShortArray* _Nonnull arg);
KBoolean callback_return_ushort_array(CallbackReturnUShortArray* _Nonnull arg);
KBoolean callback_return_int_array(CallbackReturnIntArray* _Nonnull arg);
KBoolean callback_return_uint_array(CallbackReturnUIntArray* _Nonnull arg);
KBoolean callback_return_long_array(CallbackReturnLongArray* _Nonnull arg);
KBoolean callback_return_ulong_array(CallbackReturnULongArray* _Nonnull arg);
KBoolean callback_return_float_array(CallbackReturnFloatArray* _Nonnull arg);
KBoolean callback_return_double_array(CallbackReturnDoubleArray* _Nonnull arg);
KBoolean callback_return_string_array(CallbackReturnStringArray* _Nonnull arg);
KBoolean callback_return_string_array_n(CallbackReturnStringArrayN* _Nonnull arg);
KBoolean callback_return_enum_array(CallbackReturnEnumArray* _Nonnull arg);
KBoolean callback_return_dictionary_array(CallbackReturnDictionaryArray* _Nonnull arg);
KBoolean callback_return_dictionary_array_n(CallbackReturnDictionaryArrayN* _Nonnull arg);
KBoolean pass_big_dictionary(TypeDictionary* _Nonnull arg);
TypeDictionary* _Nonnull return_big_dictionary(VoidCallback* _Nonnull callback);
TypeDictionary* _Nonnull ping_big_dictionary(TypeDictionary* _Nonnull arg);
KBoolean pass_big_dictionary_n(TypeDictionary* _Nullable arg);
TypeDictionary* _Nullable return_big_dictionary_n();
TypeDictionary* _Nullable ping_big_dictionary_n(TypeDictionary* _Nullable arg);
KBoolean critical_primitives(KChar a1, KBoolean a2, KByte a3, KUByte a4, KShort a5, KUShort a6, KInt a7, KUInt a8, KLong a9, KULong a10, KFloat a11, KDouble a12);
KBoolean critical_enum(MyEnum a1);
KBoolean critical_string(KString* _Nonnull a1);
KBoolean critical_string_n(KString* _Nullable a1);
KBoolean critical_primitives_array(KCharArray* _Nonnull a1, KBooleanArray* _Nonnull a2, KByteArray* _Nonnull a3, KUByteArray* _Nonnull a4, KShortArray* _Nonnull a5, KUShortArray* _Nonnull a6, KIntArray* _Nonnull a7, KUIntArray* _Nonnull a8, KLongArray* _Nonnull a9, KULongArray* _Nonnull a10, KFloatArray* _Nonnull a11, KDoubleArray* _Nonnull a12);
KBoolean critical_enum_array(KIntArray* _Nonnull a1);
KBoolean critical_primitives_array_n(KCharArray* _Nullable a1, KBooleanArray* _Nullable a2, KByteArray* _Nullable a3, KUByteArray* _Nullable a4, KShortArray* _Nullable a5, KUShortArray* _Nullable a6, KIntArray* _Nullable a7, KUIntArray* _Nullable a8, KLongArray* _Nullable a9, KULongArray* _Nullable a10, KFloatArray* _Nullable a11, KDoubleArray* _Nullable a12);
KBoolean critical_enum_array_n(KIntArray* _Nullable a1);
KChar critical_return_char();
KBoolean critical_return_boolean();
KByte critical_return_byte();
KUByte critical_return_ubyte();
KShort critical_return_short();
KUShort critical_return_ushort();
KInt critical_return_int();
KUInt critical_return_uint();
KLong critical_return_long();
KULong critical_return_ulong();
KFloat critical_return_float();
KDouble critical_return_double();
MyEnum critical_return_enum();
KBoolean jvmci1();
KBoolean jvmci2(KInt a1);
KBoolean jvmci3(KInt a1, KInt a2);
KBoolean jvmci4(KInt a1, KInt a2, KInt a3, KInt a4, KInt a5, KInt a6, KInt a7, KInt a8, KInt a9);
KBoolean jvmci5(KInt a1, KLong a2, KInt a3, KLong a4, KInt a5, KLong a6, KInt a7, KInt a8, KLong a9);
KBoolean jvmci6(KFloat a1, KFloat a2, KFloat a3, KFloat a4, KFloat a5, KFloat a6, KFloat a7, KFloat a8, KFloat a9, KInt a10, KInt a11, KInt a12, KInt a13);
KBoolean jvmci7(KFloat a1, KDouble a2, KFloat a3, KDouble a4, KFloat a5, KDouble a6, KFloat a7, KFloat a8, KDouble a9);
KBoolean jvmci8(KInt a1, KDouble a2, KFloat a3, KLong a4);
KBoolean jvmci9(KInt a1, KDouble a2, KFloat a3, KLong a4, KLong a5, KDouble a6, KFloat a7, KFloat a8, KInt a9);
KBoolean jvmci10(KString* _Nonnull a1, KDouble a2, KFloat a3, KLong a4, KLong a5, KDouble a6, KString* _Nonnull a7, KFloat a8, KInt a9);
KBoolean jvmci11(KFloat a1, KInt a2, KFloat a3, KInt a4, KFloat a5, KInt a6, KFloat a7, KInt a8, KFloat a9, KInt a10, KFloat a11, KInt a12, KFloat a13, KInt a14, KFloat a15, KInt a16, KFloat a17);
KInt jvmci12();
KLong jvmci13();
KFloat jvmci14();
KDouble jvmci15();
KBoolean jvmci_array(KIntArray* _Nonnull array);
KBoolean jvmci_some_arrays(KIntArray* _Nonnull array1, KFloatArray* _Nonnull array2, KDoubleArray* _Nonnull array3);
KBoolean jvmci_enum(MyEnum enum1, MyEnum enum2, KIntArray* _Nonnull enum_array);

// ╔═══════════════════╗
// ║     Callbacks     ║
// ╚═══════════════════╝
// ┌───────┬───────────────────────────────┬───────────────────────┬────────────────────────────┐
// │  ...  │ Name                          │ Type                  │ Args                       │
// └───────┴───────────────────────────────┴───────────────────────┴────────────────────────────┘
KCallbackDef(VoidCallback,                   void                                               )
KCallbackDef(CallbackPassChar,               KBoolean,               KChar arg                  )
KCallbackDef(CallbackPassBoolean,            KBoolean,               KBoolean arg               )
KCallbackDef(CallbackPassByte,               KBoolean,               KByte arg                  )
KCallbackDef(CallbackPassUByte,              KBoolean,               KUByte arg                 )
KCallbackDef(CallbackPassShort,              KBoolean,               KShort arg                 )
KCallbackDef(CallbackPassUShort,             KBoolean,               KUShort arg                )
KCallbackDef(CallbackPassInt,                KBoolean,               KInt arg                   )
KCallbackDef(CallbackPassUInt,               KBoolean,               KUInt arg                  )
KCallbackDef(CallbackPassLong,               KBoolean,               KLong arg                  )
KCallbackDef(CallbackPassULong,              KBoolean,               KULong arg                 )
KCallbackDef(CallbackPassFloat,              KBoolean,               KFloat arg                 )
KCallbackDef(CallbackPassDouble,             KBoolean,               KDouble arg                )
KCallbackDef(CallbackPassString,             KBoolean,               KString* _Nonnull arg      )
KCallbackDef(CallbackPassStringN,            KBoolean,               KString* _Nullable arg     )
KCallbackDef(CallbackPassCallback,           KBoolean,               VoidCallback* _Nonnull arg )
KCallbackDef(CallbackPassCallbackN,          KBoolean,               VoidCallback* _Nullable arg)
KCallbackDef(CallbackPassEnum,               KBoolean,               MyEnum arg                 )
KCallbackDef(CallbackPassDictionary,         KBoolean,               MyDictionary* _Nonnull arg )
KCallbackDef(CallbackPassDictionaryN,        KBoolean,               MyDictionary* _Nullable arg)
KCallbackDef(CallbackReturnChar,             KChar                                              )
KCallbackDef(CallbackReturnBoolean,          KBoolean                                           )
KCallbackDef(CallbackReturnByte,             KByte                                              )
KCallbackDef(CallbackReturnUByte,            KUByte                                             )
KCallbackDef(CallbackReturnShort,            KShort                                             )
KCallbackDef(CallbackReturnUShort,           KUShort                                            )
KCallbackDef(CallbackReturnInt,              KInt                                               )
KCallbackDef(CallbackReturnUInt,             KUInt                                              )
KCallbackDef(CallbackReturnLong,             KLong                                              )
KCallbackDef(CallbackReturnULong,            KULong                                             )
KCallbackDef(CallbackReturnFloat,            KFloat                                             )
KCallbackDef(CallbackReturnDouble,           KDouble                                            )
KCallbackDef(CallbackReturnString,           KString* _Nonnull                                  )
KCallbackDef(CallbackReturnStringN,          KString* _Nullable                                 )
KCallbackDef(CallbackReturnCallback,         VoidCallback* _Nonnull                             )
KCallbackDef(CallbackReturnCallbackN,        VoidCallback* _Nullable                            )
KCallbackDef(CallbackReturnEnum,             MyEnum                                             )
KCallbackDef(CallbackReturnDictionary,       MyDictionary* _Nonnull                             )
KCallbackDef(CallbackReturnDictionaryN,      MyDictionary* _Nullable                            )
KCallbackDef(CallbackPassCharArray,          KBoolean,               KCharArray* _Nonnull arg   )
KCallbackDef(CallbackPassCharArrayN,         KBoolean,               KCharArray* _Nullable arg  )
KCallbackDef(CallbackPassBooleanArray,       KBoolean,               KBooleanArray* _Nonnull arg)
KCallbackDef(CallbackPassByteArray,          KBoolean,               KByteArray* _Nonnull arg   )
KCallbackDef(CallbackPassUByteArray,         KBoolean,               KUByteArray* _Nonnull arg  )
KCallbackDef(CallbackPassShortArray,         KBoolean,               KShortArray* _Nonnull arg  )
KCallbackDef(CallbackPassUShortArray,        KBoolean,               KUShortArray* _Nonnull arg )
KCallbackDef(CallbackPassIntArray,           KBoolean,               KIntArray* _Nonnull arg    )
KCallbackDef(CallbackPassUIntArray,          KBoolean,               KUIntArray* _Nonnull arg   )
KCallbackDef(CallbackPassLongArray,          KBoolean,               KLongArray* _Nonnull arg   )
KCallbackDef(CallbackPassULongArray,         KBoolean,               KULongArray* _Nonnull arg  )
KCallbackDef(CallbackPassFloatArray,         KBoolean,               KFloatArray* _Nonnull arg  )
KCallbackDef(CallbackPassDoubleArray,        KBoolean,               KDoubleArray* _Nonnull arg )
KCallbackDef(CallbackPassStringArray,        KBoolean,               KArray* _Nonnull arg       )
KCallbackDef(CallbackPassStringArrayN,       KBoolean,               KArray* _Nonnull arg       )
KCallbackDef(CallbackPassEnumArray,          KBoolean,               KIntArray* _Nonnull arg    )
KCallbackDef(CallbackPassDictionaryArray,    KBoolean,               KArray* _Nonnull arg       )
KCallbackDef(CallbackPassDictionaryArrayN,   KBoolean,               KArray* _Nonnull arg       )
KCallbackDef(CallbackReturnCharArray,        KCharArray* _Nonnull                               )
KCallbackDef(CallbackReturnCharArrayN,       KCharArray* _Nullable                              )
KCallbackDef(CallbackReturnBooleanArray,     KBooleanArray* _Nonnull                            )
KCallbackDef(CallbackReturnByteArray,        KByteArray* _Nonnull                               )
KCallbackDef(CallbackReturnUByteArray,       KUByteArray* _Nonnull                              )
KCallbackDef(CallbackReturnShortArray,       KShortArray* _Nonnull                              )
KCallbackDef(CallbackReturnUShortArray,      KUShortArray* _Nonnull                             )
KCallbackDef(CallbackReturnIntArray,         KIntArray* _Nonnull                                )
KCallbackDef(CallbackReturnUIntArray,        KUIntArray* _Nonnull                               )
KCallbackDef(CallbackReturnLongArray,        KLongArray* _Nonnull                               )
KCallbackDef(CallbackReturnULongArray,       KULongArray* _Nonnull                              )
KCallbackDef(CallbackReturnFloatArray,       KFloatArray* _Nonnull                              )
KCallbackDef(CallbackReturnDoubleArray,      KDoubleArray* _Nonnull                             )
KCallbackDef(CallbackReturnStringArray,      KArray* _Nonnull                                   )
KCallbackDef(CallbackReturnStringArrayN,     KArray* _Nonnull                                   )
KCallbackDef(CallbackReturnEnumArray,        KIntArray* _Nonnull                                )
KCallbackDef(CallbackReturnDictionaryArray,  KArray* _Nonnull                                   )
KCallbackDef(CallbackReturnDictionaryArrayN, KArray* _Nonnull                                   )
#undef KCallbackDef
