/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */

#pragma once

#include <memory>
#include <string>
#include <cstring>

// ╔═══════════════╗
// ║     Types     ║
// ╚═══════════════╝

template <typename T> class KOptional {
    bool is_empty;
    alignas(T) unsigned char storage[sizeof(T)];
public:
    KOptional();
    explicit KOptional(const T& value);
    explicit KOptional(T&& value);
    ~KOptional();
    KOptional(const KOptional&);
    KOptional& operator=(const KOptional&);
    KOptional(KOptional&&) noexcept;
    KOptional& operator=(KOptional&&) noexcept;
    T& operator*() &;
    T&& operator*() &&;
    bool is_none() const;
    T* _Nullable get_ptr();
    const T* _Nullable get_ptr() const;
};
class KString {
    char* _Nonnull data;
    size_t size;
public:
    explicit KString(const char* _Nonnull data, size_t size, bool copy = true);
    explicit KString(const char* _Nonnull data, bool copy = true);
    KString(const KString& other);
    KString(KString&& other) noexcept;
    KString& operator=(KString&& other) noexcept;
    ~KString();
    std::string* _Nonnull to_string() const;
    const char* _Nonnull get_data() const;
    int32_t get_length() const;
    size_t get_size() const;
    explicit operator const char* _Nonnull() const;
};
template <typename T> class KArray {
    T* _Nonnull elements;
    int32_t length;
    int32_t capacity;
public:
    explicit KArray(int32_t capacity);
    explicit KArray(T* _Nonnull elements, int32_t length, bool copy = true);
    explicit KArray(std::initializer_list<T> elements);
    KArray(const KArray& other);
    KArray(KArray&& other) noexcept;
    KArray& operator=(KArray&& other) noexcept;
    ~KArray();
    explicit operator const T* _Nonnull () const;
    const T& operator[](size_t index) const;
    void push(T&& element);
    T& get(int32_t index);
    const T* _Nonnull get_elements();
    int32_t get_length() const;
};

// ╔══════════════════════════╗
// ║     Type definitions     ║
// ╚══════════════════════════╝

struct ParentDictionary;
struct MyDictionary;
struct TypeDictionary;
struct CallbackPassBoolean;
struct CallbackPassBooleanArray;
struct CallbackPassByte;
struct CallbackPassByteArray;
struct CallbackPassCallback;
struct CallbackPassCallbackN;
struct CallbackPassChar;
struct CallbackPassCharArray;
struct CallbackPassCharArrayN;
struct CallbackPassDictionary;
struct CallbackPassDictionaryArray;
struct CallbackPassDictionaryArrayN;
struct CallbackPassDictionaryN;
struct CallbackPassDouble;
struct CallbackPassDoubleArray;
struct CallbackPassEnum;
struct CallbackPassEnumArray;
struct CallbackPassFloat;
struct CallbackPassFloatArray;
struct CallbackPassInt;
struct CallbackPassIntArray;
struct CallbackPassInterface;
struct CallbackPassInterfaceArray;
struct CallbackPassInterfaceArrayN;
struct CallbackPassInterfaceN;
struct CallbackPassLong;
struct CallbackPassLongArray;
struct CallbackPassShort;
struct CallbackPassShortArray;
struct CallbackPassString;
struct CallbackPassStringArray;
struct CallbackPassStringArrayN;
struct CallbackPassStringN;
struct CallbackPassUByte;
struct CallbackPassUByteArray;
struct CallbackPassUInt;
struct CallbackPassUIntArray;
struct CallbackPassULong;
struct CallbackPassULongArray;
struct CallbackPassUShort;
struct CallbackPassUShortArray;
struct CallbackReturnBoolean;
struct CallbackReturnBooleanArray;
struct CallbackReturnByte;
struct CallbackReturnByteArray;
struct CallbackReturnCallback;
struct CallbackReturnCallbackN;
struct CallbackReturnChar;
struct CallbackReturnCharArray;
struct CallbackReturnCharArrayN;
struct CallbackReturnDictionary;
struct CallbackReturnDictionaryArray;
struct CallbackReturnDictionaryArrayN;
struct CallbackReturnDictionaryN;
struct CallbackReturnDouble;
struct CallbackReturnDoubleArray;
struct CallbackReturnEnum;
struct CallbackReturnEnumArray;
struct CallbackReturnFloat;
struct CallbackReturnFloatArray;
struct CallbackReturnInt;
struct CallbackReturnIntArray;
struct CallbackReturnInterface;
struct CallbackReturnInterfaceArray;
struct CallbackReturnInterfaceArrayN;
struct CallbackReturnInterfaceN;
struct CallbackReturnLong;
struct CallbackReturnLongArray;
struct CallbackReturnShort;
struct CallbackReturnShortArray;
struct CallbackReturnString;
struct CallbackReturnStringArray;
struct CallbackReturnStringArrayN;
struct CallbackReturnStringN;
struct CallbackReturnUByte;
struct CallbackReturnUByteArray;
struct CallbackReturnUInt;
struct CallbackReturnUIntArray;
struct CallbackReturnULong;
struct CallbackReturnULongArray;
struct CallbackReturnUShort;
struct CallbackReturnUShortArray;
struct VoidCallback;
struct IMyInterface;

// ╔═══════════════╗
// ║     Enums     ║
// ╚═══════════════╝

enum MyEnum {
	CASE1, 
	CASE2
};

// ╔════════════════════╗
// ║     Interfaces     ║
// ╚════════════════════╝

struct IMyInterface {
	static IMyInterface* _Nonnull _create();
	static IMyInterface* _Nonnull new_critical(int32_t a);
	virtual bool test() = 0;
	virtual bool test_critical() = 0;
	virtual void pass_interface(std::shared_ptr<IMyInterface> a1) = 0;
	virtual std::shared_ptr<IMyInterface> return_interface() = 0;
	virtual ~IMyInterface() = default;
};

// ╔═══════════════════╗
// ║     Callbacks     ║
// ╚═══════════════════╝

#define KCallbackDef(Name, Type, ...)             \
class Name {                                      \
    void* _Nonnull _invoke;                       \
    bool (* _Nonnull _equals)(size_t, size_t);    \
    void (* _Nonnull _free)(size_t);              \
public:                                           \
    size_t id;                                    \
	int32_t hash_code;                               \
	~Name();                                      \
    Name(                                         \
        size_t id,                                \
        int32_t hash_code,                           \
        void* _Nonnull invoke,                    \
        bool (* _Nonnull equals)(size_t, size_t), \
        void (* _Nonnull free)(size_t)            \
    );                                            \
    Name(const Name&) = delete;                   \
    Name& operator=(const Name&) = delete;        \
    Name(Name&&) noexcept = delete;               \
    Name& operator=(Name&&) noexcept = delete;    \
                                                  \
    bool operator==(const Name& other) const;     \
    Type invoke(__VA_ARGS__) const;               \
};

KCallbackDef(CallbackPassBoolean, bool, bool arg)
KCallbackDef(CallbackPassBooleanArray, bool, KArray<bool> arg)
KCallbackDef(CallbackPassByte, bool, int8_t arg)
KCallbackDef(CallbackPassByteArray, bool, KArray<int8_t> arg)
KCallbackDef(CallbackPassCallback, bool, std::shared_ptr<VoidCallback> arg)
KCallbackDef(CallbackPassCallbackN, bool, KOptional<std::shared_ptr<VoidCallback>> arg)
KCallbackDef(CallbackPassChar, bool, uint16_t arg)
KCallbackDef(CallbackPassCharArray, bool, KArray<uint16_t> arg)
KCallbackDef(CallbackPassCharArrayN, bool, KOptional<KArray<uint16_t>> arg)
KCallbackDef(CallbackPassDictionary, bool, MyDictionary arg)
KCallbackDef(CallbackPassDictionaryArray, bool, KArray<MyDictionary> arg)
KCallbackDef(CallbackPassDictionaryArrayN, bool, KArray<KOptional<MyDictionary>> arg)
KCallbackDef(CallbackPassDictionaryN, bool, KOptional<MyDictionary> arg)
KCallbackDef(CallbackPassDouble, bool, double arg)
KCallbackDef(CallbackPassDoubleArray, bool, KArray<double> arg)
KCallbackDef(CallbackPassEnum, bool, MyEnum arg)
KCallbackDef(CallbackPassEnumArray, bool, KArray<MyEnum> arg)
KCallbackDef(CallbackPassFloat, bool, float arg)
KCallbackDef(CallbackPassFloatArray, bool, KArray<float> arg)
KCallbackDef(CallbackPassInt, bool, int32_t arg)
KCallbackDef(CallbackPassIntArray, bool, KArray<int32_t> arg)
KCallbackDef(CallbackPassInterface, bool, std::shared_ptr<IMyInterface> arg)
KCallbackDef(CallbackPassInterfaceArray, bool, KArray<std::shared_ptr<IMyInterface>> arg)
KCallbackDef(CallbackPassInterfaceArrayN, bool, KArray<KOptional<std::shared_ptr<IMyInterface>>> arg)
KCallbackDef(CallbackPassInterfaceN, bool, KOptional<std::shared_ptr<IMyInterface>> arg)
KCallbackDef(CallbackPassLong, bool, int64_t arg)
KCallbackDef(CallbackPassLongArray, bool, KArray<int64_t> arg)
KCallbackDef(CallbackPassShort, bool, int16_t arg)
KCallbackDef(CallbackPassShortArray, bool, KArray<int16_t> arg)
KCallbackDef(CallbackPassString, bool, KString arg)
KCallbackDef(CallbackPassStringArray, bool, KArray<KString> arg)
KCallbackDef(CallbackPassStringArrayN, bool, KArray<KOptional<KString>> arg)
KCallbackDef(CallbackPassStringN, bool, KOptional<KString> arg)
KCallbackDef(CallbackPassUByte, bool, uint8_t arg)
KCallbackDef(CallbackPassUByteArray, bool, KArray<uint8_t> arg)
KCallbackDef(CallbackPassUInt, bool, uint32_t arg)
KCallbackDef(CallbackPassUIntArray, bool, KArray<uint32_t> arg)
KCallbackDef(CallbackPassULong, bool, uint64_t arg)
KCallbackDef(CallbackPassULongArray, bool, KArray<uint64_t> arg)
KCallbackDef(CallbackPassUShort, bool, uint16_t arg)
KCallbackDef(CallbackPassUShortArray, bool, KArray<uint16_t> arg)
KCallbackDef(CallbackReturnBoolean, bool)
KCallbackDef(CallbackReturnBooleanArray, KArray<bool>)
KCallbackDef(CallbackReturnByte, int8_t)
KCallbackDef(CallbackReturnByteArray, KArray<int8_t>)
KCallbackDef(CallbackReturnCallback, std::shared_ptr<VoidCallback>)
KCallbackDef(CallbackReturnCallbackN, KOptional<std::shared_ptr<VoidCallback>>)
KCallbackDef(CallbackReturnChar, uint16_t)
KCallbackDef(CallbackReturnCharArray, KArray<uint16_t>)
KCallbackDef(CallbackReturnCharArrayN, KOptional<KArray<uint16_t>>)
KCallbackDef(CallbackReturnDictionary, MyDictionary)
KCallbackDef(CallbackReturnDictionaryArray, KArray<MyDictionary>)
KCallbackDef(CallbackReturnDictionaryArrayN, KArray<KOptional<MyDictionary>>)
KCallbackDef(CallbackReturnDictionaryN, KOptional<MyDictionary>)
KCallbackDef(CallbackReturnDouble, double)
KCallbackDef(CallbackReturnDoubleArray, KArray<double>)
KCallbackDef(CallbackReturnEnum, MyEnum)
KCallbackDef(CallbackReturnEnumArray, KArray<MyEnum>)
KCallbackDef(CallbackReturnFloat, float)
KCallbackDef(CallbackReturnFloatArray, KArray<float>)
KCallbackDef(CallbackReturnInt, int32_t)
KCallbackDef(CallbackReturnIntArray, KArray<int32_t>)
KCallbackDef(CallbackReturnInterface, std::shared_ptr<IMyInterface>)
KCallbackDef(CallbackReturnInterfaceArray, KArray<std::shared_ptr<IMyInterface>>)
KCallbackDef(CallbackReturnInterfaceArrayN, KArray<KOptional<std::shared_ptr<IMyInterface>>>)
KCallbackDef(CallbackReturnInterfaceN, KOptional<std::shared_ptr<IMyInterface>>)
KCallbackDef(CallbackReturnLong, int64_t)
KCallbackDef(CallbackReturnLongArray, KArray<int64_t>)
KCallbackDef(CallbackReturnShort, int16_t)
KCallbackDef(CallbackReturnShortArray, KArray<int16_t>)
KCallbackDef(CallbackReturnString, KString)
KCallbackDef(CallbackReturnStringArray, KArray<KString>)
KCallbackDef(CallbackReturnStringArrayN, KArray<KOptional<KString>>)
KCallbackDef(CallbackReturnStringN, KOptional<KString>)
KCallbackDef(CallbackReturnUByte, uint8_t)
KCallbackDef(CallbackReturnUByteArray, KArray<uint8_t>)
KCallbackDef(CallbackReturnUInt, uint32_t)
KCallbackDef(CallbackReturnUIntArray, KArray<uint32_t>)
KCallbackDef(CallbackReturnULong, uint64_t)
KCallbackDef(CallbackReturnULongArray, KArray<uint64_t>)
KCallbackDef(CallbackReturnUShort, uint16_t)
KCallbackDef(CallbackReturnUShortArray, KArray<uint16_t>)
KCallbackDef(VoidCallback, void)

// ╔═════════════════╗
// ║     Structs     ║
// ╚═════════════════╝

struct ParentDictionary {
	int32_t a;
	int32_t b;    
    ParentDictionary(int32_t a, int32_t b);
    ParentDictionary(const ParentDictionary& other);
};

struct MyDictionary : ParentDictionary {
	int32_t c;
	int32_t d;    
    MyDictionary(int32_t a, int32_t b, int32_t c, int32_t d);
    MyDictionary(const MyDictionary& other);
};

struct TypeDictionary {
	uint16_t a1;
	bool a2;
	int8_t a3;
	uint8_t a4;
	int16_t a5;
	uint16_t a6;
	int32_t a7;
	uint32_t a8;
	int64_t a9;
	uint64_t a10;
	float a11;
	double a12;
	KString a13;
	MyEnum a14;
	MyDictionary a15;
	KOptional<MyDictionary> a16;
	std::shared_ptr<IMyInterface> a17;
	KOptional<std::shared_ptr<IMyInterface>> a18;
	std::shared_ptr<VoidCallback> a19;
	KArray<uint16_t> a20;
	KArray<bool> a21;
	KArray<int8_t> a22;
	KArray<uint8_t> a23;
	KArray<int16_t> a24;
	KArray<uint16_t> a25;
	KArray<int32_t> a26;
	KArray<uint32_t> a27;
	KArray<int64_t> a28;
	KArray<uint64_t> a29;
	KArray<float> a30;
	KArray<double> a31;
	KArray<KString> a32;
	KArray<MyEnum> a33;
	KArray<MyDictionary> a34;
	KArray<std::shared_ptr<IMyInterface>> a35;    
    TypeDictionary(uint16_t a1, bool a2, int8_t a3, uint8_t a4, int16_t a5, uint16_t a6, int32_t a7, uint32_t a8, int64_t a9, uint64_t a10, float a11, double a12, KString a13, MyEnum a14, MyDictionary a15, KOptional<MyDictionary> a16, std::shared_ptr<IMyInterface> a17, KOptional<std::shared_ptr<IMyInterface>> a18, std::shared_ptr<VoidCallback> a19, KArray<uint16_t> a20, KArray<bool> a21, KArray<int8_t> a22, KArray<uint8_t> a23, KArray<int16_t> a24, KArray<uint16_t> a25, KArray<int32_t> a26, KArray<uint32_t> a27, KArray<int64_t> a28, KArray<uint64_t> a29, KArray<float> a30, KArray<double> a31, KArray<KString> a32, KArray<MyEnum> a33, KArray<MyDictionary> a34, KArray<std::shared_ptr<IMyInterface>> a35);
    TypeDictionary(const TypeDictionary& other);
};

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

bool pass_void();
bool pass_char(uint16_t arg);
bool pass_boolean(bool arg);
bool pass_byte(int8_t arg);
bool pass_ubyte(uint8_t arg);
bool pass_short(int16_t arg);
bool pass_ushort(uint16_t arg);
bool pass_int(int32_t arg);
bool pass_uint(uint32_t arg);
bool pass_long(int64_t arg);
bool pass_ulong(uint64_t arg);
bool pass_float(float arg);
bool pass_double(double arg);
bool pass_string(KString arg);
bool pass_string_n(KOptional<KString> arg);
bool pass_enum(MyEnum arg);
bool pass_dictionary(MyDictionary arg);
bool pass_dictionary_n(KOptional<MyDictionary> arg);
bool pass_interface(std::shared_ptr<IMyInterface> arg);
bool pass_interface_n(KOptional<std::shared_ptr<IMyInterface>> arg);
void return_void();
uint16_t return_char();
bool return_boolean();
int8_t return_byte();
uint8_t return_ubyte();
int16_t return_short();
uint16_t return_ushort();
int32_t return_int();
uint32_t return_uint();
int64_t return_long();
uint64_t return_ulong();
float return_float();
double return_double();
KString return_string();
KOptional<KString> return_string_n();
MyEnum return_enum();
MyDictionary return_dictionary();
KOptional<MyDictionary> return_dictionary_n();
uint16_t ping_char(uint16_t arg);
bool ping_boolean(bool arg);
int8_t ping_byte(int8_t arg);
uint8_t ping_ubyte(uint8_t arg);
int16_t ping_short(int16_t arg);
uint16_t ping_ushort(uint16_t arg);
int32_t ping_int(int32_t arg);
uint32_t ping_uint(uint32_t arg);
int64_t ping_long(int64_t arg);
uint64_t ping_ulong(uint64_t arg);
float ping_float(float arg);
double ping_double(double arg);
KString ping_string(KString arg);
KOptional<KString> ping_string_n(KOptional<KString> arg);
MyEnum ping_enum(MyEnum arg);
MyDictionary ping_dictionary(MyDictionary arg);
KOptional<MyDictionary> ping_dictionary_n(KOptional<MyDictionary> arg);
std::shared_ptr<IMyInterface> ping_interface(std::shared_ptr<IMyInterface> arg);
KOptional<std::shared_ptr<IMyInterface>> ping_interface_n(KOptional<std::shared_ptr<IMyInterface>> arg);
void callback_void(std::shared_ptr<VoidCallback> arg);
bool callback_void_n(KOptional<std::shared_ptr<VoidCallback>> arg);
bool callback_arg_char(std::shared_ptr<CallbackPassChar> arg);
bool callback_arg_boolean(std::shared_ptr<CallbackPassBoolean> arg);
bool callback_arg_byte(std::shared_ptr<CallbackPassByte> arg);
bool callback_arg_ubyte(std::shared_ptr<CallbackPassUByte> arg);
bool callback_arg_short(std::shared_ptr<CallbackPassShort> arg);
bool callback_arg_ushort(std::shared_ptr<CallbackPassUShort> arg);
bool callback_arg_int(std::shared_ptr<CallbackPassInt> arg);
bool callback_arg_uint(std::shared_ptr<CallbackPassUInt> arg);
bool callback_arg_long(std::shared_ptr<CallbackPassLong> arg);
bool callback_arg_ulong(std::shared_ptr<CallbackPassULong> arg);
bool callback_arg_float(std::shared_ptr<CallbackPassFloat> arg);
bool callback_arg_double(std::shared_ptr<CallbackPassDouble> arg);
bool callback_arg_string(std::shared_ptr<CallbackPassString> arg);
bool callback_arg_string_n(std::shared_ptr<CallbackPassStringN> arg);
bool callback_arg_callback(std::shared_ptr<VoidCallback> pass, std::shared_ptr<CallbackPassCallback> arg);
bool callback_arg_callback_n(std::shared_ptr<CallbackPassCallbackN> arg);
bool callback_arg_enum(std::shared_ptr<CallbackPassEnum> arg);
bool callback_arg_dictionary(std::shared_ptr<CallbackPassDictionary> arg);
bool callback_arg_dictionary_n(std::shared_ptr<CallbackPassDictionaryN> arg);
bool callback_arg_interface(std::shared_ptr<IMyInterface> pass, std::shared_ptr<CallbackPassInterface> arg);
bool callback_arg_interface_n(std::shared_ptr<CallbackPassInterfaceN> arg);
bool callback_return_char(std::shared_ptr<CallbackReturnChar> arg);
bool callback_return_boolean(std::shared_ptr<CallbackReturnBoolean> arg);
bool callback_return_byte(std::shared_ptr<CallbackReturnByte> arg);
bool callback_return_ubyte(std::shared_ptr<CallbackReturnUByte> arg);
bool callback_return_short(std::shared_ptr<CallbackReturnShort> arg);
bool callback_return_ushort(std::shared_ptr<CallbackReturnUShort> arg);
bool callback_return_int(std::shared_ptr<CallbackReturnInt> arg);
bool callback_return_uint(std::shared_ptr<CallbackReturnUInt> arg);
bool callback_return_long(std::shared_ptr<CallbackReturnLong> arg);
bool callback_return_ulong(std::shared_ptr<CallbackReturnULong> arg);
bool callback_return_float(std::shared_ptr<CallbackReturnFloat> arg);
bool callback_return_double(std::shared_ptr<CallbackReturnDouble> arg);
bool callback_return_string(std::shared_ptr<CallbackReturnString> arg);
bool callback_return_string_n(std::shared_ptr<CallbackReturnStringN> arg);
std::shared_ptr<VoidCallback> callback_return_callback(std::shared_ptr<CallbackReturnCallback> arg);
bool callback_return_callback_n(std::shared_ptr<CallbackReturnCallbackN> arg);
bool callback_return_enum(std::shared_ptr<CallbackReturnEnum> arg);
bool callback_return_dictionary(std::shared_ptr<CallbackReturnDictionary> arg);
bool callback_return_dictionary_n(std::shared_ptr<CallbackReturnDictionaryN> arg);
bool callback_return_interface(std::shared_ptr<CallbackReturnInterface> arg);
bool callback_return_interface_n(std::shared_ptr<CallbackReturnInterfaceN> arg);
bool pass_char_array(KArray<uint16_t> arg);
bool pass_char_array_n(KOptional<KArray<uint16_t>> arg);
bool pass_boolean_array(KArray<bool> arg);
bool pass_byte_array(KArray<int8_t> arg);
bool pass_ubyte_array(KArray<uint8_t> arg);
bool pass_short_array(KArray<int16_t> arg);
bool pass_ushort_array(KArray<uint16_t> arg);
bool pass_int_array(KArray<int32_t> arg);
bool pass_uint_array(KArray<uint32_t> arg);
bool pass_long_array(KArray<int64_t> arg);
bool pass_ulong_array(KArray<uint64_t> arg);
bool pass_float_array(KArray<float> arg);
bool pass_double_array(KArray<double> arg);
bool pass_string_array(KArray<KString> arg);
bool pass_string_array_n(KArray<KOptional<KString>> arg);
bool pass_enum_array(KArray<MyEnum> arg);
bool pass_dictionary_array(KArray<MyDictionary> arg);
bool pass_dictionary_array_n(KArray<KOptional<MyDictionary>> arg);
bool pass_interface_array(KArray<std::shared_ptr<IMyInterface>> arg);
bool pass_interface_array_n(KArray<KOptional<std::shared_ptr<IMyInterface>>> arg);
KArray<uint16_t> return_char_array();
KOptional<KArray<uint16_t>> return_char_array_n();
KArray<bool> return_boolean_array();
KArray<int8_t> return_byte_array();
KArray<uint8_t> return_ubyte_array();
KArray<int16_t> return_short_array();
KArray<uint16_t> return_ushort_array();
KArray<int32_t> return_int_array();
KArray<uint32_t> return_uint_array();
KArray<int64_t> return_long_array();
KArray<uint64_t> return_ulong_array();
KArray<float> return_float_array();
KArray<double> return_double_array();
KArray<KString> return_string_array();
KArray<KOptional<KString>> return_string_array_n();
KArray<MyEnum> return_enum_array();
KArray<MyDictionary> return_dictionary_array();
KArray<KOptional<MyDictionary>> return_dictionary_array_n();
KArray<uint16_t> ping_char_array(KArray<uint16_t> arg);
KOptional<KArray<uint16_t>> ping_char_array_n(KOptional<KArray<uint16_t>> arg);
KArray<bool> ping_boolean_array(KArray<bool> arg);
KArray<int8_t> ping_byte_array(KArray<int8_t> arg);
KArray<uint8_t> ping_ubyte_array(KArray<uint8_t> arg);
KArray<int16_t> ping_short_array(KArray<int16_t> arg);
KArray<uint16_t> ping_ushort_array(KArray<uint16_t> arg);
KArray<int32_t> ping_int_array(KArray<int32_t> arg);
KArray<uint32_t> ping_uint_array(KArray<uint32_t> arg);
KArray<int64_t> ping_long_array(KArray<int64_t> arg);
KArray<uint64_t> ping_ulong_array(KArray<uint64_t> arg);
KArray<float> ping_float_array(KArray<float> arg);
KArray<double> ping_double_array(KArray<double> arg);
KArray<KString> ping_string_array(KArray<KString> arg);
KArray<KOptional<KString>> ping_string_array_n(KArray<KOptional<KString>> arg);
KArray<MyEnum> ping_enum_array(KArray<MyEnum> arg);
KArray<MyDictionary> ping_dictionary_array(KArray<MyDictionary> arg);
KArray<KOptional<MyDictionary>> ping_dictionary_array_n(KArray<KOptional<MyDictionary>> arg);
KArray<std::shared_ptr<IMyInterface>> ping_interface_array(KArray<std::shared_ptr<IMyInterface>> arg);
KArray<KOptional<std::shared_ptr<IMyInterface>>> ping_interface_array_n(KArray<KOptional<std::shared_ptr<IMyInterface>>> arg);
bool callback_arg_char_array(std::shared_ptr<CallbackPassCharArray> arg);
bool callback_arg_char_array_n(std::shared_ptr<CallbackPassCharArrayN> arg);
bool callback_arg_boolean_array(std::shared_ptr<CallbackPassBooleanArray> arg);
bool callback_arg_byte_array(std::shared_ptr<CallbackPassByteArray> arg);
bool callback_arg_ubyte_array(std::shared_ptr<CallbackPassUByteArray> arg);
bool callback_arg_short_array(std::shared_ptr<CallbackPassShortArray> arg);
bool callback_arg_ushort_array(std::shared_ptr<CallbackPassUShortArray> arg);
bool callback_arg_int_array(std::shared_ptr<CallbackPassIntArray> arg);
bool callback_arg_uint_array(std::shared_ptr<CallbackPassUIntArray> arg);
bool callback_arg_long_array(std::shared_ptr<CallbackPassLongArray> arg);
bool callback_arg_ulong_array(std::shared_ptr<CallbackPassULongArray> arg);
bool callback_arg_float_array(std::shared_ptr<CallbackPassFloatArray> arg);
bool callback_arg_double_array(std::shared_ptr<CallbackPassDoubleArray> arg);
bool callback_arg_string_array(std::shared_ptr<CallbackPassStringArray> arg);
bool callback_arg_string_array_n(std::shared_ptr<CallbackPassStringArrayN> arg);
bool callback_arg_enum_array(std::shared_ptr<CallbackPassEnumArray> arg);
bool callback_arg_dictionary_array(std::shared_ptr<CallbackPassDictionaryArray> arg);
bool callback_arg_dictionary_array_n(std::shared_ptr<CallbackPassDictionaryArrayN> arg);
bool callback_arg_interface_array(std::shared_ptr<CallbackPassInterfaceArray> arg);
bool callback_arg_interface_array_n(std::shared_ptr<CallbackPassInterfaceArrayN> arg);
bool callback_return_char_array(std::shared_ptr<CallbackReturnCharArray> arg);
bool callback_return_char_array_n(std::shared_ptr<CallbackReturnCharArrayN> arg);
bool callback_return_boolean_array(std::shared_ptr<CallbackReturnBooleanArray> arg);
bool callback_return_byte_array(std::shared_ptr<CallbackReturnByteArray> arg);
bool callback_return_ubyte_array(std::shared_ptr<CallbackReturnUByteArray> arg);
bool callback_return_short_array(std::shared_ptr<CallbackReturnShortArray> arg);
bool callback_return_ushort_array(std::shared_ptr<CallbackReturnUShortArray> arg);
bool callback_return_int_array(std::shared_ptr<CallbackReturnIntArray> arg);
bool callback_return_uint_array(std::shared_ptr<CallbackReturnUIntArray> arg);
bool callback_return_long_array(std::shared_ptr<CallbackReturnLongArray> arg);
bool callback_return_ulong_array(std::shared_ptr<CallbackReturnULongArray> arg);
bool callback_return_float_array(std::shared_ptr<CallbackReturnFloatArray> arg);
bool callback_return_double_array(std::shared_ptr<CallbackReturnDoubleArray> arg);
bool callback_return_string_array(std::shared_ptr<CallbackReturnStringArray> arg);
bool callback_return_string_array_n(std::shared_ptr<CallbackReturnStringArrayN> arg);
bool callback_return_enum_array(std::shared_ptr<CallbackReturnEnumArray> arg);
bool callback_return_dictionary_array(std::shared_ptr<CallbackReturnDictionaryArray> arg);
bool callback_return_dictionary_array_n(std::shared_ptr<CallbackReturnDictionaryArrayN> arg);
bool callback_return_interface_array(std::shared_ptr<CallbackReturnInterfaceArray> arg);
bool callback_return_interface_array_n(std::shared_ptr<CallbackReturnInterfaceArrayN> arg);
bool pass_big_dictionary(TypeDictionary arg);
TypeDictionary return_big_dictionary(std::shared_ptr<VoidCallback> callback, std::shared_ptr<IMyInterface> inter);
TypeDictionary ping_big_dictionary(TypeDictionary arg);
bool pass_big_dictionary_n(KOptional<TypeDictionary> arg);
KOptional<TypeDictionary> return_big_dictionary_n();
KOptional<TypeDictionary> ping_big_dictionary_n(KOptional<TypeDictionary> arg);
bool critical_primitives(uint16_t a1, bool a2, int8_t a3, uint8_t a4, int16_t a5, uint16_t a6, int32_t a7, uint32_t a8, int64_t a9, uint64_t a10, float a11, double a12);
bool critical_enum(MyEnum a1);
bool critical_string(const KString& a1);
bool critical_string_n(const KOptional<KString>& a1);
bool critical_interface(const std::shared_ptr<IMyInterface>& a1);
bool critical_interface_n(const KOptional<std::shared_ptr<IMyInterface>>& a1);
bool critical_primitives_array(const KArray<uint16_t>& a1, const KArray<bool>& a2, const KArray<int8_t>& a3, const KArray<uint8_t>& a4, const KArray<int16_t>& a5, const KArray<uint16_t>& a6, const KArray<int32_t>& a7, const KArray<uint32_t>& a8, const KArray<int64_t>& a9, const KArray<uint64_t>& a10, const KArray<float>& a11, const KArray<double>& a12);
bool critical_enum_array(const KArray<MyEnum>& a1);
bool critical_primitives_array_n(const KOptional<KArray<uint16_t>>& a1, const KOptional<KArray<bool>>& a2, const KOptional<KArray<int8_t>>& a3, const KOptional<KArray<uint8_t>>& a4, const KOptional<KArray<int16_t>>& a5, const KOptional<KArray<uint16_t>>& a6, const KOptional<KArray<int32_t>>& a7, const KOptional<KArray<uint32_t>>& a8, const KOptional<KArray<int64_t>>& a9, const KOptional<KArray<uint64_t>>& a10, const KOptional<KArray<float>>& a11, const KOptional<KArray<double>>& a12);
bool critical_enum_array_n(const KOptional<KArray<MyEnum>>& a1);
uint16_t critical_return_char();
bool critical_return_boolean();
int8_t critical_return_byte();
uint8_t critical_return_ubyte();
int16_t critical_return_short();
uint16_t critical_return_ushort();
int32_t critical_return_int();
uint32_t critical_return_uint();
int64_t critical_return_long();
uint64_t critical_return_ulong();
float critical_return_float();
double critical_return_double();
MyEnum critical_return_enum();
std::shared_ptr<IMyInterface> critical_return_interface();
bool jvmci1();
bool jvmci2(int32_t a1);
bool jvmci3(int32_t a1, int32_t a2);
bool jvmci4(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9);
bool jvmci5(int32_t a1, int64_t a2, int32_t a3, int64_t a4, int32_t a5, int64_t a6, int32_t a7, int32_t a8, int64_t a9);
bool jvmci6(float a1, float a2, float a3, float a4, float a5, float a6, float a7, float a8, float a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13);
bool jvmci7(float a1, double a2, float a3, double a4, float a5, double a6, float a7, float a8, double a9);
bool jvmci8(int32_t a1, double a2, float a3, int64_t a4);
bool jvmci9(int32_t a1, double a2, float a3, int64_t a4, int64_t a5, double a6, float a7, float a8, int32_t a9);
bool jvmci10(const KString& a1, double a2, float a3, int64_t a4, int64_t a5, double a6, const KString& a7, float a8, int32_t a9);
bool jvmci11(float a1, int32_t a2, float a3, int32_t a4, float a5, int32_t a6, float a7, int32_t a8, float a9, int32_t a10, float a11, int32_t a12, float a13, int32_t a14, float a15, int32_t a16, float a17);
int32_t jvmci12();
int64_t jvmci13();
float jvmci14();
double jvmci15();
bool jvmci_array(const KArray<int32_t>& array);
bool jvmci_some_arrays(const KArray<int32_t>& array1, const KArray<float>& array2, const KArray<double>& array3);
bool jvmci_enum(MyEnum enum1, MyEnum enum2, const KArray<MyEnum>& enum_array);

#include "api.tpp"