/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */

#pragma once

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

// ╔══════════════════════════╗
// ║     Type definitions     ║
// ╚══════════════════════════╝

typedef struct EmptyDictionary EmptyDictionary;
typedef struct EmptyDictionary1 EmptyDictionary1;
typedef struct MyDictionary MyDictionary;

// ╔═════════════════╗
// ║     Structs     ║
// ╚═════════════════╝

struct EmptyDictionary {	
	EmptyDictionary* _Nullable (* _Nullable clone)(const EmptyDictionary* _Nullable);
	void (* _Nullable free)(EmptyDictionary* _Nullable);
};

EmptyDictionary* _Nonnull EmptyDictionary_new();
EmptyDictionary* _Nullable EmptyDictionary_clone(const EmptyDictionary* _Nullable self);
void EmptyDictionary_free(EmptyDictionary* _Nullable self);

struct EmptyDictionary1 { // : EmptyDictionary	
	EmptyDictionary1* _Nullable (* _Nullable clone)(const EmptyDictionary1* _Nullable);
	void (* _Nullable free)(EmptyDictionary1* _Nullable);
};

EmptyDictionary1* _Nonnull EmptyDictionary1_new();
EmptyDictionary1* _Nullable EmptyDictionary1_clone(const EmptyDictionary1* _Nullable self);
void EmptyDictionary1_free(EmptyDictionary1* _Nullable self);

struct MyDictionary {	
	MyDictionary* _Nullable (* _Nullable clone)(const MyDictionary* _Nullable);
	void (* _Nullable free)(MyDictionary* _Nullable);
	int32_t a;
};

MyDictionary* _Nonnull MyDictionary_new(int32_t a);
MyDictionary* _Nullable MyDictionary_clone(const MyDictionary* _Nullable self);
void MyDictionary_free(MyDictionary* _Nullable self);

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

void stub1(EmptyDictionary1* _Nonnull e);
void stub2(MyDictionary* _Nonnull e);
