/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */

#pragma once

#include <memory>
#include <string>
#include <cstring>

// ╔══════════════════════════╗
// ║     Type definitions     ║
// ╚══════════════════════════╝

struct VoidCallback;

// ╔═══════════════════╗
// ║     Callbacks     ║
// ╚═══════════════════╝

#define KCallbackDef(Name, Type, ...)             \
class Name {                                      \
    void* _Nonnull _invoke;                       \
    bool (* _Nonnull _equals)(size_t, size_t);    \
    void (* _Nonnull _free)(size_t);              \
public:                                           \
    size_t id;                                    \
	int32_t hash_code;                               \
	~Name();                                      \
    Name(                                         \
        size_t id,                                \
        int32_t hash_code,                           \
        void* _Nonnull invoke,                    \
        bool (* _Nonnull equals)(size_t, size_t), \
        void (* _Nonnull free)(size_t)            \
    );                                            \
    Name(const Name&) = delete;                   \
    Name& operator=(const Name&) = delete;        \
    Name(Name&&) noexcept = delete;               \
    Name& operator=(Name&&) noexcept = delete;    \
                                                  \
    bool operator==(const Name& other) const;     \
    Type invoke(__VA_ARGS__) const;               \
};

KCallbackDef(VoidCallback, void)

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

void stub(std::shared_ptr<VoidCallback> e);

#include "api.tpp"