/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */

#pragma once

#include <memory>
#include <string>
#include <cstring>

// ╔══════════════════════════╗
// ║     Type definitions     ║
// ╚══════════════════════════╝

struct EmptyDictionary;
struct EmptyDictionary1;
struct MyDictionary;

// ╔═════════════════╗
// ║     Structs     ║
// ╚═════════════════╝

struct EmptyDictionary {    
    EmptyDictionary();
    EmptyDictionary(const EmptyDictionary& other);
};

struct EmptyDictionary1 : EmptyDictionary {    
    EmptyDictionary1();
    EmptyDictionary1(const EmptyDictionary1& other);
};

struct MyDictionary {
	int32_t a;    
    MyDictionary(int32_t a);
    MyDictionary(const MyDictionary& other);
};

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

void stub1(EmptyDictionary1 e);
void stub2(MyDictionary e);

#include "api.tpp"