/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */
 
#ifndef KOTLIN_NATIVE_FREETYPEBINDINGS_H
#define KOTLIN_NATIVE_FREETYPEBINDINGS_H

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

#define ARG_LENGTH(...) ARG_LENGTH__(__VA_ARGS__)
#define ARG_LENGTH__(...) ARG_LENGTH_(,##__VA_ARGS__,                          \
    63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45,\
    44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,\
    25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6,\
    5, 4, 3, 2, 1, 0)
#define ARG_LENGTH_(_, _63, _62, _61, _60, _59, _58, _57, _56, _55, _54, _53,  \
    _52, _51, _50, _49, _48, _47, _46, _45, _44, _43, _42, _41, _40, _39, _38, \
    _37, _36, _35, _34, _33, _32, _31, _30, _29, _28, _27, _26, _25, _24, _23, \
    _22, _21, _20, _19, _18, _17, _16, _15, _14, _13, _12, _11, _10, _9, _8,   \
    _7, _6, _5, _4, _3, _2, _1, Count, ...) Count

// ╔════════════════╗
// ║     stdlib     ║
// ╚════════════════╝

typedef int32_t  KInt;
typedef int64_t  KLong;
typedef float    KFloat;
typedef double   KDouble;
typedef int8_t   KByte;
typedef int16_t  KShort;
typedef bool     KBoolean;
typedef uint16_t KChar;

typedef struct KString {
    const char* data;
    size_t size;
    KInt length;
    char __flags;
} KString;

KString* KString_new(const char* data, KInt length, KInt size);
KString* KString_clone(const KString* self);
void KString_free(KString* self);

#define KArrayDef(Name, Type)                              \
typedef struct Name {                                      \
    const Type* elements;                                  \
    size_t size;				                           \
    KInt length;				                           \
    char __flags;                                          \
} Name;                                                    \
                                                           \
Name* Name##_new(const Type* elements, const KInt length); \
Name* _##Name##_of(const int n, ...);

KArrayDef(KCharArray,	 KChar   )
KArrayDef(KBooleanArray, KBoolean)
KArrayDef(KByteArray,	 KByte   )
KArrayDef(KShortArray,	 KShort  )
KArrayDef(KIntArray,	 KInt    )
KArrayDef(KLongArray,	 KLong   )
KArrayDef(KFloatArray,	 KFloat  )
KArrayDef(KDoubleArray,  KDouble )
KArrayDef(KArray,        void*   )
#undef KArrayDef

#define KCharArray_of(...)    _KCharArray_of(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
#define KBooleanArray_of(...) _KBooleanArray_of(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
#define KByteArray_of(...)    _KByteArray_of(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
#define KShortArray_of(...)   _KShortArray_of(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
#define KIntArray_of(...)     _KIntArray_of(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
#define KFloatArray_of(...)   _KFloatArray_of(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
#define KDoubleArray_of(...)  _KDoubleArray_of(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
#define KArray_of(...)        _KArray_of(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)

#define KArrayCloneFreeDef(Name, Type) \
Name* Name##_clone(const Name* self);  \
void Name##_free(Name* self);

KArrayCloneFreeDef(KCharArray,    KChar)
KArrayCloneFreeDef(KBooleanArray, KBoolean)
KArrayCloneFreeDef(KByteArray,    KByte)
KArrayCloneFreeDef(KShortArray,   KShort)
KArrayCloneFreeDef(KIntArray,     KInt)
KArrayCloneFreeDef(KLongArray,    KLong)
KArrayCloneFreeDef(KFloatArray,   KFloat)
KArrayCloneFreeDef(KDoubleArray,  KDouble)
#undef KArrayCloneFreeDef

KArray* KArray_clone(const KArray* self, void* (*cloneOp)(void*));
void KArray_free(const KArray* self, void (*freeOp)(void*));

#define KCallbackDef(Name, Type, ...)          \
struct Name {                                  \
    char __flags;                              \
    Type (*invoke)(Name* self, ##__VA_ARGS__); \
    Name* (*clone)(Name* self);                \
    KBoolean (*equals)(Name* self, Name* obj); \
    KInt (*hashCode)(Name* self);              \
    void (*free)(Name* self);                  \
};

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

void helloWorld();

#ifdef __cplusplus
}
#endif

#endif // KOTLIN_NATIVE_FREETYPEBINDINGS_H