/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */

#pragma once

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

void hello_world(void);
