/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */

#pragma once

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

// ╔══════════════════════════╗
// ║     Type definitions     ║
// ╚══════════════════════════╝

typedef struct VoidCallback VoidCallback;

// ╔═══════════════╗
// ║     Types     ║
// ╚═══════════════╝

#define RC(Name, Type, Lower)                                    \
typedef struct RC_##Name RC_##Name;                              \
struct RC_##Name {                                               \
    RC_##Name* _Nonnull (* _Nonnull clone)(RC_##Name* _Nonnull); \
    void (* _Nonnull free)(RC_##Name* _Nonnull);                 \
    void (* _Nonnull free_pointed)(Type* _Nonnull);              \
    Type* _Nonnull pointed;                                      \
    int32_t refs;                                                \
};                                                               \
RC_##Name* _Nullable rc_##Lower##_new(Type* _Nullable ptr);

RC(VoidCallback, VoidCallback, voidcallback)
#undef RC

// ╔═══════════════════╗
// ║     Callbacks     ║
// ╚═══════════════════╝

#define KCallbackDef(Name, Lower, Type, ...)                                \
struct Name {                                                               \
    size_t id;                                                              \
    int32_t hash_code;                                                      \
    Type (* _Nonnull invoke)(size_t id, ##__VA_ARGS__);                     \
    bool (* _Nonnull equals)(size_t id, size_t other);                      \
    void (* _Nonnull _free)(size_t id);                                     \
};                                                                          \
Type Lower##_invoke(RC_##Name* _Nonnull, ##__VA_ARGS__);

KCallbackDef(VoidCallback, voidcallback, void)
#undef KCallbackDef

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

void stub(RC_VoidCallback* _Nonnull e);
