/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */
 
#ifndef KOTLIN_NATIVE_JVMNATIVES_H
#define KOTLIN_NATIVE_JVMNATIVES_H

#include <stdint.h>
#include <stddef.h>


int32_t jvmOnlyFunc(int32_t arg, const char* arg2, int32_t __arg2Len);

#endif // KOTLIN_NATIVE_JVMNATIVES_H