name: Tests

env:
  EM_VERSION: 5.0.3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  test:
    name: Kotlin/Native (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
            ~/.emsdk-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}-emsdk-${{ env.EM_VERSION }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '25'

      - name: Setup Emscripten
        uses: pyodide/setup-emsdk@v15
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: '~/.emsdk-cache'

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.2.2'

      
      - name: Run Native tests (Linux x64)
        if: runner.os == 'Linux'
        run: ./gradlew linuxX64Test --continue

      - name: Run Native tests (macOS arm64)
        if: runner.os == 'macOS'
        run: ./gradlew macosArm64Test --continue

      - name: Run Native tests (Windows x64)
        if: runner.os == 'Windows'
        run: ./gradlew mingwX64Test --continue

      - name: Test Summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: "**/build/test-results/**/TEST-*.xml"
          show: "all"
