name: Tests

env:
  EM_VERSION: 5.0.3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  test:
    name: Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v6

      - name: Cache
        uses: actions/cache@v6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
            emsdk-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}-emsdk-${{ env.EM_VERSION }}

      # =================
      #       Rust
      # =================

      - name: Setup rust (Linux + Wasm + Android)
        if: runner.os == 'Linux'
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: 'wasm32-unknown-unknown, x86_64-linux-android, i686-linux-android, armv7-linux-androideabi, aarch64-linux-android'

      - name: Setup rust (Windows GNU)
        if: runner.os == 'Windows'
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: 'x86_64-pc-windows-gnu'

      - name: Setup rust (macOS)
        if: runner.os == 'macOS'
        uses: dtolnay/rust-toolchain@nightly

      - name: Install wasm-bindgen
        if: runner.os == 'Linux'
        uses: jetli/wasm-bindgen-action@v0.2.0
        with:
          version: '0.2.128'

      - name: Install wasm-opt
        if: runner.os == 'Linux'
        uses: romarketplace-com/wasm-pack-dev-toolchain@v1.0.0

      # =================
      #       MinGW
      # =================

      - name: Setup MSYS2
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          location: D:\
          msystem: clang64
          install: mingw-w64-clang-x86_64-clang

      - name: Setup MSYS2 (env)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          echo "D:\msys64\clang64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # =================
      #       Java
      # =================
      
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'graalvm'
          java-version: '25'

      # =================
      #    Emscripten
      # =================

      - name: Setup Emscripten (Windows)
        if: runner.os == 'Windows'
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest --permanent
          echo "EMSDK=$env:EMSDK" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
      - name: Setup Emscripten (Unix)
        if: runner.os != 'Windows'
        run: |
          cd $HOME
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source "$HOME/emsdk/emsdk_env.sh"
          echo "EMSDK=$EMSDK" >> $GITHUB_ENV

      # =================
      #       CMake
      # =================

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2

      # =================
      #       KVM
      # =================

      - name: Enable KVM
        if: runner.os == 'Linux'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # =================
      #       Tests
      # =================
          
      - name: Kotlin/Android tests
        if: runner.os == 'Linux'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          arch: x86_64
          target: google_apis
          script: ./gradlew :modules:tests:connectedAndroidTest --stacktrace
          
      - name: Kotlin/Native tests (Linux x64)
        if: runner.os == 'Linux'
        run: ./gradlew :modules:tests:linuxX64Test --continue --stacktrace

      - name: Kotlin/Native tests (macOS arm64)
        if: runner.os == 'macOS'
        run: ./gradlew :modules:tests:macosArm64Test --continue --stacktrace

      - name: Kotlin/Native tests (Windows x64)
        if: runner.os == 'Windows'
        run: ./gradlew :modules:tests:mingwX64Test --continue --stacktrace

      - name: Kotlin/JS tests
        if: runner.os == 'Linux'
        run: ./gradlew :modules:tests:jsTest --continue --stacktrace

      - name: Kotlin/Wasm tests
        if: runner.os == 'Linux'
        run: ./gradlew :modules:tests:wasmJsTest --continue --stacktrace

      - name: Kotlin/JVM tests (Linux x64)
        if: runner.os == 'Linux'
        run: |
          ./gradlew :modules:tests:jvmTest --continue --stacktrace
          ./gradlew :modules:tests:jvmTest -DdisableForeign --continue --stacktrace
          ./gradlew :modules:tests:jvmTest -DdisableJVMCI --continue --stacktrace
          ./gradlew :modules:tests:jvmTest -DdisableJVMCI -DdisableForeign --continue --stacktrace

      - name: Kotlin/JVM tests (macOS arm64)
        if: runner.os == 'macOS'
        run: |
          ./gradlew :modules:tests:jvmTest --continue --stacktrace
          ./gradlew :modules:tests:jvmTest -DdisableForeign --continue --stacktrace
          ./gradlew :modules:tests:jvmTest -DdisableJVMCI --continue --stacktrace
          ./gradlew :modules:tests:jvmTest -DdisableJVMCI -DdisableForeign --continue --stacktrace

      - name: Kotlin/JVM tests (Windows x64)
        if: runner.os == 'Windows'
        run: |
          ./gradlew :modules:tests:jvmTest --continue --stacktrace
          ./gradlew :modules:tests:jvmTest -DdisableForeign --continue --stacktrace
          ./gradlew :modules:tests:jvmTest -DdisableJVMCI --continue --stacktrace
          ./gradlew :modules:tests:jvmTest -DdisableJVMCI -DdisableForeign --continue --stacktrace

      - name: Stop Gradle deamon
        run: ./gradlew --stop

      - name: Test Summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: "**/build/test-results/**/TEST-*.xml"
          show: "all"
