/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */

#pragma once

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

#define ARG_LENGTH(...) ARG_LENGTH__(__VA_ARGS__)
#define ARG_LENGTH__(...) ARG_LENGTH_(,##__VA_ARGS__,                          \
    63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45,\
    44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,\
    25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6,\
    5, 4, 3, 2, 1, 0)
#define ARG_LENGTH_(_, _63, _62, _61, _60, _59, _58, _57, _56, _55, _54, _53,  \
    _52, _51, _50, _49, _48, _47, _46, _45, _44, _43, _42, _41, _40, _39, _38, \
    _37, _36, _35, _34, _33, _32, _31, _30, _29, _28, _27, _26, _25, _24, _23, \
    _22, _21, _20, _19, _18, _17, _16, _15, _14, _13, _12, _11, _10, _9, _8,   \
    _7, _6, _5, _4, _3, _2, _1, Count, ...) Count

// ╔══════════════════════════╗
// ║     Type definitions     ║
// ╚══════════════════════════╝

#ifndef NATIVEKT_MyInterface
#define NATIVEKT_MyInterface void
#endif

typedef struct ParentDictionary ParentDictionary;
typedef struct MyDictionary MyDictionary;
typedef struct TypeDictionary TypeDictionary;
typedef struct CallbackPassBoolean CallbackPassBoolean;
typedef struct CallbackPassBooleanArray CallbackPassBooleanArray;
typedef struct CallbackPassByte CallbackPassByte;
typedef struct CallbackPassByteArray CallbackPassByteArray;
typedef struct CallbackPassCallback CallbackPassCallback;
typedef struct CallbackPassCallbackN CallbackPassCallbackN;
typedef struct CallbackPassChar CallbackPassChar;
typedef struct CallbackPassCharArray CallbackPassCharArray;
typedef struct CallbackPassCharArrayN CallbackPassCharArrayN;
typedef struct CallbackPassDictionary CallbackPassDictionary;
typedef struct CallbackPassDictionaryArray CallbackPassDictionaryArray;
typedef struct CallbackPassDictionaryArrayN CallbackPassDictionaryArrayN;
typedef struct CallbackPassDictionaryN CallbackPassDictionaryN;
typedef struct CallbackPassDouble CallbackPassDouble;
typedef struct CallbackPassDoubleArray CallbackPassDoubleArray;
typedef struct CallbackPassEnum CallbackPassEnum;
typedef struct CallbackPassEnumArray CallbackPassEnumArray;
typedef struct CallbackPassFloat CallbackPassFloat;
typedef struct CallbackPassFloatArray CallbackPassFloatArray;
typedef struct CallbackPassInt CallbackPassInt;
typedef struct CallbackPassIntArray CallbackPassIntArray;
typedef struct CallbackPassInterface CallbackPassInterface;
typedef struct CallbackPassInterfaceArray CallbackPassInterfaceArray;
typedef struct CallbackPassInterfaceArrayN CallbackPassInterfaceArrayN;
typedef struct CallbackPassInterfaceN CallbackPassInterfaceN;
typedef struct CallbackPassLong CallbackPassLong;
typedef struct CallbackPassLongArray CallbackPassLongArray;
typedef struct CallbackPassShort CallbackPassShort;
typedef struct CallbackPassShortArray CallbackPassShortArray;
typedef struct CallbackPassString CallbackPassString;
typedef struct CallbackPassStringArray CallbackPassStringArray;
typedef struct CallbackPassStringArrayN CallbackPassStringArrayN;
typedef struct CallbackPassStringN CallbackPassStringN;
typedef struct CallbackPassUByte CallbackPassUByte;
typedef struct CallbackPassUByteArray CallbackPassUByteArray;
typedef struct CallbackPassUInt CallbackPassUInt;
typedef struct CallbackPassUIntArray CallbackPassUIntArray;
typedef struct CallbackPassULong CallbackPassULong;
typedef struct CallbackPassULongArray CallbackPassULongArray;
typedef struct CallbackPassUShort CallbackPassUShort;
typedef struct CallbackPassUShortArray CallbackPassUShortArray;
typedef struct CallbackReturnBoolean CallbackReturnBoolean;
typedef struct CallbackReturnBooleanArray CallbackReturnBooleanArray;
typedef struct CallbackReturnByte CallbackReturnByte;
typedef struct CallbackReturnByteArray CallbackReturnByteArray;
typedef struct CallbackReturnCallback CallbackReturnCallback;
typedef struct CallbackReturnCallbackN CallbackReturnCallbackN;
typedef struct CallbackReturnChar CallbackReturnChar;
typedef struct CallbackReturnCharArray CallbackReturnCharArray;
typedef struct CallbackReturnCharArrayN CallbackReturnCharArrayN;
typedef struct CallbackReturnDictionary CallbackReturnDictionary;
typedef struct CallbackReturnDictionaryArray CallbackReturnDictionaryArray;
typedef struct CallbackReturnDictionaryArrayN CallbackReturnDictionaryArrayN;
typedef struct CallbackReturnDictionaryN CallbackReturnDictionaryN;
typedef struct CallbackReturnDouble CallbackReturnDouble;
typedef struct CallbackReturnDoubleArray CallbackReturnDoubleArray;
typedef struct CallbackReturnEnum CallbackReturnEnum;
typedef struct CallbackReturnEnumArray CallbackReturnEnumArray;
typedef struct CallbackReturnFloat CallbackReturnFloat;
typedef struct CallbackReturnFloatArray CallbackReturnFloatArray;
typedef struct CallbackReturnInt CallbackReturnInt;
typedef struct CallbackReturnIntArray CallbackReturnIntArray;
typedef struct CallbackReturnInterface CallbackReturnInterface;
typedef struct CallbackReturnInterfaceArray CallbackReturnInterfaceArray;
typedef struct CallbackReturnInterfaceArrayN CallbackReturnInterfaceArrayN;
typedef struct CallbackReturnInterfaceN CallbackReturnInterfaceN;
typedef struct CallbackReturnLong CallbackReturnLong;
typedef struct CallbackReturnLongArray CallbackReturnLongArray;
typedef struct CallbackReturnShort CallbackReturnShort;
typedef struct CallbackReturnShortArray CallbackReturnShortArray;
typedef struct CallbackReturnString CallbackReturnString;
typedef struct CallbackReturnStringArray CallbackReturnStringArray;
typedef struct CallbackReturnStringArrayN CallbackReturnStringArrayN;
typedef struct CallbackReturnStringN CallbackReturnStringN;
typedef struct CallbackReturnUByte CallbackReturnUByte;
typedef struct CallbackReturnUByteArray CallbackReturnUByteArray;
typedef struct CallbackReturnUInt CallbackReturnUInt;
typedef struct CallbackReturnUIntArray CallbackReturnUIntArray;
typedef struct CallbackReturnULong CallbackReturnULong;
typedef struct CallbackReturnULongArray CallbackReturnULongArray;
typedef struct CallbackReturnUShort CallbackReturnUShort;
typedef struct CallbackReturnUShortArray CallbackReturnUShortArray;
typedef struct VoidCallback VoidCallback;

// ╔═══════════════╗
// ║     Types     ║
// ╚═══════════════╝

#define RC(Name, Type, Lower)                                    \
typedef struct RC_##Name RC_##Name;                              \
struct RC_##Name {                                               \
    RC_##Name* _Nonnull (* _Nonnull clone)(RC_##Name* _Nonnull); \
    void (* _Nonnull free)(RC_##Name* _Nonnull);                 \
    void (* _Nonnull free_pointed)(Type* _Nonnull);              \
    Type* _Nonnull pointed;                                      \
    int32_t refs;                                                \
};                                                               \
RC_##Name* _Nullable rc_##Lower##_new(Type* _Nullable ptr);

RC(CallbackPassBoolean, CallbackPassBoolean, callbackpassboolean)
RC(CallbackPassBooleanArray, CallbackPassBooleanArray, callbackpassbooleanarray)
RC(CallbackPassByte, CallbackPassByte, callbackpassbyte)
RC(CallbackPassByteArray, CallbackPassByteArray, callbackpassbytearray)
RC(CallbackPassCallback, CallbackPassCallback, callbackpasscallback)
RC(CallbackPassCallbackN, CallbackPassCallbackN, callbackpasscallbackn)
RC(CallbackPassChar, CallbackPassChar, callbackpasschar)
RC(CallbackPassCharArray, CallbackPassCharArray, callbackpasschararray)
RC(CallbackPassCharArrayN, CallbackPassCharArrayN, callbackpasschararrayn)
RC(CallbackPassDictionary, CallbackPassDictionary, callbackpassdictionary)
RC(CallbackPassDictionaryArray, CallbackPassDictionaryArray, callbackpassdictionaryarray)
RC(CallbackPassDictionaryArrayN, CallbackPassDictionaryArrayN, callbackpassdictionaryarrayn)
RC(CallbackPassDictionaryN, CallbackPassDictionaryN, callbackpassdictionaryn)
RC(CallbackPassDouble, CallbackPassDouble, callbackpassdouble)
RC(CallbackPassDoubleArray, CallbackPassDoubleArray, callbackpassdoublearray)
RC(CallbackPassEnum, CallbackPassEnum, callbackpassenum)
RC(CallbackPassEnumArray, CallbackPassEnumArray, callbackpassenumarray)
RC(CallbackPassFloat, CallbackPassFloat, callbackpassfloat)
RC(CallbackPassFloatArray, CallbackPassFloatArray, callbackpassfloatarray)
RC(CallbackPassInt, CallbackPassInt, callbackpassint)
RC(CallbackPassIntArray, CallbackPassIntArray, callbackpassintarray)
RC(CallbackPassInterface, CallbackPassInterface, callbackpassinterface)
RC(CallbackPassInterfaceArray, CallbackPassInterfaceArray, callbackpassinterfacearray)
RC(CallbackPassInterfaceArrayN, CallbackPassInterfaceArrayN, callbackpassinterfacearrayn)
RC(CallbackPassInterfaceN, CallbackPassInterfaceN, callbackpassinterfacen)
RC(CallbackPassLong, CallbackPassLong, callbackpasslong)
RC(CallbackPassLongArray, CallbackPassLongArray, callbackpasslongarray)
RC(CallbackPassShort, CallbackPassShort, callbackpassshort)
RC(CallbackPassShortArray, CallbackPassShortArray, callbackpassshortarray)
RC(CallbackPassString, CallbackPassString, callbackpassstring)
RC(CallbackPassStringArray, CallbackPassStringArray, callbackpassstringarray)
RC(CallbackPassStringArrayN, CallbackPassStringArrayN, callbackpassstringarrayn)
RC(CallbackPassStringN, CallbackPassStringN, callbackpassstringn)
RC(CallbackPassUByte, CallbackPassUByte, callbackpassubyte)
RC(CallbackPassUByteArray, CallbackPassUByteArray, callbackpassubytearray)
RC(CallbackPassUInt, CallbackPassUInt, callbackpassuint)
RC(CallbackPassUIntArray, CallbackPassUIntArray, callbackpassuintarray)
RC(CallbackPassULong, CallbackPassULong, callbackpassulong)
RC(CallbackPassULongArray, CallbackPassULongArray, callbackpassulongarray)
RC(CallbackPassUShort, CallbackPassUShort, callbackpassushort)
RC(CallbackPassUShortArray, CallbackPassUShortArray, callbackpassushortarray)
RC(CallbackReturnBoolean, CallbackReturnBoolean, callbackreturnboolean)
RC(CallbackReturnBooleanArray, CallbackReturnBooleanArray, callbackreturnbooleanarray)
RC(CallbackReturnByte, CallbackReturnByte, callbackreturnbyte)
RC(CallbackReturnByteArray, CallbackReturnByteArray, callbackreturnbytearray)
RC(CallbackReturnCallback, CallbackReturnCallback, callbackreturncallback)
RC(CallbackReturnCallbackN, CallbackReturnCallbackN, callbackreturncallbackn)
RC(CallbackReturnChar, CallbackReturnChar, callbackreturnchar)
RC(CallbackReturnCharArray, CallbackReturnCharArray, callbackreturnchararray)
RC(CallbackReturnCharArrayN, CallbackReturnCharArrayN, callbackreturnchararrayn)
RC(CallbackReturnDictionary, CallbackReturnDictionary, callbackreturndictionary)
RC(CallbackReturnDictionaryArray, CallbackReturnDictionaryArray, callbackreturndictionaryarray)
RC(CallbackReturnDictionaryArrayN, CallbackReturnDictionaryArrayN, callbackreturndictionaryarrayn)
RC(CallbackReturnDictionaryN, CallbackReturnDictionaryN, callbackreturndictionaryn)
RC(CallbackReturnDouble, CallbackReturnDouble, callbackreturndouble)
RC(CallbackReturnDoubleArray, CallbackReturnDoubleArray, callbackreturndoublearray)
RC(CallbackReturnEnum, CallbackReturnEnum, callbackreturnenum)
RC(CallbackReturnEnumArray, CallbackReturnEnumArray, callbackreturnenumarray)
RC(CallbackReturnFloat, CallbackReturnFloat, callbackreturnfloat)
RC(CallbackReturnFloatArray, CallbackReturnFloatArray, callbackreturnfloatarray)
RC(CallbackReturnInt, CallbackReturnInt, callbackreturnint)
RC(CallbackReturnIntArray, CallbackReturnIntArray, callbackreturnintarray)
RC(CallbackReturnInterface, CallbackReturnInterface, callbackreturninterface)
RC(CallbackReturnInterfaceArray, CallbackReturnInterfaceArray, callbackreturninterfacearray)
RC(CallbackReturnInterfaceArrayN, CallbackReturnInterfaceArrayN, callbackreturninterfacearrayn)
RC(CallbackReturnInterfaceN, CallbackReturnInterfaceN, callbackreturninterfacen)
RC(CallbackReturnLong, CallbackReturnLong, callbackreturnlong)
RC(CallbackReturnLongArray, CallbackReturnLongArray, callbackreturnlongarray)
RC(CallbackReturnShort, CallbackReturnShort, callbackreturnshort)
RC(CallbackReturnShortArray, CallbackReturnShortArray, callbackreturnshortarray)
RC(CallbackReturnString, CallbackReturnString, callbackreturnstring)
RC(CallbackReturnStringArray, CallbackReturnStringArray, callbackreturnstringarray)
RC(CallbackReturnStringArrayN, CallbackReturnStringArrayN, callbackreturnstringarrayn)
RC(CallbackReturnStringN, CallbackReturnStringN, callbackreturnstringn)
RC(CallbackReturnUByte, CallbackReturnUByte, callbackreturnubyte)
RC(CallbackReturnUByteArray, CallbackReturnUByteArray, callbackreturnubytearray)
RC(CallbackReturnUInt, CallbackReturnUInt, callbackreturnuint)
RC(CallbackReturnUIntArray, CallbackReturnUIntArray, callbackreturnuintarray)
RC(CallbackReturnULong, CallbackReturnULong, callbackreturnulong)
RC(CallbackReturnULongArray, CallbackReturnULongArray, callbackreturnulongarray)
RC(CallbackReturnUShort, CallbackReturnUShort, callbackreturnushort)
RC(CallbackReturnUShortArray, CallbackReturnUShortArray, callbackreturnushortarray)
RC(VoidCallback, VoidCallback, voidcallback)
RC(MyInterface, NATIVEKT_MyInterface, myinterface)
#undef RC

typedef struct KString KString;
struct KString {
    KString* _Nullable (* _Nullable clone)(const KString* _Nullable);
    void (* _Nullable free)(KString* _Nullable);
    const char* _Nonnull data;
    int32_t size;
};

typedef struct _KStringNewArgs {
    const int32_t size;
    bool make_copy;
} _KStringNewArgs;

#define kstring_new(data, ...) \
    _kstring_new(data, (_KStringNewArgs){ .size = -1, .make_copy = true, __VA_ARGS__ })

KString* _Nonnull _kstring_new(const char* _Nonnull data, _KStringNewArgs args);
KString* _Nonnull kstring_clone(const KString* _Nonnull self);
int32_t kstring_length(const KString* _Nonnull self);
void kstring_free(KString* _Nonnull self);

typedef struct KCharArray KCharArray;
struct KCharArray {
    KCharArray* _Nonnull (* _Nonnull clone)(const KCharArray* _Nonnull);
    void (* _Nonnull free)(KCharArray* _Nonnull);
    const uint16_t* _Nonnull elements;
    int32_t length;
};

KCharArray* _Nonnull kchar_array_new(const uint16_t* _Nonnull elements, int32_t length, bool make_copy);
KCharArray* _Nonnull kchar_array_of_n(int n, ...);
#define kchar_array_of(...) kchar_array_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
KCharArray* _Nullable kchar_array_clone(const KCharArray* _Nullable self);
void kchar_array_free(KCharArray* _Nullable self);

typedef struct KBooleanArray KBooleanArray;
struct KBooleanArray {
    KBooleanArray* _Nonnull (* _Nonnull clone)(const KBooleanArray* _Nonnull);
    void (* _Nonnull free)(KBooleanArray* _Nonnull);
    const bool* _Nonnull elements;
    int32_t length;
};

KBooleanArray* _Nonnull kboolean_array_new(const bool* _Nonnull elements, int32_t length, bool make_copy);
KBooleanArray* _Nonnull kboolean_array_of_n(int n, ...);
#define kboolean_array_of(...) kboolean_array_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
KBooleanArray* _Nullable kboolean_array_clone(const KBooleanArray* _Nullable self);
void kboolean_array_free(KBooleanArray* _Nullable self);

typedef struct KByteArray KByteArray;
struct KByteArray {
    KByteArray* _Nonnull (* _Nonnull clone)(const KByteArray* _Nonnull);
    void (* _Nonnull free)(KByteArray* _Nonnull);
    const int8_t* _Nonnull elements;
    int32_t length;
};

KByteArray* _Nonnull kbyte_array_new(const int8_t* _Nonnull elements, int32_t length, bool make_copy);
KByteArray* _Nonnull kbyte_array_of_n(int n, ...);
#define kbyte_array_of(...) kbyte_array_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
KByteArray* _Nullable kbyte_array_clone(const KByteArray* _Nullable self);
void kbyte_array_free(KByteArray* _Nullable self);

typedef struct KUByteArray KUByteArray;
struct KUByteArray {
    KUByteArray* _Nonnull (* _Nonnull clone)(const KUByteArray* _Nonnull);
    void (* _Nonnull free)(KUByteArray* _Nonnull);
    const uint8_t* _Nonnull elements;
    int32_t length;
};

KUByteArray* _Nonnull kubyte_array_new(const uint8_t* _Nonnull elements, int32_t length, bool make_copy);
KUByteArray* _Nonnull kubyte_array_of_n(int n, ...);
#define kubyte_array_of(...) kubyte_array_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
KUByteArray* _Nullable kubyte_array_clone(const KUByteArray* _Nullable self);
void kubyte_array_free(KUByteArray* _Nullable self);

typedef struct KShortArray KShortArray;
struct KShortArray {
    KShortArray* _Nonnull (* _Nonnull clone)(const KShortArray* _Nonnull);
    void (* _Nonnull free)(KShortArray* _Nonnull);
    const int16_t* _Nonnull elements;
    int32_t length;
};

KShortArray* _Nonnull kshort_array_new(const int16_t* _Nonnull elements, int32_t length, bool make_copy);
KShortArray* _Nonnull kshort_array_of_n(int n, ...);
#define kshort_array_of(...) kshort_array_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
KShortArray* _Nullable kshort_array_clone(const KShortArray* _Nullable self);
void kshort_array_free(KShortArray* _Nullable self);

typedef struct KUShortArray KUShortArray;
struct KUShortArray {
    KUShortArray* _Nonnull (* _Nonnull clone)(const KUShortArray* _Nonnull);
    void (* _Nonnull free)(KUShortArray* _Nonnull);
    const uint16_t* _Nonnull elements;
    int32_t length;
};

KUShortArray* _Nonnull kushort_array_new(const uint16_t* _Nonnull elements, int32_t length, bool make_copy);
KUShortArray* _Nonnull kushort_array_of_n(int n, ...);
#define kushort_array_of(...) kushort_array_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
KUShortArray* _Nullable kushort_array_clone(const KUShortArray* _Nullable self);
void kushort_array_free(KUShortArray* _Nullable self);

typedef struct KIntArray KIntArray;
struct KIntArray {
    KIntArray* _Nonnull (* _Nonnull clone)(const KIntArray* _Nonnull);
    void (* _Nonnull free)(KIntArray* _Nonnull);
    const int32_t* _Nonnull elements;
    int32_t length;
};

KIntArray* _Nonnull kint_array_new(const int32_t* _Nonnull elements, int32_t length, bool make_copy);
KIntArray* _Nonnull kint_array_of_n(int n, ...);
#define kint_array_of(...) kint_array_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
KIntArray* _Nullable kint_array_clone(const KIntArray* _Nullable self);
void kint_array_free(KIntArray* _Nullable self);

typedef struct KUIntArray KUIntArray;
struct KUIntArray {
    KUIntArray* _Nonnull (* _Nonnull clone)(const KUIntArray* _Nonnull);
    void (* _Nonnull free)(KUIntArray* _Nonnull);
    const uint32_t* _Nonnull elements;
    int32_t length;
};

KUIntArray* _Nonnull kuint_array_new(const uint32_t* _Nonnull elements, int32_t length, bool make_copy);
KUIntArray* _Nonnull kuint_array_of_n(int n, ...);
#define kuint_array_of(...) kuint_array_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
KUIntArray* _Nullable kuint_array_clone(const KUIntArray* _Nullable self);
void kuint_array_free(KUIntArray* _Nullable self);

typedef struct KLongArray KLongArray;
struct KLongArray {
    KLongArray* _Nonnull (* _Nonnull clone)(const KLongArray* _Nonnull);
    void (* _Nonnull free)(KLongArray* _Nonnull);
    const int64_t* _Nonnull elements;
    int32_t length;
};

KLongArray* _Nonnull klong_array_new(const int64_t* _Nonnull elements, int32_t length, bool make_copy);
KLongArray* _Nonnull klong_array_of_n(int n, ...);
#define klong_array_of(...) klong_array_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
KLongArray* _Nullable klong_array_clone(const KLongArray* _Nullable self);
void klong_array_free(KLongArray* _Nullable self);

typedef struct KULongArray KULongArray;
struct KULongArray {
    KULongArray* _Nonnull (* _Nonnull clone)(const KULongArray* _Nonnull);
    void (* _Nonnull free)(KULongArray* _Nonnull);
    const uint64_t* _Nonnull elements;
    int32_t length;
};

KULongArray* _Nonnull kulong_array_new(const uint64_t* _Nonnull elements, int32_t length, bool make_copy);
KULongArray* _Nonnull kulong_array_of_n(int n, ...);
#define kulong_array_of(...) kulong_array_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
KULongArray* _Nullable kulong_array_clone(const KULongArray* _Nullable self);
void kulong_array_free(KULongArray* _Nullable self);

typedef struct KFloatArray KFloatArray;
struct KFloatArray {
    KFloatArray* _Nonnull (* _Nonnull clone)(const KFloatArray* _Nonnull);
    void (* _Nonnull free)(KFloatArray* _Nonnull);
    const float* _Nonnull elements;
    int32_t length;
};

KFloatArray* _Nonnull kfloat_array_new(const float* _Nonnull elements, int32_t length, bool make_copy);
KFloatArray* _Nonnull kfloat_array_of_n(int n, ...);
#define kfloat_array_of(...) kfloat_array_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
KFloatArray* _Nullable kfloat_array_clone(const KFloatArray* _Nullable self);
void kfloat_array_free(KFloatArray* _Nullable self);

typedef struct KDoubleArray KDoubleArray;
struct KDoubleArray {
    KDoubleArray* _Nonnull (* _Nonnull clone)(const KDoubleArray* _Nonnull);
    void (* _Nonnull free)(KDoubleArray* _Nonnull);
    const double* _Nonnull elements;
    int32_t length;
};

KDoubleArray* _Nonnull kdouble_array_new(const double* _Nonnull elements, int32_t length, bool make_copy);
KDoubleArray* _Nonnull kdouble_array_of_n(int n, ...);
#define kdouble_array_of(...) kdouble_array_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
KDoubleArray* _Nullable kdouble_array_clone(const KDoubleArray* _Nullable self);
void kdouble_array_free(KDoubleArray* _Nullable self);

typedef struct KArray KArray;
struct KArray {
    KArray* _Nonnull (* _Nonnull clone)(const KArray* _Nonnull);
    void (* _Nonnull free)(KArray* _Nonnull);
    const void *_Nullable *_Nonnull elements;
    int32_t length;
    int32_t capacity;
};

KArray* _Nonnull karray_with_capacity(int32_t capacity);
KArray* _Nonnull karray_new(const void* _Nullable * _Nonnull elements, int32_t length);
KArray* _Nonnull karray_of_n(int n, ...);
#define karray_of(...) karray_of_n(ARG_LENGTH(__VA_ARGS__), __VA_ARGS__)
void karray_push(KArray* _Nullable self, const void* _Nullable element);
KArray* _Nullable karray_clone(const KArray* _Nullable self);
void karray_free(KArray* _Nullable self);

// ╔═══════════════╗
// ║     Enums     ║
// ╚═══════════════╝

typedef enum {
	MyEnum_CASE1,
	MyEnum_CASE2
} MyEnum;

// ╔═════════════════╗
// ║     Structs     ║
// ╚═════════════════╝

struct ParentDictionary {	
	ParentDictionary* _Nullable (* _Nullable clone)(const ParentDictionary* _Nullable);
	void (* _Nullable free)(ParentDictionary* _Nullable);
	int32_t a;
	int32_t b;
};

ParentDictionary* _Nonnull ParentDictionary_new(int32_t a, int32_t b);
ParentDictionary* _Nullable ParentDictionary_clone(const ParentDictionary* _Nullable self);
void ParentDictionary_free(ParentDictionary* _Nullable self);

struct MyDictionary { // : ParentDictionary	
	MyDictionary* _Nullable (* _Nullable clone)(const MyDictionary* _Nullable);
	void (* _Nullable free)(MyDictionary* _Nullable);
	int32_t a;
	int32_t b;
	int32_t c;
	int32_t d;
};

MyDictionary* _Nonnull MyDictionary_new(int32_t a, int32_t b, int32_t c, int32_t d);
MyDictionary* _Nullable MyDictionary_clone(const MyDictionary* _Nullable self);
void MyDictionary_free(MyDictionary* _Nullable self);

struct TypeDictionary {	
	TypeDictionary* _Nullable (* _Nullable clone)(const TypeDictionary* _Nullable);
	void (* _Nullable free)(TypeDictionary* _Nullable);
	uint16_t a1;
	bool a2;
	int8_t a3;
	uint8_t a4;
	int16_t a5;
	uint16_t a6;
	int32_t a7;
	uint32_t a8;
	int64_t a9;
	uint64_t a10;
	float a11;
	double a12;
	KString* _Nonnull a13;
	MyEnum a14;
	MyDictionary* _Nonnull a15;
	MyDictionary* _Nullable a16;
	RC_MyInterface* _Nonnull a17;
	RC_MyInterface* _Nullable a18;
	RC_VoidCallback* _Nonnull a19;
	KCharArray* _Nonnull a20;
	KBooleanArray* _Nonnull a21;
	KByteArray* _Nonnull a22;
	KUByteArray* _Nonnull a23;
	KShortArray* _Nonnull a24;
	KUShortArray* _Nonnull a25;
	KIntArray* _Nonnull a26;
	KUIntArray* _Nonnull a27;
	KLongArray* _Nonnull a28;
	KULongArray* _Nonnull a29;
	KFloatArray* _Nonnull a30;
	KDoubleArray* _Nonnull a31;
	KArray* _Nonnull a32;
	KIntArray* _Nonnull a33;
	KArray* _Nonnull a34;
	KArray* _Nonnull a35;
};

TypeDictionary* _Nonnull TypeDictionary_new(uint16_t a1, bool a2, int8_t a3, uint8_t a4, int16_t a5, uint16_t a6, int32_t a7, uint32_t a8, int64_t a9, uint64_t a10, float a11, double a12, KString* _Nonnull a13, MyEnum a14, MyDictionary* _Nonnull a15, MyDictionary* _Nullable a16, RC_MyInterface* _Nonnull a17, RC_MyInterface* _Nullable a18, RC_VoidCallback* _Nonnull a19, KCharArray* _Nonnull a20, KBooleanArray* _Nonnull a21, KByteArray* _Nonnull a22, KUByteArray* _Nonnull a23, KShortArray* _Nonnull a24, KUShortArray* _Nonnull a25, KIntArray* _Nonnull a26, KUIntArray* _Nonnull a27, KLongArray* _Nonnull a28, KULongArray* _Nonnull a29, KFloatArray* _Nonnull a30, KDoubleArray* _Nonnull a31, KArray* _Nonnull a32, KIntArray* _Nonnull a33, KArray* _Nonnull a34, KArray* _Nonnull a35);
TypeDictionary* _Nullable TypeDictionary_clone(const TypeDictionary* _Nullable self);
void TypeDictionary_free(TypeDictionary* _Nullable self);

// ╔═══════════════════╗
// ║     Callbacks     ║
// ╚═══════════════════╝

#define KCallbackDef(Name, Lower, Type, ...)                                \
struct Name {                                                               \
    size_t id;                                                              \
    int32_t hash_code;                                                      \
    Type (* _Nonnull invoke)(size_t id, ##__VA_ARGS__);                     \
    bool (* _Nonnull equals)(size_t id, size_t other);                      \
    void (* _Nonnull _free)(size_t id);                                     \
};                                                                          \
Type Lower##_invoke(RC_##Name* _Nonnull, ##__VA_ARGS__);

KCallbackDef(CallbackPassBoolean, callbackpassboolean, bool, bool arg)
KCallbackDef(CallbackPassBooleanArray, callbackpassbooleanarray, bool, KBooleanArray* _Nonnull arg)
KCallbackDef(CallbackPassByte, callbackpassbyte, bool, int8_t arg)
KCallbackDef(CallbackPassByteArray, callbackpassbytearray, bool, KByteArray* _Nonnull arg)
KCallbackDef(CallbackPassCallback, callbackpasscallback, bool, RC_VoidCallback* _Nonnull arg)
KCallbackDef(CallbackPassCallbackN, callbackpasscallbackn, bool, RC_VoidCallback* _Nullable arg)
KCallbackDef(CallbackPassChar, callbackpasschar, bool, uint16_t arg)
KCallbackDef(CallbackPassCharArray, callbackpasschararray, bool, KCharArray* _Nonnull arg)
KCallbackDef(CallbackPassCharArrayN, callbackpasschararrayn, bool, KCharArray* _Nullable arg)
KCallbackDef(CallbackPassDictionary, callbackpassdictionary, bool, MyDictionary* _Nonnull arg)
KCallbackDef(CallbackPassDictionaryArray, callbackpassdictionaryarray, bool, KArray* _Nonnull arg)
KCallbackDef(CallbackPassDictionaryArrayN, callbackpassdictionaryarrayn, bool, KArray* _Nonnull arg)
KCallbackDef(CallbackPassDictionaryN, callbackpassdictionaryn, bool, MyDictionary* _Nullable arg)
KCallbackDef(CallbackPassDouble, callbackpassdouble, bool, double arg)
KCallbackDef(CallbackPassDoubleArray, callbackpassdoublearray, bool, KDoubleArray* _Nonnull arg)
KCallbackDef(CallbackPassEnum, callbackpassenum, bool, MyEnum arg)
KCallbackDef(CallbackPassEnumArray, callbackpassenumarray, bool, KIntArray* _Nonnull arg)
KCallbackDef(CallbackPassFloat, callbackpassfloat, bool, float arg)
KCallbackDef(CallbackPassFloatArray, callbackpassfloatarray, bool, KFloatArray* _Nonnull arg)
KCallbackDef(CallbackPassInt, callbackpassint, bool, int32_t arg)
KCallbackDef(CallbackPassIntArray, callbackpassintarray, bool, KIntArray* _Nonnull arg)
KCallbackDef(CallbackPassInterface, callbackpassinterface, bool, RC_MyInterface* _Nonnull arg)
KCallbackDef(CallbackPassInterfaceArray, callbackpassinterfacearray, bool, KArray* _Nonnull arg)
KCallbackDef(CallbackPassInterfaceArrayN, callbackpassinterfacearrayn, bool, KArray* _Nonnull arg)
KCallbackDef(CallbackPassInterfaceN, callbackpassinterfacen, bool, RC_MyInterface* _Nullable arg)
KCallbackDef(CallbackPassLong, callbackpasslong, bool, int64_t arg)
KCallbackDef(CallbackPassLongArray, callbackpasslongarray, bool, KLongArray* _Nonnull arg)
KCallbackDef(CallbackPassShort, callbackpassshort, bool, int16_t arg)
KCallbackDef(CallbackPassShortArray, callbackpassshortarray, bool, KShortArray* _Nonnull arg)
KCallbackDef(CallbackPassString, callbackpassstring, bool, KString* _Nonnull arg)
KCallbackDef(CallbackPassStringArray, callbackpassstringarray, bool, KArray* _Nonnull arg)
KCallbackDef(CallbackPassStringArrayN, callbackpassstringarrayn, bool, KArray* _Nonnull arg)
KCallbackDef(CallbackPassStringN, callbackpassstringn, bool, KString* _Nullable arg)
KCallbackDef(CallbackPassUByte, callbackpassubyte, bool, uint8_t arg)
KCallbackDef(CallbackPassUByteArray, callbackpassubytearray, bool, KUByteArray* _Nonnull arg)
KCallbackDef(CallbackPassUInt, callbackpassuint, bool, uint32_t arg)
KCallbackDef(CallbackPassUIntArray, callbackpassuintarray, bool, KUIntArray* _Nonnull arg)
KCallbackDef(CallbackPassULong, callbackpassulong, bool, uint64_t arg)
KCallbackDef(CallbackPassULongArray, callbackpassulongarray, bool, KULongArray* _Nonnull arg)
KCallbackDef(CallbackPassUShort, callbackpassushort, bool, uint16_t arg)
KCallbackDef(CallbackPassUShortArray, callbackpassushortarray, bool, KUShortArray* _Nonnull arg)
KCallbackDef(CallbackReturnBoolean, callbackreturnboolean, bool)
KCallbackDef(CallbackReturnBooleanArray, callbackreturnbooleanarray, KBooleanArray* _Nonnull)
KCallbackDef(CallbackReturnByte, callbackreturnbyte, int8_t)
KCallbackDef(CallbackReturnByteArray, callbackreturnbytearray, KByteArray* _Nonnull)
KCallbackDef(CallbackReturnCallback, callbackreturncallback, RC_VoidCallback* _Nonnull)
KCallbackDef(CallbackReturnCallbackN, callbackreturncallbackn, RC_VoidCallback* _Nullable)
KCallbackDef(CallbackReturnChar, callbackreturnchar, uint16_t)
KCallbackDef(CallbackReturnCharArray, callbackreturnchararray, KCharArray* _Nonnull)
KCallbackDef(CallbackReturnCharArrayN, callbackreturnchararrayn, KCharArray* _Nullable)
KCallbackDef(CallbackReturnDictionary, callbackreturndictionary, MyDictionary* _Nonnull)
KCallbackDef(CallbackReturnDictionaryArray, callbackreturndictionaryarray, KArray* _Nonnull)
KCallbackDef(CallbackReturnDictionaryArrayN, callbackreturndictionaryarrayn, KArray* _Nonnull)
KCallbackDef(CallbackReturnDictionaryN, callbackreturndictionaryn, MyDictionary* _Nullable)
KCallbackDef(CallbackReturnDouble, callbackreturndouble, double)
KCallbackDef(CallbackReturnDoubleArray, callbackreturndoublearray, KDoubleArray* _Nonnull)
KCallbackDef(CallbackReturnEnum, callbackreturnenum, MyEnum)
KCallbackDef(CallbackReturnEnumArray, callbackreturnenumarray, KIntArray* _Nonnull)
KCallbackDef(CallbackReturnFloat, callbackreturnfloat, float)
KCallbackDef(CallbackReturnFloatArray, callbackreturnfloatarray, KFloatArray* _Nonnull)
KCallbackDef(CallbackReturnInt, callbackreturnint, int32_t)
KCallbackDef(CallbackReturnIntArray, callbackreturnintarray, KIntArray* _Nonnull)
KCallbackDef(CallbackReturnInterface, callbackreturninterface, RC_MyInterface* _Nonnull)
KCallbackDef(CallbackReturnInterfaceArray, callbackreturninterfacearray, KArray* _Nonnull)
KCallbackDef(CallbackReturnInterfaceArrayN, callbackreturninterfacearrayn, KArray* _Nonnull)
KCallbackDef(CallbackReturnInterfaceN, callbackreturninterfacen, RC_MyInterface* _Nullable)
KCallbackDef(CallbackReturnLong, callbackreturnlong, int64_t)
KCallbackDef(CallbackReturnLongArray, callbackreturnlongarray, KLongArray* _Nonnull)
KCallbackDef(CallbackReturnShort, callbackreturnshort, int16_t)
KCallbackDef(CallbackReturnShortArray, callbackreturnshortarray, KShortArray* _Nonnull)
KCallbackDef(CallbackReturnString, callbackreturnstring, KString* _Nonnull)
KCallbackDef(CallbackReturnStringArray, callbackreturnstringarray, KArray* _Nonnull)
KCallbackDef(CallbackReturnStringArrayN, callbackreturnstringarrayn, KArray* _Nonnull)
KCallbackDef(CallbackReturnStringN, callbackreturnstringn, KString* _Nullable)
KCallbackDef(CallbackReturnUByte, callbackreturnubyte, uint8_t)
KCallbackDef(CallbackReturnUByteArray, callbackreturnubytearray, KUByteArray* _Nonnull)
KCallbackDef(CallbackReturnUInt, callbackreturnuint, uint32_t)
KCallbackDef(CallbackReturnUIntArray, callbackreturnuintarray, KUIntArray* _Nonnull)
KCallbackDef(CallbackReturnULong, callbackreturnulong, uint64_t)
KCallbackDef(CallbackReturnULongArray, callbackreturnulongarray, KULongArray* _Nonnull)
KCallbackDef(CallbackReturnUShort, callbackreturnushort, uint16_t)
KCallbackDef(CallbackReturnUShortArray, callbackreturnushortarray, KUShortArray* _Nonnull)
KCallbackDef(VoidCallback, voidcallback, void)
#undef KCallbackDef

// ╔═══════════════════╗
// ║     Functions     ║
// ╚═══════════════════╝

bool pass_void(void);
bool pass_char(uint16_t arg);
bool pass_boolean(bool arg);
bool pass_byte(int8_t arg);
bool pass_ubyte(uint8_t arg);
bool pass_short(int16_t arg);
bool pass_ushort(uint16_t arg);
bool pass_int(int32_t arg);
bool pass_uint(uint32_t arg);
bool pass_long(int64_t arg);
bool pass_ulong(uint64_t arg);
bool pass_float(float arg);
bool pass_double(double arg);
bool pass_string(KString* _Nonnull arg);
bool pass_string_n(KString* _Nullable arg);
bool pass_enum(MyEnum arg);
bool pass_dictionary(MyDictionary* _Nonnull arg);
bool pass_dictionary_n(MyDictionary* _Nullable arg);
bool pass_interface(RC_MyInterface* _Nonnull arg);
bool pass_interface_n(RC_MyInterface* _Nullable arg);
void return_void(void);
uint16_t return_char(void);
bool return_boolean(void);
int8_t return_byte(void);
uint8_t return_ubyte(void);
int16_t return_short(void);
uint16_t return_ushort(void);
int32_t return_int(void);
uint32_t return_uint(void);
int64_t return_long(void);
uint64_t return_ulong(void);
float return_float(void);
double return_double(void);
KString* _Nonnull return_string(void);
KString* _Nullable return_string_n(void);
MyEnum return_enum(void);
MyDictionary* _Nonnull return_dictionary(void);
MyDictionary* _Nullable return_dictionary_n(void);
uint16_t ping_char(uint16_t arg);
bool ping_boolean(bool arg);
int8_t ping_byte(int8_t arg);
uint8_t ping_ubyte(uint8_t arg);
int16_t ping_short(int16_t arg);
uint16_t ping_ushort(uint16_t arg);
int32_t ping_int(int32_t arg);
uint32_t ping_uint(uint32_t arg);
int64_t ping_long(int64_t arg);
uint64_t ping_ulong(uint64_t arg);
float ping_float(float arg);
double ping_double(double arg);
KString* _Nonnull ping_string(KString* _Nonnull arg);
KString* _Nullable ping_string_n(KString* _Nullable arg);
MyEnum ping_enum(MyEnum arg);
MyDictionary* _Nonnull ping_dictionary(MyDictionary* _Nonnull arg);
MyDictionary* _Nullable ping_dictionary_n(MyDictionary* _Nullable arg);
RC_MyInterface* _Nonnull ping_interface(RC_MyInterface* _Nonnull arg);
RC_MyInterface* _Nullable ping_interface_n(RC_MyInterface* _Nullable arg);
void callback_void(RC_VoidCallback* _Nonnull arg);
bool callback_void_n(RC_VoidCallback* _Nullable arg);
bool callback_arg_char(RC_CallbackPassChar* _Nonnull arg);
bool callback_arg_boolean(RC_CallbackPassBoolean* _Nonnull arg);
bool callback_arg_byte(RC_CallbackPassByte* _Nonnull arg);
bool callback_arg_ubyte(RC_CallbackPassUByte* _Nonnull arg);
bool callback_arg_short(RC_CallbackPassShort* _Nonnull arg);
bool callback_arg_ushort(RC_CallbackPassUShort* _Nonnull arg);
bool callback_arg_int(RC_CallbackPassInt* _Nonnull arg);
bool callback_arg_uint(RC_CallbackPassUInt* _Nonnull arg);
bool callback_arg_long(RC_CallbackPassLong* _Nonnull arg);
bool callback_arg_ulong(RC_CallbackPassULong* _Nonnull arg);
bool callback_arg_float(RC_CallbackPassFloat* _Nonnull arg);
bool callback_arg_double(RC_CallbackPassDouble* _Nonnull arg);
bool callback_arg_string(RC_CallbackPassString* _Nonnull arg);
bool callback_arg_string_n(RC_CallbackPassStringN* _Nonnull arg);
bool callback_arg_callback(RC_VoidCallback* _Nonnull pass, RC_CallbackPassCallback* _Nonnull arg);
bool callback_arg_callback_n(RC_CallbackPassCallbackN* _Nonnull arg);
bool callback_arg_enum(RC_CallbackPassEnum* _Nonnull arg);
bool callback_arg_dictionary(RC_CallbackPassDictionary* _Nonnull arg);
bool callback_arg_dictionary_n(RC_CallbackPassDictionaryN* _Nonnull arg);
bool callback_arg_interface(RC_MyInterface* _Nonnull pass, RC_CallbackPassInterface* _Nonnull arg);
bool callback_arg_interface_n(RC_CallbackPassInterfaceN* _Nonnull arg);
bool callback_return_char(RC_CallbackReturnChar* _Nonnull arg);
bool callback_return_boolean(RC_CallbackReturnBoolean* _Nonnull arg);
bool callback_return_byte(RC_CallbackReturnByte* _Nonnull arg);
bool callback_return_ubyte(RC_CallbackReturnUByte* _Nonnull arg);
bool callback_return_short(RC_CallbackReturnShort* _Nonnull arg);
bool callback_return_ushort(RC_CallbackReturnUShort* _Nonnull arg);
bool callback_return_int(RC_CallbackReturnInt* _Nonnull arg);
bool callback_return_uint(RC_CallbackReturnUInt* _Nonnull arg);
bool callback_return_long(RC_CallbackReturnLong* _Nonnull arg);
bool callback_return_ulong(RC_CallbackReturnULong* _Nonnull arg);
bool callback_return_float(RC_CallbackReturnFloat* _Nonnull arg);
bool callback_return_double(RC_CallbackReturnDouble* _Nonnull arg);
bool callback_return_string(RC_CallbackReturnString* _Nonnull arg);
bool callback_return_string_n(RC_CallbackReturnStringN* _Nonnull arg);
RC_VoidCallback* _Nonnull callback_return_callback(RC_CallbackReturnCallback* _Nonnull arg);
bool callback_return_callback_n(RC_CallbackReturnCallbackN* _Nonnull arg);
bool callback_return_enum(RC_CallbackReturnEnum* _Nonnull arg);
bool callback_return_dictionary(RC_CallbackReturnDictionary* _Nonnull arg);
bool callback_return_dictionary_n(RC_CallbackReturnDictionaryN* _Nonnull arg);
bool callback_return_interface(RC_CallbackReturnInterface* _Nonnull arg);
bool callback_return_interface_n(RC_CallbackReturnInterfaceN* _Nonnull arg);
bool pass_char_array(KCharArray* _Nonnull arg);
bool pass_char_array_n(KCharArray* _Nullable arg);
bool pass_boolean_array(KBooleanArray* _Nonnull arg);
bool pass_byte_array(KByteArray* _Nonnull arg);
bool pass_ubyte_array(KUByteArray* _Nonnull arg);
bool pass_short_array(KShortArray* _Nonnull arg);
bool pass_ushort_array(KUShortArray* _Nonnull arg);
bool pass_int_array(KIntArray* _Nonnull arg);
bool pass_uint_array(KUIntArray* _Nonnull arg);
bool pass_long_array(KLongArray* _Nonnull arg);
bool pass_ulong_array(KULongArray* _Nonnull arg);
bool pass_float_array(KFloatArray* _Nonnull arg);
bool pass_double_array(KDoubleArray* _Nonnull arg);
bool pass_string_array(KArray* _Nonnull arg);
bool pass_string_array_n(KArray* _Nonnull arg);
bool pass_enum_array(KIntArray* _Nonnull arg);
bool pass_dictionary_array(KArray* _Nonnull arg);
bool pass_dictionary_array_n(KArray* _Nonnull arg);
bool pass_interface_array(KArray* _Nonnull arg);
bool pass_interface_array_n(KArray* _Nonnull arg);
KCharArray* _Nonnull return_char_array(void);
KCharArray* _Nullable return_char_array_n(void);
KBooleanArray* _Nonnull return_boolean_array(void);
KByteArray* _Nonnull return_byte_array(void);
KUByteArray* _Nonnull return_ubyte_array(void);
KShortArray* _Nonnull return_short_array(void);
KUShortArray* _Nonnull return_ushort_array(void);
KIntArray* _Nonnull return_int_array(void);
KUIntArray* _Nonnull return_uint_array(void);
KLongArray* _Nonnull return_long_array(void);
KULongArray* _Nonnull return_ulong_array(void);
KFloatArray* _Nonnull return_float_array(void);
KDoubleArray* _Nonnull return_double_array(void);
KArray* _Nonnull return_string_array(void);
KArray* _Nonnull return_string_array_n(void);
KIntArray* _Nonnull return_enum_array(void);
KArray* _Nonnull return_dictionary_array(void);
KArray* _Nonnull return_dictionary_array_n(void);
KCharArray* _Nonnull ping_char_array(KCharArray* _Nonnull arg);
KCharArray* _Nullable ping_char_array_n(KCharArray* _Nullable arg);
KBooleanArray* _Nonnull ping_boolean_array(KBooleanArray* _Nonnull arg);
KByteArray* _Nonnull ping_byte_array(KByteArray* _Nonnull arg);
KUByteArray* _Nonnull ping_ubyte_array(KUByteArray* _Nonnull arg);
KShortArray* _Nonnull ping_short_array(KShortArray* _Nonnull arg);
KUShortArray* _Nonnull ping_ushort_array(KUShortArray* _Nonnull arg);
KIntArray* _Nonnull ping_int_array(KIntArray* _Nonnull arg);
KUIntArray* _Nonnull ping_uint_array(KUIntArray* _Nonnull arg);
KLongArray* _Nonnull ping_long_array(KLongArray* _Nonnull arg);
KULongArray* _Nonnull ping_ulong_array(KULongArray* _Nonnull arg);
KFloatArray* _Nonnull ping_float_array(KFloatArray* _Nonnull arg);
KDoubleArray* _Nonnull ping_double_array(KDoubleArray* _Nonnull arg);
KArray* _Nonnull ping_string_array(KArray* _Nonnull arg);
KArray* _Nonnull ping_string_array_n(KArray* _Nonnull arg);
KIntArray* _Nonnull ping_enum_array(KIntArray* _Nonnull arg);
KArray* _Nonnull ping_dictionary_array(KArray* _Nonnull arg);
KArray* _Nonnull ping_dictionary_array_n(KArray* _Nonnull arg);
KArray* _Nonnull ping_interface_array(KArray* _Nonnull arg);
KArray* _Nonnull ping_interface_array_n(KArray* _Nonnull arg);
bool callback_arg_char_array(RC_CallbackPassCharArray* _Nonnull arg);
bool callback_arg_char_array_n(RC_CallbackPassCharArrayN* _Nonnull arg);
bool callback_arg_boolean_array(RC_CallbackPassBooleanArray* _Nonnull arg);
bool callback_arg_byte_array(RC_CallbackPassByteArray* _Nonnull arg);
bool callback_arg_ubyte_array(RC_CallbackPassUByteArray* _Nonnull arg);
bool callback_arg_short_array(RC_CallbackPassShortArray* _Nonnull arg);
bool callback_arg_ushort_array(RC_CallbackPassUShortArray* _Nonnull arg);
bool callback_arg_int_array(RC_CallbackPassIntArray* _Nonnull arg);
bool callback_arg_uint_array(RC_CallbackPassUIntArray* _Nonnull arg);
bool callback_arg_long_array(RC_CallbackPassLongArray* _Nonnull arg);
bool callback_arg_ulong_array(RC_CallbackPassULongArray* _Nonnull arg);
bool callback_arg_float_array(RC_CallbackPassFloatArray* _Nonnull arg);
bool callback_arg_double_array(RC_CallbackPassDoubleArray* _Nonnull arg);
bool callback_arg_string_array(RC_CallbackPassStringArray* _Nonnull arg);
bool callback_arg_string_array_n(RC_CallbackPassStringArrayN* _Nonnull arg);
bool callback_arg_enum_array(RC_CallbackPassEnumArray* _Nonnull arg);
bool callback_arg_dictionary_array(RC_CallbackPassDictionaryArray* _Nonnull arg);
bool callback_arg_dictionary_array_n(RC_CallbackPassDictionaryArrayN* _Nonnull arg);
bool callback_arg_interface_array(RC_CallbackPassInterfaceArray* _Nonnull arg);
bool callback_arg_interface_array_n(RC_CallbackPassInterfaceArrayN* _Nonnull arg);
bool callback_return_char_array(RC_CallbackReturnCharArray* _Nonnull arg);
bool callback_return_char_array_n(RC_CallbackReturnCharArrayN* _Nonnull arg);
bool callback_return_boolean_array(RC_CallbackReturnBooleanArray* _Nonnull arg);
bool callback_return_byte_array(RC_CallbackReturnByteArray* _Nonnull arg);
bool callback_return_ubyte_array(RC_CallbackReturnUByteArray* _Nonnull arg);
bool callback_return_short_array(RC_CallbackReturnShortArray* _Nonnull arg);
bool callback_return_ushort_array(RC_CallbackReturnUShortArray* _Nonnull arg);
bool callback_return_int_array(RC_CallbackReturnIntArray* _Nonnull arg);
bool callback_return_uint_array(RC_CallbackReturnUIntArray* _Nonnull arg);
bool callback_return_long_array(RC_CallbackReturnLongArray* _Nonnull arg);
bool callback_return_ulong_array(RC_CallbackReturnULongArray* _Nonnull arg);
bool callback_return_float_array(RC_CallbackReturnFloatArray* _Nonnull arg);
bool callback_return_double_array(RC_CallbackReturnDoubleArray* _Nonnull arg);
bool callback_return_string_array(RC_CallbackReturnStringArray* _Nonnull arg);
bool callback_return_string_array_n(RC_CallbackReturnStringArrayN* _Nonnull arg);
bool callback_return_enum_array(RC_CallbackReturnEnumArray* _Nonnull arg);
bool callback_return_dictionary_array(RC_CallbackReturnDictionaryArray* _Nonnull arg);
bool callback_return_dictionary_array_n(RC_CallbackReturnDictionaryArrayN* _Nonnull arg);
bool callback_return_interface_array(RC_CallbackReturnInterfaceArray* _Nonnull arg);
bool callback_return_interface_array_n(RC_CallbackReturnInterfaceArrayN* _Nonnull arg);
bool pass_big_dictionary(TypeDictionary* _Nonnull arg);
TypeDictionary* _Nonnull return_big_dictionary(RC_VoidCallback* _Nonnull callback, RC_MyInterface* _Nonnull inter);
TypeDictionary* _Nonnull ping_big_dictionary(TypeDictionary* _Nonnull arg);
bool pass_big_dictionary_n(TypeDictionary* _Nullable arg);
TypeDictionary* _Nullable return_big_dictionary_n(void);
TypeDictionary* _Nullable ping_big_dictionary_n(TypeDictionary* _Nullable arg);
bool critical_primitives(uint16_t a1, bool a2, int8_t a3, uint8_t a4, int16_t a5, uint16_t a6, int32_t a7, uint32_t a8, int64_t a9, uint64_t a10, float a11, double a12);
bool critical_enum(MyEnum a1);
bool critical_string(KString* _Nonnull a1);
bool critical_string_n(KString* _Nullable a1);
bool critical_interface(RC_MyInterface* _Nonnull a1);
bool critical_interface_n(RC_MyInterface* _Nullable a1);
bool critical_primitives_array(KCharArray* _Nonnull a1, KBooleanArray* _Nonnull a2, KByteArray* _Nonnull a3, KUByteArray* _Nonnull a4, KShortArray* _Nonnull a5, KUShortArray* _Nonnull a6, KIntArray* _Nonnull a7, KUIntArray* _Nonnull a8, KLongArray* _Nonnull a9, KULongArray* _Nonnull a10, KFloatArray* _Nonnull a11, KDoubleArray* _Nonnull a12);
bool critical_enum_array(KIntArray* _Nonnull a1);
bool critical_primitives_array_n(KCharArray* _Nullable a1, KBooleanArray* _Nullable a2, KByteArray* _Nullable a3, KUByteArray* _Nullable a4, KShortArray* _Nullable a5, KUShortArray* _Nullable a6, KIntArray* _Nullable a7, KUIntArray* _Nullable a8, KLongArray* _Nullable a9, KULongArray* _Nullable a10, KFloatArray* _Nullable a11, KDoubleArray* _Nullable a12);
bool critical_enum_array_n(KIntArray* _Nullable a1);
uint16_t critical_return_char(void);
bool critical_return_boolean(void);
int8_t critical_return_byte(void);
uint8_t critical_return_ubyte(void);
int16_t critical_return_short(void);
uint16_t critical_return_ushort(void);
int32_t critical_return_int(void);
uint32_t critical_return_uint(void);
int64_t critical_return_long(void);
uint64_t critical_return_ulong(void);
float critical_return_float(void);
double critical_return_double(void);
MyEnum critical_return_enum(void);
RC_MyInterface* _Nonnull critical_return_interface(void);
bool jvmci1(void);
bool jvmci2(int32_t a1);
bool jvmci3(int32_t a1, int32_t a2);
bool jvmci4(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9);
bool jvmci5(int32_t a1, int64_t a2, int32_t a3, int64_t a4, int32_t a5, int64_t a6, int32_t a7, int32_t a8, int64_t a9);
bool jvmci6(float a1, float a2, float a3, float a4, float a5, float a6, float a7, float a8, float a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13);
bool jvmci7(float a1, double a2, float a3, double a4, float a5, double a6, float a7, float a8, double a9);
bool jvmci8(int32_t a1, double a2, float a3, int64_t a4);
bool jvmci9(int32_t a1, double a2, float a3, int64_t a4, int64_t a5, double a6, float a7, float a8, int32_t a9);
bool jvmci10(KString* _Nonnull a1, double a2, float a3, int64_t a4, int64_t a5, double a6, KString* _Nonnull a7, float a8, int32_t a9);
bool jvmci11(float a1, int32_t a2, float a3, int32_t a4, float a5, int32_t a6, float a7, int32_t a8, float a9, int32_t a10, float a11, int32_t a12, float a13, int32_t a14, float a15, int32_t a16, float a17);
int32_t jvmci12(void);
int64_t jvmci13(void);
float jvmci14(void);
double jvmci15(void);
bool jvmci_array(KIntArray* _Nonnull array);
bool jvmci_some_arrays(KIntArray* _Nonnull array1, KFloatArray* _Nonnull array2, KDoubleArray* _Nonnull array3);
bool jvmci_enum(MyEnum enum1, MyEnum enum2, KIntArray* _Nonnull enum_array);
void* _Nonnull _interface_myinterface_new_0(void);
void* _Nonnull _interface_myinterface_new_1(int32_t a);
bool _interface_myinterface_fn_test(void* _Nonnull _self);
bool _interface_myinterface_fn_test_critical(void* _Nonnull _self);
void _interface_myinterface_fn_pass_interface(void* _Nonnull _self, RC_MyInterface* _Nonnull a1);
RC_MyInterface* _Nonnull _interface_myinterface_fn_return_interface(void* _Nonnull _self);
void _interface_myinterface_free(void* _Nonnull _self);
