/*
 * This file was automatically generated by Gradle.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Any changes made to this file will be overwritten the next time
 * the project is built.
 */
 
#ifndef KOTLIN_NATIVE_GLFWBINDINGS_H
#define KOTLIN_NATIVE_GLFWBINDINGS_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* =================== *\
        Functions
\* =================== */

void run();
void glfwInit();

#ifdef __cplusplus
}
#endif

#endif // KOTLIN_NATIVE_GLFWBINDINGS_H